import React from "react";
import { Link } from "react-router-dom";

const DATA = {
  "calorie": {
    title: "Calorie Calculator: Estimate Your Daily Calorie Needs",
    quick: "A calorie calculator estimates how much energy you may need each day from your age, sex, height, weight and activity level. FitMe Pro uses a BMR-based approach and applies activity to estimate daily energy needs.",
    formula: "BMR = 10W + 6.25H − 5A + S; estimated daily calories = BMR × activity factor.",
    inputs: "Age, sex, height, body weight and typical activity level. Keep units consistent and choose the activity level that best represents your normal routine.",
    method: ["Convert height and weight into the units required by the equation.", "Estimate resting energy expenditure with the Mifflin-St Jeor equation.", "Apply an activity factor to estimate total daily energy expenditure.", "Use the estimate as a starting point and compare it with your real-world weight trend before making large changes."],
    meaning: "The result is an estimated daily calorie requirement. It can provide a starting maintenance level, but actual energy expenditure varies between people and from day to day.",
    example: "A 30-year-old man weighing 70 kg at 175 cm has an estimated BMR of about 1,699 kcal/day. With moderate activity, the estimate is about 2,633 kcal/day.",
    limits: "Equations cannot directly observe every source of energy expenditure. Exercise, spontaneous movement, body composition, sleep, illness and other factors can change actual needs.",
    links: [["BMR Calculator","/bmr-calculator"],["TDEE Calculator","/tdee-calculator"],["Calorie Deficit Calculator","/calorie-deficit-calculator"],["Maintenance Calories Calculator","/maintenance-calories-calculator"],["Macro Calculator","/macronutrient-calculator"]],
    faqs: [["How many calories should I eat per day?","It depends on your body size, age, sex, activity and goal. A calculator provides an estimate rather than one universal number."],["Is this calorie calculator accurate?","It is a useful estimate, but actual energy expenditure can differ. Multi-week trends are more informative than treating the result as exact."],["Are calorie needs the same as TDEE?","For practical diet planning, daily calorie needs and TDEE commonly describe the same estimated daily energy requirement."],["How many calories should I eat to lose weight?","Weight loss generally requires a sustained energy deficit. The appropriate deficit depends on the individual and should be reasonable rather than extreme."],["Do I need fewer calories after losing weight?","Often yes. A smaller body generally uses less energy, and activity can change as well."],["Does exercise increase calorie needs?","Yes. Physical activity contributes to total daily energy expenditure."],["Should I eat exactly the calculator result?","Not necessarily. Treat it as a starting estimate and adjust based on your goal and observed trend."],["Can this be used for medical diets?","Not by itself. Medical nutrition plans may require individualized assessment by a qualified professional."]]
  },
  "body-fat": {
    title: "Body Fat Calculator: Estimate Body Fat Percentage",
    quick: "Body fat percentage is the proportion of total body weight made up of fat tissue. FitMe Pro estimates body fat using a BMI- and age-based equation, so the result is an estimate rather than a direct measurement.",
    formula: "Deurenberg equation: body fat % = 1.2 × BMI + 0.23 × age − 10.8 × sex − 5.4, with the sex term represented by the equation's male/female coding.",
    inputs: "Height, weight, age and sex. Because the equation depends on BMI, accurate height and weight are important inputs.",
    method: ["Calculate BMI from height and weight.", "Combine BMI with age and the sex-specific term in the Deurenberg equation.", "Return the estimated body-fat percentage.", "Interpret the estimate alongside body size, fat distribution and other measurements rather than as a diagnosis."],
    meaning: "The result estimates the percentage of your body weight that is fat. It can add context beyond body weight alone, but it does not directly measure fat tissue.",
    example: "For a 30-year-old man at 70 kg and 175 cm, BMI is about 22.9. The Deurenberg equation gives an estimated body-fat percentage of about 18.2%.",
    limits: "BMI-based equations can have meaningful individual error. Hydration, body composition, muscularity, age and population differences can affect how well an estimate represents an individual.",
    links: [["BMI Calculator","/bmi-calculator"],["Lean Body Mass Calculator","/lean-body-mass-calculator"],["Fat Mass Calculator","/fat-mass-calculator"],["Fat-Free Mass Calculator","/fat-free-mass-calculator"],["Waist-to-Height Ratio Calculator","/waist-to-height-ratio-calculator"]],
    faqs: [["What is body fat percentage?","It is the percentage of total body weight attributable to fat tissue."],["How does FitMe Pro estimate body fat?","The calculator uses the Deurenberg BMI-based equation using BMI, age and sex."],["Is body fat percentage more useful than BMI?","They measure different things. BMI describes weight relative to height, while body-fat percentage estimates the proportion of weight that is fat."],["How accurate is a body-fat calculator?","It is an estimate and can differ from direct or instrument-based measurements. Consistent tracking can still be useful."],["Why can two body-fat calculators give different results?","They may use different equations, inputs or reference assumptions."],["Can muscular people have a misleading result?","Yes. BMI-based equations can be less representative for people with unusually high or low muscularity."],["Does age affect estimated body fat?","Yes. Age is an input in the Deurenberg equation."],["Should I use one body-fat number as a health diagnosis?","No. A calculator result is not a diagnosis and should be considered alongside other health information."]]
  },
  "calorie-deficit": {
    title: "Calorie Deficit Calculator: Estimate a Weight-Loss Calorie Target",
    quick: "A calorie deficit means consuming fewer calories than your body uses over time. This calculator uses estimated maintenance calories and a selected deficit to show a planning target; it does not guarantee a specific rate of weight loss.",
    formula: "Calorie target = estimated maintenance calories − selected daily deficit. A 500 kcal/day deficit is a common reference point, not a universal prescription.",
    inputs: "Current body information, activity level and the desired calorie deficit. The maintenance estimate is based on predicted energy expenditure rather than a laboratory measurement.",
    method: ["Estimate maintenance calories from BMR and activity.", "Choose a reasonable daily deficit.", "Subtract the deficit from estimated maintenance calories.", "Monitor progress over several weeks and adjust cautiously if the observed trend differs from the plan."],
    meaning: "A deficit is an energy-balance concept, not a promise of a fixed amount of fat loss. Scale weight can also change because of water, glycogen and food volume.",
    example: "If estimated maintenance is 2,500 kcal/day and the selected deficit is 500 kcal/day, the planning target is 2,000 kcal/day. Actual results should be evaluated from the longer-term trend.",
    limits: "The 3,500-calorie-per-pound rule and similar simple conversions are only rough planning models. Metabolic adaptation, activity changes and imperfect food tracking mean real-world weight change is not perfectly linear.",
    links: [["TDEE Calculator","/tdee-calculator"],["Maintenance Calories Calculator","/maintenance-calories-calculator"],["Daily Calorie Needs Calculator","/daily-calorie-needs-calculator"],["Weight Loss Calorie Calculator","/weight-loss-calorie-calculator"],["Protein Calculator","/protein-calculator"]],
    faqs: [["What is a calorie deficit?","It is a period in which energy intake is below energy expenditure on average."],["How large should my calorie deficit be?","There is no single appropriate deficit for everyone. A moderate, sustainable approach is generally preferable to extreme restriction."],["Is a 500-calorie deficit safe for everyone?","No. Individual needs differ, and very low calorie intake can be inappropriate. People with medical or nutritional concerns should seek professional guidance."],["How fast will I lose weight?","The rate varies. Water and glycogen can cause short-term changes, while longer-term trends better reflect sustained weight change."],["Does a calorie deficit always mean fat loss?","A sustained energy deficit generally supports weight loss, but changes in body water and lean tissue can also contribute to scale changes."],["Should I recalculate my deficit after losing weight?","It can be useful because maintenance needs may change as body weight and activity change."],["Can exercise create a calorie deficit?","Yes. Increased energy expenditure through activity can contribute to an overall deficit."],["Why did my weight stop falling?","Plateaus can reflect changes in water, activity, intake, body weight or adherence. Look at a multi-week trend before making a major adjustment."]]
  },
  "calories-burned": {
    title: "Calories Burned Calculator: Estimate Exercise Energy Expenditure",
    quick: "A calories-burned calculator estimates energy expenditure from an activity using factors such as body weight, activity intensity and duration. The result is an estimate, not a direct measurement of calories used.",
    formula: "A common approach uses METs: calories ≈ MET × 3.5 × body weight(kg) ÷ 200 × minutes.",
    inputs: "Body weight, exercise type, intensity and duration. Some activities can also require speed, distance or other activity-specific inputs.",
    method: ["Enter your body weight using the requested unit.", "Select the activity that best matches what you performed.", "Enter the duration and any activity-specific intensity information.", "Interpret the output as an estimated energy cost rather than a precise count of calories burned."],
    meaning: "The estimate represents energy expenditure associated with the selected activity. It should not automatically be treated as calories that must be eaten back after exercise.",
    example: "For a 70 kg person, a 30-minute activity at an assumed MET of 5 gives roughly 184 kcal using the standard MET equation. The actual cost depends on intensity and the individual.",
    limits: "MET values are standardized estimates. Real energy expenditure can differ because of fitness, movement efficiency, terrain, technique, intensity and individual physiology.",
    links: [["Walking Calorie Calculator","/walking-calorie-calculator"],["Running Calorie Calculator","/running-calorie-calculator"],["Exercise Calorie Calculator","/exercise-calorie-calculator"],["TDEE Calculator","/tdee-calculator"],["Calorie Deficit Calculator","/calorie-deficit-calculator"]],
    faqs: [["How are calories burned during exercise calculated?","A common method combines an activity's MET value with body weight and exercise duration."],["Are calories-burned calculators accurate?","They provide estimates. Actual energy expenditure varies with intensity, technique, fitness and individual physiology."],["Does body weight affect calories burned?","Yes. Heavier bodies generally expend more energy performing the same activity at the same assumed intensity and duration."],["Does exercise intensity matter?","Yes. Higher-intensity activity generally has a higher energy cost per unit of time."],["Should I eat back all exercise calories?","Not automatically. Exercise estimates can have substantial uncertainty, and dietary needs depend on your overall goal and intake."],["Why do fitness watches show different calorie numbers?","Devices use different sensors, algorithms and assumptions, so estimates can differ."],["Can I use calories burned for weight loss?","It can help you understand activity energy expenditure, but weight change depends on overall energy balance over time."],["What is a MET?","MET is a standardized way of expressing activity energy cost relative to resting metabolism."]]
  },
  "water-intake": {
    title: "Water Intake Calculator: Estimate Daily Fluid Needs",
    quick: "A water-intake calculator provides a practical estimate of daily fluid needs from factors such as body size and activity. It is a starting point, not a universal prescription for every person or situation.",
    formula: "A simple body-weight approach may estimate fluid needs from body weight; FitMe Pro presents the result as an estimate and not a medical requirement.",
    inputs: "Body weight and, where supported, activity or other context. Fluid needs also depend on temperature, sweating, diet, illness, pregnancy and other factors.",
    method: ["Enter your body weight and relevant activity information.", "Apply the calculator's selected fluid-intake estimate.", "Convert the result into the displayed unit such as litres or fluid ounces.", "Use thirst, urine color, environmental conditions and professional advice where relevant to adjust intake appropriately."],
    meaning: "The result is a planning estimate for fluid intake. Total water comes from beverages and water contained in foods, so a calculator output should not necessarily be interpreted as the exact amount of plain water to drink.",
    example: "If a method estimates 35 mL of fluid per kg for a 70 kg adult, the calculation gives about 2.45 L/day. This is an example of the formula, not an individual medical prescription.",
    limits: "Fluid requirements vary widely. Heat, exercise, sweating, illness, pregnancy, breastfeeding, medications and kidney or heart conditions can change needs. Some medical conditions require specific fluid guidance.",
    links: [["TDEE Calculator","/tdee-calculator"],["Body Fat Calculator","/body-fat-calculator"],["Healthy Weight Range Calculator","/healthy-weight-range-calculator"],["Protein Calculator","/protein-calculator"]],
    faqs: [["How much water should I drink per day?","Needs vary by person and conditions. A calculator can provide a starting estimate, while thirst, environment and activity also matter."],["Does water intake depend on body weight?","Body size is one factor that can be used for an estimate, but it is not the only determinant of fluid needs."],["Does exercise increase water needs?","Usually, because sweating increases fluid loss. Hot or humid conditions can increase losses further."],["Does food count toward daily water intake?","Yes. Total water intake includes water from beverages and food."],["Is more water always better?","No. Excessive fluid intake can also be harmful. Intake should match needs rather than maximizing water consumption."],["Should I drink extra water in hot weather?","Heat can increase fluid losses, especially when sweating, so fluid needs may rise."],["What if I have kidney or heart problems?","Fluid recommendations can be condition-specific. Follow the advice of your healthcare professional rather than relying on a general calculator."],["Can this calculator diagnose dehydration?","No. It estimates intake and cannot diagnose dehydration or other medical conditions."]]
  }
};

export default function Phase2SEOContent({ slug }) {
  const data = DATA[slug];
  if (!data) return null;
  return <div className="space-y-8" data-testid={`phase2-seo-${slug}`}>
    <section><h3 className="font-display text-2xl sm:text-3xl uppercase tracking-tight mb-3">{data.title}</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.quick}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Quick Answer</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.quick}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Formula & Method</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.formula}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">How It Is Calculated</h3><ol className="list-decimal pl-6 space-y-2 text-sm sm:text-base text-muted-foreground leading-8">{data.method.map((x,i)=><li key={i}>{x}</li>)}</ol></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Inputs Explained</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.inputs}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">What Does My Result Mean?</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.meaning}</p></section>
    <section className="border border-border bg-card p-6"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Worked Example</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.example}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Accuracy & Limitations</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.limits}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-4">Frequently Asked Questions</h3><div className="space-y-5">{data.faqs.map(([q,a])=><div key={q}><h4 className="font-semibold mb-1">{q}</h4><p className="text-sm text-muted-foreground leading-7">{a}</p></div>)}</div></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-4">Related Calculators</h3><div className="grid sm:grid-cols-2 gap-2">{data.links.map(([label,to])=><Link key={to} to={to} className="border border-border px-4 py-3 text-sm font-bold hover:text-[var(--brand-lime)] hover:border-[var(--brand-lime)] transition-colors">{label}</Link>)}</div></section>
    <section className="border border-border p-6 bg-card"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Important Health Note</h3><p className="text-sm text-muted-foreground leading-7">FitMe Pro provides educational estimates and does not diagnose disease or replace professional care. Do not use calculator results as a substitute for individualized medical, nutrition or exercise advice when such advice is needed.</p></section>
  </div>;
}
