import React from "react";
import { Link } from "react-router-dom";

const DATA = {
  "walking-calories": {
    title: "Walking Calories Calculator Guide",
    quick: "A walking-calorie estimate uses body weight, walking duration or distance, and exercise intensity to approximate energy expenditure. The result is an estimate, not a direct measurement of calories burned.",
    formula: "Calories ≈ MET × 3.5 × body weight(kg) ÷ 200 × time(minutes)",
    method: "The calculator estimates energy expenditure from body weight and walking intensity over the selected duration. Speed, incline, terrain, fitness level and walking efficiency can change the actual value.",
    inputs: "Enter your body weight and the walking information requested by the calculator, such as duration, distance or speed. Use consistent units and avoid treating a single session estimate as an exact measurement.",
    meaning: "Higher body weight, greater intensity and longer duration generally increase estimated energy expenditure. The number should be used for planning and comparison rather than as a precise calorie ledger.",
    example: "For example, a 70 kg person walking for 60 minutes will receive an estimate based on the selected walking intensity. A faster pace or uphill route can produce a higher estimate than easy level walking.",
    limits: "Wearables and formulas can disagree because they use different assumptions. Incline, terrain, gait, fitness and device algorithms all affect estimates. Do not compensate for every reported calorie with food automatically.",
    faqs: [
      ["How many calories does walking burn?", "It depends mainly on body weight, duration and intensity. Longer and faster walks generally use more energy."],
      ["Does walking speed affect calories burned?", "Yes. Faster walking generally increases energy expenditure per unit of time."],
      ["Does body weight affect walking calories?", "Yes. A heavier body generally requires more energy to move the same distance."],
      ["Does incline increase walking calories?", "Yes. Uphill walking increases exercise intensity and can substantially change an estimate."],
      ["Are walking-calorie estimates exact?", "No. They are model-based estimates and can differ from measured energy expenditure."],
      ["Should I eat back calories burned walking?", "Not automatically. Exercise estimates have uncertainty, and nutrition decisions should consider overall goals and intake."],
      ["Is walking good for weight management?", "Regular walking can contribute to physical activity and energy expenditure, while sustainable weight management also depends on overall diet and lifestyle."],
      ["What should I track besides calories?", "Track walking time, distance, pace, frequency and how your fitness changes over time."],
    ],
    related: ["Pace Calculator", "Calories Burned Calculator", "Daily Calorie Needs", "TDEE Calculator"],
  },
  "macro-calculator": {
    title: "Macro Calculator Guide",
    quick: "A macro calculator estimates daily protein, carbohydrate and fat targets from calorie needs and a chosen macronutrient distribution. These targets are planning estimates, not mandatory numbers.",
    formula: "Protein and carbohydrate = 4 kcal/g; fat = 9 kcal/g",
    method: "The calculator starts with an estimated calorie target and allocates calories among protein, carbohydrate and fat according to the selected targets. Calories are then converted to grams using the energy values of each macronutrient.",
    inputs: "Use your calorie target and the macro percentages or targets requested by the calculator. If your calorie target is itself estimated from BMR and activity, remember that uncertainty carries through to the macro result.",
    meaning: "The result tells you how many grams of each macronutrient fit your selected calorie framework. It does not mean that one exact macro split is universally optimal.",
    example: "If a 2,000 kcal plan allocates 30% to protein, 40% to carbohydrate and 30% to fat, the approximate targets are 150 g protein, 200 g carbohydrate and 67 g fat.",
    limits: "Macro targets depend on goals, activity, food preferences and total energy needs. Food labels and portion estimates also introduce error. Prioritize overall diet quality and consistency over tiny differences in macro grams.",
    faqs: [
      ["What are macros?", "Macros are macronutrients: protein, carbohydrate and fat, the main nutrients that provide dietary energy."],
      ["How are macro grams calculated?", "Protein and carbohydrate provide about 4 kcal per gram, while fat provides about 9 kcal per gram."],
      ["What macro split should I use?", "There is no single ideal split for everyone. Targets should fit your energy needs, activity, goals and dietary preferences."],
      ["Should protein be calculated before carbs and fat?", "Often it is useful to establish an appropriate protein target first, then distribute remaining calories according to goals and preference."],
      ["Can macros help with weight loss?", "They can help organize food intake, but total energy intake and sustainable eating habits remain important."],
      ["Do I need to hit macros exactly?", "No. Small daily differences are normal. Consistency over time is generally more useful than perfect precision."],
      ["Are macro percentages the same as macro grams?", "No. Percentages describe calorie allocation; grams depend on the calorie density of each macronutrient."],
      ["Can athletes use a macro calculator?", "Yes, as a planning tool. Higher training loads may change energy and carbohydrate requirements, so targets should be adjusted as training changes."],
    ],
    related: ["Protein Calculator", "Daily Calorie Needs", "Calorie Deficit Calculator", "Meal Macro Calculator"],
  },
  "vo2-max": {
    title: "VO₂ Max Calculator Guide",
    quick: "VO₂ max is an estimate of maximal oxygen uptake, commonly expressed in millilitres of oxygen per kilogram of body weight per minute. It is widely used as an indicator of aerobic fitness.",
    formula: "Formula depends on the test protocol used",
    method: "VO₂ max can be measured directly with a graded exercise test and respiratory gas analysis. Field and wearable methods instead estimate it from performance, heart rate and other inputs. FitMe Pro presents an estimate based on its selected method.",
    inputs: "Use the exact performance, time, distance, heart-rate or demographic inputs requested by the calculator. Results from different protocols should not be assumed to be directly interchangeable.",
    meaning: "A higher VO₂ max generally indicates greater aerobic capacity, but interpretation depends on age, sex, training status and the test method. Changes over time can be more useful than comparing unrelated protocols.",
    example: "For example, two runners may have different estimated VO₂ max values because their race performance and body weights differ. The estimate is most useful when repeated with the same method under similar conditions.",
    limits: "Estimated VO₂ max is not the same as laboratory-measured VO₂ max. Heat, fatigue, terrain, pacing, heart-rate accuracy and the equation used can affect the result.",
    faqs: [
      ["What is VO₂ max?", "VO₂ max is the maximum rate at which the body can take in and use oxygen during intense exercise."],
      ["What does a higher VO₂ max mean?", "It generally reflects greater aerobic capacity, although context and measurement method matter."],
      ["Can a calculator measure VO₂ max directly?", "No. A calculator estimates it from selected inputs. Direct measurement requires specialized exercise testing and gas analysis."],
      ["Can VO₂ max improve with training?", "Aerobic training can improve cardiorespiratory fitness, although the amount of change varies between people."],
      ["Why do different VO₂ max calculators give different results?", "They may use different tests, equations, assumptions and input variables."],
      ["Does body weight affect relative VO₂ max?", "Yes. Relative VO₂ max is expressed per kilogram of body weight, so body mass affects the reported value."],
      ["Are smartwatch VO₂ max estimates accurate?", "They can be useful for tracking trends, but they are estimates and should not be treated as laboratory measurements."],
      ["Should I compare my VO₂ max with someone else's?", "Only cautiously. Age, sex, training history and the measurement protocol can make direct comparisons misleading."],
    ],
    related: ["Pace Calculator", "Running Speed Calculator", "Cardio Fitness Level Calculator", "Maximum Heart Rate Calculator"],
  },
  "healthy-weight-range": {
    title: "Healthy Weight Range Calculator Guide",
    quick: "A healthy-weight-range calculator estimates the body-weight range corresponding to an adult BMI range of 18.5 to 24.9 for a given height. BMI is a screening measure rather than a diagnosis.",
    formula: "Weight = BMI × height²; range uses BMI 18.5–24.9",
    method: "Convert height to metres, square it, and multiply by the lower and upper BMI boundaries. The result is the range of weights that correspond mathematically to that BMI interval.",
    inputs: "The main input is height. Enter it accurately and use the same unit system throughout the calculation. Age, sex and body composition are not part of this BMI-based range calculation.",
    meaning: "The result describes a BMI-based reference range, not an individualized ideal weight. Muscularity, fat distribution, age, pregnancy and other factors can make BMI less informative for an individual.",
    example: "At 1.75 m, the BMI-based range is approximately 56.7 kg to 76.3 kg using BMI values of 18.5 and 24.9.",
    limits: "BMI does not distinguish fat from muscle and should not be used alone to assess health. A clinician can combine weight with waist circumference, medical history, laboratory data and other measures when appropriate.",
    faqs: [
      ["How do I calculate my healthy weight range?", "For adults, a BMI-based healthy-weight range is calculated by multiplying height in metres squared by the lower and upper BMI boundaries, commonly 18.5 and 24.9."],
      ["What is the standard healthy weight range calculator?", "A standard adult calculator can convert the BMI range of 18.5–24.9 into weights for your height. It is a screening reference rather than a diagnosis or personalized medical target."],
      ["How to check my ideal weight online for free?", "Enter your height into a reputable healthy-weight or BMI calculator. Treat the result as a reference range; there is not one universally ideal weight for every person of the same height."],
      ["What is the most accurate healthy weight calculator?", "No calculator can determine a single exact healthy weight. A BMI-based calculator is useful for screening, while waist measurements, body composition and health history add individual context."],
      ["How much should I weigh according to my height and gender?", "For adult BMI calculations, the same BMI boundaries are generally used regardless of sex. Height determines the mathematical weight range, while body composition and health context can differ."],
      ["What is my target weight range for optimum health?", "A target should not be chosen from weight alone. An adult BMI-based range can provide a starting reference, but your health history, body composition, waist size and goals also matter."],
      ["How is healthy weight range calculated online?", "The calculator converts height to metres, squares it, and multiplies it by the selected lower and upper BMI values. This produces the weights corresponding to that BMI interval."],
      ["Where can I find a healthy weight chart and calculator?", "A healthy-weight chart can show BMI-based ranges by height, while a calculator gives the same relationship for your exact height. Use charts as screening tools rather than personalized medical advice."],
      ["How to know if my current weight is in a healthy range?", "Compare your weight with the adult BMI-based range for your height, then consider other indicators such as waist circumference and body composition. BMI alone does not establish whether someone is healthy."],
      ["What is the weight calculator formula for normal weight?", "For a BMI-based range, weight equals BMI multiplied by height squared. Using 18.5 and 24.9 gives the commonly used adult BMI reference range."],
      ["How to calculate healthy weight in kilograms and pounds?", "Calculate the range in kilograms using height in metres, then convert kilograms to pounds by multiplying by about 2.205. Keeping units consistent prevents calculation errors."],
      ["What is the healthy weight range for adults?", "For adults, the commonly used BMI category called healthy or normal weight is 18.5–24.9. The corresponding kilogram or pound range depends on height."],
      ["What is the healthy weight range for a 5'2\" female?", "At 5 feet 2 inches, or about 1.575 m, a BMI of 18.5–24.9 corresponds to roughly 45.9–61.8 kg, or about 101–136 lb."],
      ["What is the ideal weight range for a 5'4\" woman?", "At 5 feet 4 inches, or about 1.626 m, BMI 18.5–24.9 corresponds to roughly 48.9–65.8 kg, or about 108–145 lb."],
      ["What should a 5'6\" female weigh in kg?", "At 5 feet 6 inches, or about 1.676 m, the BMI 18.5–24.9 range is approximately 52.0–70.0 kg. This is a BMI reference, not an individualized ideal."],
      ["What is the healthy weight for a 5'8\" male?", "At 5 feet 8 inches, or about 1.727 m, BMI 18.5–24.9 corresponds to approximately 55.2–74.3 kg. Muscle mass and body composition can change how useful BMI is."],
      ["What is the ideal weight range for a 5'10\" man?", "At 5 feet 10 inches, or about 1.778 m, BMI 18.5–24.9 corresponds to approximately 58.5–78.7 kg. The range is a screening reference rather than a required target."],
      ["What is a healthy weight for a 6 foot tall man?", "At 6 feet, or about 1.829 m, BMI 18.5–24.9 corresponds to roughly 61.9–83.3 kg. A person's health cannot be determined from this range alone."],
      ["What is the normal weight range for 5'0\" height?", "At 5 feet, or about 1.524 m, BMI 18.5–24.9 corresponds to approximately 43.0–57.8 kg, or about 95–127 lb."],
      ["What is a healthy weight range for 5'3\" in lbs?", "At 5 feet 3 inches, or about 1.600 m, BMI 18.5–24.9 corresponds to approximately 104–140 lb."],
      ["What is the ideal weight for a 5'5\" woman in kilograms?", "At 5 feet 5 inches, or about 1.651 m, BMI 18.5–24.9 corresponds to roughly 50.4–67.9 kg. This should be interpreted as a BMI range, not an ideal body weight."],
      ["What should a 5'7\" male weigh in pounds?", "At 5 feet 7 inches, or about 1.702 m, BMI 18.5–24.9 corresponds to roughly 118–159 lb."],
      ["What is the healthy weight range for a 5'9\" female?", "At 5 feet 9 inches, or about 1.753 m, BMI 18.5–24.9 corresponds to approximately 57.0–76.5 kg, or about 126–169 lb."],
      ["What is the normal weight range for 6'2\" height?", "At 6 feet 2 inches, or about 1.88 m, BMI 18.5–24.9 corresponds to approximately 65.4–88.0 kg, or about 144–194 lb."],
      ["Why do men and women have different healthy weight ranges for the same height?", "The adult BMI range itself is generally the same, but men and women can differ in average body composition and fat distribution. Those differences are one reason weight alone should not be interpreted in isolation."],
      ["How does biological sex affect the ideal body weight calculation?", "Many height-based ideal-weight formulas use sex-specific constants, so they can produce different estimates. BMI-based healthy-weight ranges generally do not use separate adult cutoffs by sex."],
      ["What is the average healthy weight for short females?", "There is no single healthy weight for all shorter women. The appropriate BMI-based range depends on height, while body composition, waist size and health history provide additional context."],
      ["What is the target healthy weight for tall males?", "There is no universal target for tall men. A BMI-based range can be calculated from height, but a personal target should also account for body composition, health and goals."],
      ["Is there a different healthy weight calculator for men vs women?", "A BMI-based adult calculator can use the same BMI thresholds for men and women. Some ideal-body-weight formulas are sex-specific, so those calculators may produce different results."],
      ["How to calculate healthy weight range for petite women?", "Use the woman's measured height in the BMI equation rather than a generic petite-weight chart. For adults, the standard BMI-based range can then be interpreted alongside body composition and health measures."],
      ["How much should I weigh for my age and height?", "For adults, height is central to BMI-based weight ranges, while age does not normally change the standard adult BMI boundaries. Older adults may need broader clinical context."],
      ["What is a healthy weight range for teenagers aged 13–18?", "Teenagers should not normally use the adult 18.5–24.9 range as a simple target. Growth is assessed using age- and sex-specific BMI-for-age percentiles or other pediatric measures."],
      ["How does ideal weight change as you get older?", "There is no single formula that makes an ideal weight automatically change with age. Aging can change muscle and fat distribution, so clinicians may consider body composition and function in addition to weight."],
      ["What is a healthy weight range for seniors over 60?", "Older adults need individualized interpretation because muscle loss, chronic disease, medications and functional status can affect the meaning of body weight and BMI. A standard BMI range is only one reference."],
      ["How to calculate healthy weight range for young adults aged 18–25?", "Once adult BMI categories apply, calculate the range from height using the adult BMI boundaries. Individual health, body composition and activity still matter."],
      ["Is the healthy weight calculator suitable for children under 12?", "A standard adult BMI-based calculator is not appropriate for children. Pediatric weight status is assessed using BMI-for-age and sex-specific growth charts."],
      ["How does aging affect recommended body mass index and weight?", "The standard adult BMI categories do not simply become a different healthy range with each birthday. However, aging changes body composition and health risks, so clinicians may interpret BMI with additional measures."],
      ["What is a healthy weight range during pregnancy?", "Pregnancy should not be managed with a standard adult healthy-weight range. Recommended pregnancy weight gain is based largely on pre-pregnancy BMI and should be discussed with a maternity-care professional."],
      ["How much weight should I gain during pregnancy calculator?", "Pregnancy weight-gain recommendations depend on pre-pregnancy BMI, whether the pregnancy is singleton or multiple, and clinical circumstances. A pregnancy-specific calculator is more appropriate than a healthy-weight-range calculator."],
      ["What is the healthy weight range for post-menopausal women?", "There is no separate universal post-menopausal weight range. After menopause, changes in fat distribution and muscle mass make waist measurement, strength, activity and overall health useful alongside BMI."],
      ["Does ideal body weight decrease after age 50?", "Not automatically. Age alone does not establish a lower ideal weight. In later adulthood, preserving muscle and function can be important when setting weight goals."],
      ["How to calculate target body weight for middle-aged adults?", "Start with a height-based BMI reference if appropriate, then set a practical target using current weight, body composition, waist circumference, health conditions and sustainable lifestyle goals."],
      ["How do I adjust ideal weight calculations for body frame size?", "Traditional frame-size adjustments use measurements such as wrist circumference, but these formulas are rough and are not standard clinical measures of health. Modern assessment can use BMI plus body composition and waist measurements."],
      ["How to measure wrist size to find frame size for weight calculation?", "A wrist circumference can be measured with a flexible tape around the wrist at a consistent point. Frame-size charts may use this measurement, but results should be treated as estimates rather than medical classifications."],
      ["What is the healthy weight range for a broad-framed person?", "A broad frame does not automatically create a separate medically defined healthy-weight range. Height-based BMI is unchanged, while body composition and waist size can provide additional information."],
      ["Does a muscular build affect healthy weight range calculations?", "Yes. BMI cannot distinguish muscle from fat, so a muscular person can fall above the BMI-based range while having relatively low body fat."],
      ["Why am I considered overweight on a calculator if I have high muscle mass?", "BMI is calculated from height and weight and does not identify what the weight is made of. High muscle mass can therefore increase BMI without implying the same body-fat level as in a less muscular person."],
      ["How does body fat percentage change my target weight range?", "Body-fat percentage provides information that BMI does not. If body composition is known, it can help put a scale-weight result into context, although there is no single body-fat percentage that defines a healthy target for everyone."],
      ["What is the difference between scale weight and healthy body composition?", "Scale weight measures total mass, while body composition separates components such as fat mass and lean mass. Two people with the same weight can have very different proportions of each."],
      ["How to account for heavy bones in healthy weight calculation?", "Bone mass contributes to body weight, but it is not usually practical to adjust a healthy-weight calculation specifically for 'heavy bones.' Body composition and waist measures are more useful for individual context."],
      ["What is a healthy weight range for athletes and bodybuilders?", "A standard BMI-based range may be less informative for highly muscular athletes. Performance, body-fat distribution, recovery, health markers and sport-specific requirements can provide better context."],
      ["How to calculate lean body mass vs ideal weight?", "Lean body mass is the weight of everything except body fat, while ideal-weight formulas estimate a reference weight from height. They answer different questions and should not be treated as interchangeable."],
      ["Does waist circumference matter more than healthy weight range?", "Neither measure is sufficient alone. Waist circumference can provide information about central fat distribution that BMI and scale weight miss, so using multiple measures gives a fuller picture."],
      ["What is the healthy waist-to-height ratio compared to weight range?", "Waist-to-height ratio relates waist size to height and focuses on central adiposity. It complements rather than replaces a BMI-based weight range."],
      ["What is the Devine formula for ideal body weight calculation?", "The Devine formula estimates ideal body weight from height using sex-specific constants. It was developed as a reference formula and should not be interpreted as a universal personal target."],
      ["What is the Robinson formula and how is it calculated?", "The Robinson formula is another height-based ideal-body-weight equation with sex-specific constants. Because it uses different assumptions from Devine and other formulas, its estimate can differ."],
      ["How does the Miller formula determine healthy body weight?", "The Miller formula is a height-based ideal-body-weight equation that uses different constants from Devine or Robinson. It produces an estimate rather than a clinically definitive healthy weight."],
      ["What is the Hamwi method for estimating ideal weight?", "The Hamwi method estimates reference body weight from height, traditionally using separate equations for men and women. It is a historical estimate and should not be confused with a diagnosis of healthy weight."],
      ["How does the Broca index calculate normal weight?", "The classic Broca index uses height in centimetres and subtracts a fixed amount to estimate a reference weight. It is a historical rule and is less informative than modern multi-measure assessment."],
      ["What formula does a standard BMI healthy weight calculator use?", "It uses BMI = weight in kilograms divided by height in metres squared. To calculate a weight range, the chosen BMI limits are multiplied by height squared."],
      ["How to calculate healthy weight range using the BMI equation manually?", "Convert height to metres, square the height, multiply by 18.5 for the lower boundary and 24.9 for the upper boundary, then compare your current weight with the resulting range."],
      ["Why do different ideal weight formulas give different results?", "Devine, Robinson, Miller, Hamwi and other formulas were developed from different datasets and assumptions. Because they estimate a reference weight rather than a biological optimum, their outputs naturally vary."],
      ["Which ideal body weight formula is most accurate for medication dosing?", "There is no single formula that is correct for every medication. Drug dosing may use actual, ideal, adjusted or another weight measure depending on the drug and clinical protocol."],
      ["What is the Peterson formula for healthy weight calculation?", "The Peterson formula is a more recent mathematical approach to estimating ideal body weight from height and BMI-related assumptions. Like other formulas, it is an estimate rather than a universal target."],
      ["How does South Asian BMI threshold change healthy weight calculations?", "Some South Asian and Asian-specific guidelines use lower BMI thresholds to identify increased metabolic risk. This does not mean every person should use one alternative range; the guideline and clinical context matter."],
      ["Why is the recommended healthy BMI lower in Asian consensus standards (18.5–22.9)?", "Some Asian consensus criteria identify increased metabolic risk at lower BMI values than conventional adult categories. A commonly cited Asian healthy range is 18.5–22.9, but thresholds vary by guideline and population."],
      ["How many pounds do I need to lose to reach a healthy weight range?", "Subtract the upper boundary of the BMI-based range from your current weight if you are above it. The resulting number is only a mathematical difference, not necessarily the amount you should lose."],
      ["How to set realistic weight loss target goals using a calculator?", "Use the calculator to understand your starting point, then choose a gradual target that fits your health, lifestyle and ability to maintain the change. Avoid treating the lowest number in a range as the goal by default."],
      ["What is a safe timeline to reach my calculated healthy weight range?", "A safe timeline depends on starting weight, health, medications and the size of the intended change. Gradual, sustainable loss is generally preferred to aggressive short-term restriction."],
      ["How many calories should I eat to achieve my healthy weight range?", "A healthy-weight calculator does not determine calorie needs. Calorie intake depends on age, body size, activity, goals and other factors, so a separate energy-needs estimate is required."],
      ["What calorie deficit is needed to move from overweight to healthy range?", "The needed deficit depends on your current weight, target, energy expenditure and time frame. A modest sustainable deficit is generally more practical than using a large fixed deficit for everyone."],
      ["How long does it take to get into a healthy weight range safely?", "There is no universal timeline. The answer depends on how far your current weight is from the chosen target and how consistently you can make sustainable changes without compromising nutrition or health."],
      ["Should my goal weight be at the top or middle of the healthy range?", "Neither is automatically correct. A practical goal can depend on body composition, health markers, preferences and how easily the weight can be maintained."],
      ["How to calculate calorie intake for maintaining healthy weight?", "Estimate maintenance calories from factors such as age, sex, body size and activity, then monitor weight trends over several weeks. Adjustments should be based on observed trends rather than a single day's intake."],
      ["What is a realistic weight gain goal if I am below the healthy range?", "The appropriate goal depends on why weight is low and whether nutrition, illness or another issue is involved. Gradual gain with adequate protein and nutrient-dense food may be appropriate, but unexplained low weight warrants medical evaluation."],
      ["How to maintain weight once reaching the calculated healthy range?", "Keep a consistent eating pattern, remain physically active, monitor trends rather than daily fluctuations, and adjust intake when a sustained change appears. Maintenance is an ongoing process rather than a final calculator result."],
      ["How often should I check my progress against the weight calculator?", "There is usually no need to recalculate the BMI range frequently because it is primarily determined by height. Track weight trends over time and reassess goals when your circumstances or health changes."],
      ["What diet plan works best to reach the recommended weight range?", "No single diet is best for everyone. A sustainable eating pattern built around nutrient-dense foods, appropriate portions and adequate protein can support weight management."],
      ["What health risks are associated with weighing above the healthy range?", "Higher body weight can be associated with increased risk of conditions such as hypertension, type 2 diabetes, sleep apnea and cardiovascular disease, but individual risk depends on more than weight alone."],
      ["What are the medical risks of weighing below the healthy weight range?", "Low body weight can be associated with inadequate nutrient intake, reduced muscle or bone mass and other health problems. The cause matters, especially when weight loss is unintentional."],
      ["Does reaching a healthy weight range reverse type 2 diabetes risk?", "Weight reduction can improve metabolic health and, for some people with type 2 diabetes, substantial sustained weight loss can improve disease control or remission likelihood. It does not guarantee reversal."],
      ["How does being in a healthy weight range affect blood pressure?", "Maintaining a healthy weight can support healthier blood pressure, but blood pressure is also influenced by sodium intake, activity, genetics, medications, sleep and other factors."],
      ["What is the correlation between healthy weight range and visceral fat?", "BMI and scale weight do not directly measure visceral fat. Higher central adiposity is associated with metabolic risk, which is why waist circumference can add useful information."],
      ["Can PCOS affect my ability to reach a healthy weight range?", "PCOS can affect appetite, insulin sensitivity, hormones and weight management for some people. Individual treatment and lifestyle planning should account for symptoms and medical care rather than relying on a weight calculator alone."],
      ["How does thyroid dysfunction impact healthy weight targets?", "Thyroid disorders can influence body weight and energy regulation. When thyroid function is abnormal, the underlying condition should be evaluated and treated rather than using a calculator to set a rigid target."],
      ["Is being slightly above the healthy weight range dangerous for health?", "A BMI just above 24.9 does not by itself establish that someone is unhealthy or in immediate danger. Risk changes across a continuum and should be considered with waist size, medical history and other factors."],
      ["Why do doctors use healthy weight range charts during checkups?", "Charts provide a quick screening reference for weight relative to height. Clinicians can then combine that information with symptoms, medical history, waist measurements, laboratory results and other assessments."],
      ["Does maintaining a healthy weight reduce cardiovascular disease risk?", "Maintaining a weight appropriate for your individual health can be part of cardiovascular risk reduction, alongside physical activity, blood pressure control, healthy eating, not smoking and management of cholesterol and diabetes."],
      ["How does weight range affect joint health and mobility?", "Higher body mass can increase mechanical load on weight-bearing joints, while adequate muscle strength supports mobility. Joint health depends on more than scale weight, including injuries, activity and muscle function."],
      ["Should elderly individuals aim for the upper limit of the healthy weight range?", "Not automatically. Older adults may have different nutritional, muscular and functional needs, so weight goals should be individualized rather than simply targeting the top or bottom of a BMI range."],
      ["What is the difference between BMI and healthy weight range?", "BMI is a ratio calculated from weight and height. A healthy-weight range reverses the BMI equation to show which weights correspond to a selected BMI interval for a particular height."],
      ["Is ideal body weight the same as healthy weight range?", "No. Ideal-body-weight formulas usually return one estimated reference weight, while a healthy-weight range provides a span of weights corresponding to selected BMI values."],
      ["Why is BMI sometimes inaccurate for assessing healthy weight?", "BMI uses only height and weight, so it cannot distinguish fat from muscle or show where fat is stored. It can therefore misclassify some muscular people and provide limited information for certain populations."],
      ["Can two people of the same height have different healthy weight goals?", "Yes. Two people with the same height can differ in muscle mass, body-fat distribution, age, health conditions and goals, so their practical targets may differ even if their BMI range is identical."],
      ["What should I do if my current weight is far outside the healthy range?", "Look at the direction and cause of the difference rather than trying to reach a number quickly. A healthcare professional can help assess nutrition, medical conditions, medications and an appropriate rate of change."],
      ["Is a weight calculator accurate for people with water retention or edema?", "A scale measures the extra fluid as weight, so a BMI-based calculator cannot distinguish edema from fat or muscle. Sudden unexplained swelling or weight gain should be medically assessed."],
      ["How does waist-to-hip ratio compare with healthy weight calculator results?", "Waist-to-hip ratio describes fat distribution, whereas a healthy-weight calculator describes weight relative to height. They measure different aspects of health and can be considered together."],
      ["Why does my scale show a different weight range than the online calculator?", "Different tools may use different BMI boundaries, unit conversions or formulas. Check the height, units and stated assumptions in each calculator before comparing results."],
      ["Which is better: body fat percentage calculator or healthy weight range calculator?", "They answer different questions. A healthy-weight calculator relates weight to height, while body-fat estimation focuses on body composition. Neither provides a complete assessment of health on its own."],
      ["What is the most reliable metric for overall health: BMI, weight range, or waist size?", "There is no single best metric for everyone. BMI and weight range provide screening information, while waist size adds information about central fat. Health history, fitness, blood pressure and laboratory measures may also matter."]
    ],
      ["Is the healthy weight range the same as ideal weight?", "No. A BMI-based range is different from formula-based ideal-weight estimates and should not be treated as a personal target."],
      ["How is healthy weight calculated from height?", "Weight is calculated from BMI multiplied by height squared, using the selected BMI boundaries."],
      ["Does age change the adult BMI range?", "The standard adult BMI categories are generally applied to adults, but BMI interpretation can require additional context."],
      ["Does muscle affect BMI?", "Yes. People with high muscle mass can have a higher BMI without having high body fat."],
      ["Can I use this range during pregnancy?", "Pregnancy requires specialized guidance; a standard adult BMI-based weight range should not be used as a pregnancy target."],
      ["What should I use with a healthy weight range?", "Consider complementary measures such as waist circumference, body composition and overall health context."],
      ["Can a healthy weight range diagnose health?", "No. It is a screening reference based on BMI and is not a diagnosis."],
    ],
    related: ["BMI Calculator", "Ideal Body Weight", "Body Fat Percentage", "Waist-to-Height Ratio"],
  },
  "body-surface-area": {
    title: "Body Surface Area Calculator Guide",
    quick: "Body surface area (BSA) estimates the total external surface area of the human body, usually in square metres. It is used in some clinical calculations and is different from BMI or body-fat percentage.",
    formula: "Most BSA equations use height and weight; the Mosteller formula is BSA = √[(height(cm) × weight(kg)) / 3600]",
    method: "The calculator combines height and body weight through an established BSA equation. Different equations can produce slightly different estimates, especially at extreme body sizes.",
    inputs: "Enter height and weight accurately. Metric inputs can be converted from imperial units before calculation. For clinical use, follow the equation and institutional protocol specified by the healthcare service.",
    meaning: "BSA provides an estimated surface area rather than a measure of body composition. In clinical contexts it can be used as part of certain dosing or physiological calculations, but the appropriate equation and clinical protocol matter.",
    example: "For a person who is 175 cm tall and weighs 70 kg, the Mosteller equation gives a BSA of about 1.85 m².",
    limits: "BSA is an estimate derived from body dimensions. It should not be substituted for a clinician's prescribed dosing method, and different clinical applications may specify different equations or protocols.",
    faqs: [
      ["What is body surface area?", "BSA is an estimate of the body's external surface area, commonly expressed in square metres."],
      ["What is BSA used for?", "It is used in some clinical and physiological calculations, including selected medication-dosing contexts."],
      ["How is BSA calculated?", "Several equations exist. The Mosteller equation uses height and weight and is convenient for routine calculation."],
      ["What is the Mosteller formula?", "BSA = square root of [(height in cm × weight in kg) ÷ 3600]."],
      ["Is BSA the same as BMI?", "No. BMI relates body weight to height, while BSA estimates external body surface area."],
      ["Does BSA change with weight?", "Yes. For a fixed height, increasing body weight generally increases estimated BSA."],
      ["Do all BSA formulas give the same result?", "No. Different equations use different assumptions and can produce slightly different values."],
      ["Can I use BSA to change a medication dose myself?", "No. Medication dosing should follow the prescribing clinician's instructions and the specific clinical protocol."],
    ],
    related: ["BMI Calculator", "Ideal Body Weight", "Healthy Weight Range", "Body Fat Percentage"],
  },
};

const SLUGS = new Set(Object.keys(DATA));

export default function Phase4SEOContent({ slug }) {
  const data = DATA[slug];
  if (!data) return null;
  const relatedLinks = data.related.map((name) => {
    const slugMap = {
      "Pace Calculator": "pace", "Calories Burned Calculator": "calories-burned", "Daily Calorie Needs": "daily-calorie-needs", "TDEE Calculator": "tdee",
      "Protein Calculator": "protein-intake", "Calorie Deficit Calculator": "calorie-deficit", "Meal Macro Calculator": "meal-macro", "Running Speed Calculator": "running-speed",
      "Cardio Fitness Level Calculator": "cardio-fitness-level", "Maximum Heart Rate Calculator": "maximum-heart-rate", "BMI Calculator": "bmi", "Ideal Body Weight": "ideal-body-weight",
      "Body Fat Percentage": "body-fat", "Waist-to-Height Ratio": "waist-to-height-ratio",
    };
    return slugMap[name] ? { name, slug: slugMap[name] } : null;
  }).filter(Boolean);
  return (
    <div className="space-y-6">
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Quick Answer</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{data.quick}</p></section>
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Formula or Method</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed font-mono">{data.formula}</p><p className="mt-3 text-sm sm:text-base text-muted-foreground leading-relaxed">{data.method}</p></section>
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Inputs Explained</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{data.inputs}</p></section>
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">What Your Result Means</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{data.meaning}</p></section>
      <section className="border border-border bg-card p-6"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Worked Example</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{data.example}</p></section>
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Accuracy and Limitations</h3><p className="text-sm sm:text-base text-muted-foreground leading-relaxed">{data.limits}</p></section>
      <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Frequently Asked Questions</h3><div className="space-y-5">{data.faqs.map(([q,a]) => <div key={q}><h4 className="font-bold mb-1">{q}</h4><p className="text-sm text-muted-foreground leading-7">{a}</p></div>)}</div></section>
      {relatedLinks.length > 0 && <section className="border border-border bg-card p-6"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Related Calculators</h3><div className="grid sm:grid-cols-2 gap-2">{relatedLinks.map((item) => <Link key={item.slug} to={`/${item.slug}-calculator`} className="border border-border px-4 py-3 text-sm font-bold hover:text-[var(--brand-lime)] hover:border-[var(--brand-lime)] transition-colors">{item.name}</Link>)}</div></section>}
      <section className="border border-border p-6 bg-card"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Important Health Note</h3><p className="text-sm text-muted-foreground leading-7">FitMe Pro calculators provide educational estimates. They do not diagnose disease, replace professional assessment, or guarantee a health or fitness outcome. For medical decisions, use the method and guidance provided by a qualified healthcare professional.</p></section>
    </div>
  );
}

export { SLUGS };
