import React from "react";
import { Link } from "react-router-dom";

const DATA = {
  "daily-calorie-needs": {
    title: "Daily Calorie Needs Calculator: How Many Calories Do You Need?",
    quick: "Daily calorie needs are an estimate of how much energy you need each day based on your age, sex, height, weight and activity level. FitMe Pro estimates resting energy first and then adjusts it for activity.",
    formula: "Mifflin-St Jeor BMR = 10W + 6.25H − 5A + S; daily needs ≈ BMR × activity factor.",
    inputs: "Age, sex, body weight, height and typical activity level. Use your usual activity rather than an unusually active or inactive week.",
    method: ["Convert height and weight to the required units.", "Estimate BMR with the Mifflin-St Jeor equation.", "Apply the selected activity factor to estimate daily energy expenditure.", "Use the result as a starting estimate and compare it with real-world weight and activity trends."],
    meaning: "Your result is an estimated daily calorie requirement, not a laboratory measurement. Around the estimated maintenance level, body weight may remain broadly stable over time, while consistently eating below or above it can support weight loss or gain.",
    example: "For a 30-year-old man weighing 70 kg at 175 cm with moderate activity, Mifflin-St Jeor gives a BMR of about 1,699 kcal/day; applying a 1.55 activity factor gives roughly 2,633 kcal/day.",
    limits: "Energy expenditure varies with individual physiology, activity, body composition and day-to-day movement. A calculator cannot directly observe every source of energy expenditure, so the result should be treated as a starting estimate.",
    links: [["BMR Calculator","/bmr-calculator"],["TDEE Calculator","/tdee-calculator"],["Calorie Deficit Calculator","/calorie-deficit-calculator"],["Macro Calculator","/macronutrient-calculator"],["Protein Calculator","/protein-calculator"]],
    faqs: [["How many calories do I need a day?","It depends on age, sex, height, weight and activity. The calculator estimates your personal daily requirement rather than using one number for everyone."],["Are daily calorie needs the same as TDEE?","In practical fitness planning, daily maintenance calories and TDEE are often used for the same estimated daily energy requirement."],["How accurate is a calorie calculator?","It provides an estimate. Your actual energy expenditure can differ, so use longer-term weight trends and activity to calibrate it."],["Should I eat exactly the number shown?","No. Treat it as a starting target and adjust gradually based on your goal and observed progress."],["Does exercise change calorie needs?","Yes. Activity contributes substantially to total daily energy expenditure."],["Can calorie needs change after losing weight?","Yes. A smaller body generally requires less energy, and activity may also change."],["Does age affect calorie needs?","Yes. Age is one of the inputs used by the BMR equation."],["Can I use this for medical nutrition decisions?","Not by itself. Medical nutrition needs can require individualized assessment by a qualified professional."]]
  },
  bmr: {
    title: "BMR Calculator: Calculate Your Basal Metabolic Rate",
    quick: "Basal Metabolic Rate (BMR) estimates the energy your body uses at rest to support essential functions such as breathing and circulation. It does not represent your total daily calorie requirement.",
    formula: "Mifflin-St Jeor: men BMR = 10W + 6.25H − 5A + 5; women BMR = 10W + 6.25H − 5A − 161.",
    inputs: "Age, sex, weight and height. The equation uses metric weight in kilograms and height in centimetres after unit conversion.",
    method: ["Enter age, sex, height and weight.", "Convert units if you use imperial measurements.", "Apply the Mifflin-St Jeor equation.", "Interpret BMR as a resting-energy estimate; multiply by an activity factor to estimate total daily needs."],
    meaning: "BMR is the foundation of many calorie calculators. It is lower than TDEE because TDEE also reflects physical activity, daily movement and the energy cost of processing food.",
    example: "A 30-year-old man at 70 kg and 175 cm has an estimated BMR of 10×70 + 6.25×175 − 5×30 + 5 = about 1,699 kcal/day.",
    limits: "BMR equations are population-based predictive models. They do not directly measure metabolic rate and can be less accurate for individuals whose physiology differs from the populations used to develop the equation.",
    links: [["TDEE Calculator","/tdee-calculator"],["Daily Calorie Needs Calculator","/daily-calorie-needs-calculator"],["Body Fat Calculator","/body-fat-calculator"],["Macro Calculator","/macronutrient-calculator"]],
    faqs: [["What does BMR stand for?","BMR stands for Basal Metabolic Rate, an estimate of energy expenditure at rest."],["Is BMR the same as maintenance calories?","No. Maintenance calories are generally estimated from total daily energy expenditure, which is higher than BMR for active people."],["Which BMR formula does FitMe Pro use?","FitMe Pro's core BMR calculator uses the Mifflin-St Jeor equation."],["Why is BMR different for men and women?","The Mifflin-St Jeor equation uses different constants to account for average differences represented in the original model."],["Does muscle affect BMR?","Body composition can influence resting energy expenditure, although a simple BMR equation cannot capture every individual difference."],["Can I increase my BMR?","Changes in body size and composition can affect resting energy expenditure, but there is no guaranteed way to raise a calculated BMR by a specific amount."],["Should I eat my BMR in calories?","BMR is not a recommended daily food target. Daily needs normally exceed resting requirements."],["How often should BMR be recalculated?","Recalculate when meaningful changes in body weight or other inputs occur rather than reacting to tiny day-to-day changes."]]
  },
  "ideal-body-weight": {
    title: "Ideal Body Weight Calculator: Devine Formula and What It Means",
    quick: "Ideal Body Weight (IBW) is a formula-based reference value, not a universal perfect weight. FitMe Pro uses the Devine equation and displays it as an estimate.",
    formula: "Devine: men = 50 + 2.3 × inches over 5 ft; women = 45.5 + 2.3 × inches over 5 ft.",
    inputs: "Height and sex. Height is converted to inches for the Devine equation.",
    method: ["Enter height and sex.", "Convert height to inches.", "Determine the inches above 5 feet.", "Apply the sex-specific Devine equation to estimate IBW."],
    meaning: "IBW was developed as a reference measure and is still encountered in clinical contexts, including some medication-dose calculations. It should not be treated as a personal aesthetic, athletic or medical target without context.",
    example: "For a 5 ft 9 in man, the Devine estimate is 50 + 2.3×9 = 70.7 kg. This is a formula result, not a statement that 70.7 kg is the only healthy weight.",
    limits: "A single height-based formula cannot account for muscle mass, body-fat distribution, age, ethnicity, health status or individual goals. Healthy weight is better considered as a range and in context.",
    links: [["Healthy Weight Range Calculator","/healthy-weight-range-calculator"],["BMI Calculator","/bmi-calculator"],["Body Fat Calculator","/body-fat-calculator"],["Target Weight Calculator","/target-weight-calculator"]],
    faqs: [["What is ideal body weight?","It is a formula-derived reference weight. The term does not mean there is one perfect weight for every person of a given height."],["What formula does this calculator use?","FitMe Pro uses the Devine ideal body weight formula."],["Is ideal body weight the same as healthy weight?","No. Healthy weight depends on more than a single height-based formula."],["Is IBW used in medicine?","The Devine formula is used as a reference in some clinical calculations, including certain medication-dosing contexts."],["Does IBW account for muscle?","No. A simple height-based formula cannot fully account for muscularity or body composition."],["Can athletes use IBW?","It may be a reference number, but performance goals should not be built around IBW alone."],["Why does another IBW calculator give a different answer?","Different calculators may use Devine, Robinson, Miller or other formulas."],["Should I make my goal weight equal to IBW?","Not automatically. Consider your BMI, body composition, health, goals and professional guidance where appropriate."]]
  },
  tdee: {
    title: "TDEE Calculator: Calculate Total Daily Energy Expenditure",
    quick: "TDEE (Total Daily Energy Expenditure) estimates the calories you burn across a typical day. It starts with BMR and adjusts it using an activity factor.",
    formula: "TDEE = BMR × activity multiplier. FitMe Pro's BMR foundation uses Mifflin-St Jeor.",
    inputs: "Age, sex, height, weight and activity level. The activity choice should represent your typical overall routine, not just exercise sessions.",
    method: ["Estimate BMR from age, sex, height and weight.", "Select the activity level that best matches your normal week.", "Multiply BMR by the activity factor.", "Use TDEE as an estimated maintenance baseline and monitor actual trends before making large adjustments."],
    meaning: "TDEE is commonly used as an estimated maintenance-calorie number. Eating around it may support weight stability, while sustained intake below or above it can support weight loss or gain depending on the size of the energy difference and individual response.",
    example: "For a 30-year-old man weighing 70 kg at 175 cm, BMR is about 1,699 kcal/day. With moderate activity at 1.55, estimated TDEE is about 2,633 kcal/day.",
    limits: "Activity multipliers simplify a complex process. Daily movement, exercise intensity, body composition, sleep, illness and other factors can change actual energy expenditure.",
    links: [["BMR Calculator","/bmr-calculator"],["Daily Calorie Needs Calculator","/daily-calorie-needs-calculator"],["Calorie Deficit Calculator","/calorie-deficit-calculator"],["Calorie Surplus Calculator","/calorie-surplus-calculator"],["Macro Calculator","/macronutrient-calculator"]],
    faqs: [["What does TDEE stand for?","TDEE stands for Total Daily Energy Expenditure."],["Is TDEE the same as maintenance calories?","They are commonly used interchangeably in practical diet planning, because TDEE estimates total daily energy expenditure and therefore provides a maintenance baseline."],["How is TDEE calculated?","Estimate BMR and multiply it by an activity factor."],["What activity factor should I choose?","Choose the level that best represents your normal total activity. Avoid choosing a higher level simply because you exercise occasionally."],["Can TDEE change over time?","Yes. Changes in body weight, activity, body composition and routine can change energy needs."],["How can I know whether my TDEE estimate is close?","Compare the estimate with consistent calorie intake and multi-week weight trends rather than a single day's scale reading."],["Should I eat below TDEE to lose weight?","A sustained calorie deficit is generally required for weight loss, but the size of the deficit should be individualized and reasonable."],["Can I use TDEE to gain muscle?","TDEE can provide a maintenance baseline from which a modest calorie surplus may be planned alongside resistance training and adequate nutrition."]]
  },
  "maintenance-calories": {
    title: "Maintenance Calories Calculator: Find Your Estimated Daily Calorie Needs",
    quick: "Maintenance calories are the estimated amount of energy you need to keep body weight broadly stable over time. FitMe Pro estimates maintenance from BMR and activity.",
    formula: "Maintenance calories ≈ BMR × activity factor, which is the same core relationship used for TDEE.",
    inputs: "Age, sex, height, weight and activity level.",
    method: ["Enter your current body measurements and age.", "Estimate BMR.", "Apply the activity factor that matches your typical routine.", "Use the result as a starting maintenance target and calibrate it using a multi-week weight trend."],
    meaning: "Maintenance is a planning estimate, not a fixed biological number. Your real energy needs can vary from day to day, so the useful goal is a reasonable average rather than perfect precision.",
    example: "If estimated BMR is 1,699 kcal/day and the selected activity multiplier is 1.55, estimated maintenance is about 2,633 kcal/day.",
    limits: "A calculator cannot directly measure your daily energy expenditure. Changes in movement, training, body weight, food intake and other factors can move your actual maintenance level.",
    links: [["TDEE Calculator","/tdee-calculator"],["BMR Calculator","/bmr-calculator"],["Daily Calorie Needs Calculator","/daily-calorie-needs-calculator"],["Calorie Deficit Calculator","/calorie-deficit-calculator"],["Macro Calculator","/macronutrient-calculator"]],
    faqs: [["What are maintenance calories?","They are the estimated average calories needed to maintain body weight over time at a given activity level."],["Are maintenance calories and TDEE the same?","For practical calorie planning, yes, they are commonly treated as the same estimated baseline."],["Why does my weight change even at maintenance?","Water, glycogen, food volume and normal day-to-day variation can change scale weight even when average energy balance is near maintenance."],["How long should I track to estimate maintenance?","A consistent multi-week trend is more informative than a few days."],["Do maintenance calories decrease after weight loss?","They can, because a smaller body often requires less energy and activity may also change."],["Can I use maintenance calories for muscle gain?","They provide a baseline. Muscle-gain plans often add a modest surplus while resistance training and protein intake are considered."],["Can I use maintenance calories for fat loss?","They provide the baseline from which a calorie deficit can be planned."],["Is the calculator exact?","No. It is a predictive estimate and should be calibrated against your real-world trend."]]
  }
};

export default function Phase1SEOContent({ slug }) {
  const data = DATA[slug];
  if (!data) return null;
  return <div className="space-y-8" data-testid={`phase1-seo-${slug}`}>
    <section>
      <h3 className="font-display text-2xl sm:text-3xl uppercase tracking-tight mb-3">{data.title}</h3>
      <p className="text-sm sm:text-base text-muted-foreground leading-8">{data.quick}</p>
    </section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Quick Answer</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.quick}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Formula</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.formula}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">How It Is Calculated</h3><ol className="list-decimal pl-6 space-y-2 text-sm sm:text-base text-muted-foreground leading-8">{data.method.map((x,i)=><li key={i}>{x}</li>)}</ol></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Inputs Explained</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.inputs}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">What Does My Result Mean?</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.meaning}</p></section>
    <section className="border border-border bg-card p-6"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Worked Example</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.example}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-3">Accuracy & Limitations</h3><p className="text-sm sm:text-base text-muted-foreground leading-8">{data.limits}</p></section>
    <section><h3 className="font-display text-xl sm:text-2xl uppercase tracking-tight mb-4">Frequently Asked Questions</h3><div className="space-y-5">{data.faqs.map(([q,a])=><div key={q}><h4 className="font-semibold mb-1">{q}</h4><p className="text-sm text-muted-foreground leading-7">{a}</p></div>)}</div></section>
    <section><h3 className="font-display text-xl uppercase tracking-tight mb-4">Related Calculators</h3><div className="grid sm:grid-cols-2 gap-2">{data.links.map(([label,to])=><Link key={to} to={to} className="border border-border px-4 py-3 text-sm font-bold hover:text-[var(--brand-lime)] hover:border-[var(--brand-lime)] transition-colors">{label}</Link>)}</div></section>
    <section className="border border-border p-6 bg-card"><h3 className="font-display text-xl uppercase tracking-tight mb-3">Important Health Note</h3><p className="text-sm text-muted-foreground leading-7">FitMe Pro calculators provide educational estimates. They do not diagnose disease or replace individualized medical or nutrition advice. If you have a medical condition, are pregnant, have a history of disordered eating, or need a therapeutic diet, consult a qualified healthcare professional.</p></section>
    <section><h3 className="font-display text-xl uppercase tracking-tight mb-3">Scientific Method Note</h3><p className="text-sm text-muted-foreground leading-7">The calorie calculators use established predictive equations rather than direct metabolic measurement. For general calorie planning, the result is best used as a starting point and refined using consistent real-world data.</p></section>
  </div>;
}
