const fs=require("fs");
const path=require("path");
const{pathToFileURL}=require("url");
const root=path.resolve(__dirname,"..");const build=path.join(root,"build");const indexPath=path.join(build,"index.html");const unitsPath=path.join(root,"src","lib","units.js");const tempDir=path.join(build,"__fitme_prerender_modules");const site=(process.env.SITE_URL||"https://fitme-pro.vercel.app").replace(/\/$/,"");
if(!fs.existsSync(indexPath))throw new Error("Build output not found");
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");const json=v=>JSON.stringify(v).replace(/</g,"\\u003c");
function write(route,html){const dir=path.join(build,route.replace(/^\//,"").replace(/\/$/,""));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,"index.html"),html,"utf8")}
function pageHtml(base,c,canonical){const schema={"@context":"https://schema.org","@type":"WebApplication",name:c.name,url:canonical,description:c.description,applicationCategory:"HealthApplication",operatingSystem:"Web",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}};const body=`<main><article style="max-width:900px;margin:0 auto;padding:40px 20px"><nav aria-label="Breadcrumb"><a href="/">FitMe Pro</a> / <span>${esc(c.category||"Calculator")}</span> / <span>${esc(c.name)}</span></nav><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p><section><h2>How this calculator works</h2><p>${esc(c.formula||"This tool uses the inputs shown on the calculator to produce an estimate.")}</p></section><section><h2>How to use it</h2><ol><li>Enter the required measurements or values.</li><li>Use consistent units and measurement technique.</li><li>Review the result as an estimate rather than a diagnosis.</li><li>For health or training decisions involving a medical condition, consult a qualified professional.</li></ol></section><section><h2>Understanding the result</h2><p>Calculator outputs depend on the equation, assumptions and quality of the inputs. Different methods can produce different estimates, so avoid treating a single value as a precise measurement of your biology or performance.</p></section><section><h2>Related FitMe Pro calculators</h2><ul><li><a href="/bmi-calculator">BMI Calculator</a></li><li><a href="/body-fat-calculator">Body Fat Calculator</a></li><li><a href="/bmr-calculator">BMR Calculator</a></li><li><a href="/tdee-calculator">TDEE Calculator</a></li></ul></section><p><a href="/">Explore all FitMe Pro calculators</a></p></article></main>`;return base.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(c.name)} · FitMe Pro</title>`).replace(/<meta name="description" content="[^"]*"\s*\/?>(\s*)/i,`<meta name="description" content="${esc(c.description)}" />$1`).replace(/<\/head>/i,`<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" /><link rel="canonical" href="${canonical}" /><meta property="og:type" content="website" /><meta property="og:title" content="${esc(c.name)}" /><meta property="og:description" content="${esc(c.description)}" /><meta property="og:url" content="${canonical}" /><script type="application/ld+json">${json(schema)}</script></head>`).replace(/<div id="root"><\/div>/i,`<div id="root">${body}</div>`)}
(async()=>{try{fs.mkdirSync(tempDir,{recursive:true});const base=fs.readFileSync(indexPath,"utf8");const modules=["specializedCalculators.js","newSpecializedCalculators.js"];const tempUnits=path.join(tempDir,"units.mjs");fs.writeFileSync(tempUnits,fs.readFileSync(unitsPath,"utf8"),"utf8");for(const filename of modules){const sourcePath=path.join(root,"src","lib",filename);const temp=path.join(tempDir,filename.replace(/\.js$/,"")+".mjs");const source=fs.readFileSync(sourcePath,"utf8").replace(/from\s+["']\.\/units["']/g,'from "./units.mjs"').replace(/from\s+["']\.\/newSpecializedCalculators["']/g,'from "./newSpecializedCalculators.mjs"');fs.writeFileSync(temp,source,"utf8")}let total=0;for(const filename of modules){const temp=path.join(tempDir,filename.replace(/\.js$/,"")+".mjs");const m=await import(`${pathToFileURL(temp).href}?v=${Date.now()}`);const calcs=m.SPECIALIZED_CALCULATORS||m.NEW_CALCULATORS||[];for(const c of calcs){const canonical=`${site}/${c.slug}`;write(`/${c.slug}`,pageHtml(base,c,canonical));total++}}console.log(`Prerendered ${total} specialized calculators (including new 60).`)}finally{try{fs.rmSync(tempDir,{recursive:true,force:true})}catch(_){}}})().catch(e=>{console.error("Specialized prerender failed:",e);process.exit(1)});
