const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const build=path.join(root,'build');const indexPath=path.join(build,'index.html');const site=(process.env.SITE_URL||'https://fitme-pro.vercel.app').replace(/\/$/,'');
if(!fs.existsSync(indexPath))throw new Error(`Build output not found: ${indexPath}`);
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function stripSeoMeta(html){return html.replace(/<meta\s+name=["']description["'][^>]*>\s*/gi,'').replace(/<meta\s+name=["']robots["'][^>]*>\s*/gi,'').replace(/<meta\s+property=["']og:(?:type|title|description|url|site_name)["'][^>]*>\s*/gi,'').replace(/<meta\s+name=["']twitter:[^"']+["'][^>]*>\s*/gi,'').replace(/<link\s+rel=["']canonical["'][^>]*>\s*/gi,'')}
function setMeta(html,title,description,canonical){html=stripSeoMeta(html).replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(title)}</title>`);return html.replace(/<\/head>/i,`<meta name="description" content="${esc(description)}" /><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" /><link rel="canonical" href="${canonical}" /><meta property="og:type" content="website" /><meta property="og:title" content="${esc(title)}" /><meta property="og:description" content="${esc(description)}" /><meta property="og:url" content="${canonical}" /></head>`)}
function writeRoute(route,html){const clean=route.replace(/^\//,'').replace(/\/$/,'');const dir=path.join(build,clean);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html,'utf8')}
function htmlFiles(dir){let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name==='static')continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...htmlFiles(p));else if(e.name==='index.html')out.push(p)}return out}
function main(){const base=fs.readFileSync(indexPath,'utf8');const staticPages=[['about','About FitMe Pro','Learn about FitMe Pro and its health and fitness calculators.'],['contact','Contact FitMe Pro','Contact FitMe Pro about calculator corrections, technical issues and feedback.'],['privacy-policy','Privacy Policy — FitMe Pro','Read the FitMe Pro privacy policy.'],['terms','Terms of Use — FitMe Pro','Read the FitMe Pro terms of use and calculator limitations.']];for(const [slug,title,description] of staticPages){const route=`/${slug}`;const html=setMeta(base,title,description,`${site}${route}`).replace(/<div id="root"><\/div>/i,`<div id="root"><main><article><h1>${esc(title)}</h1><p>${esc(description)}</p></article></main></div>`);writeRoute(route,html)}
const urls=new Set();for(const file of htmlFiles(build)){const rel=path.relative(build,file).replace(/\\/g,'/');const route=rel==='index.html'?'':`/${rel.replace(/\/index\.html$/,'')}`;if(route==='/bmi'||route==='/bmr'||route==='/tdee'||route==='/absi'||route==='/body-fat'||route==='/waist-height-ratio'||route==='/ponderal-index'||route==='/obesity-class'||route==='/weight-loss-goal'||route==='/weight-gain-goal'||route==='/navy-body-fat')continue;urls.add(site+(route||'/'))}
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[...urls].sort().map(u=>`  <url><loc>${esc(u)}</loc></url>`).join('\n')}\n</urlset>\n`;fs.writeFileSync(path.join(build,'sitemap.xml'),sitemap,'utf8');console.log(`Generated sitemap with ${urls.size} verified URLs.`)}
try{main()}catch(error){console.error(error);process.exit(1)}
