const fs=require("fs");
const path=require("path");
const{pathToFileURL}=require("url");
const root=path.resolve(__dirname,"..");const build=path.join(root,"build");const indexPath=path.join(build,"index.html");const unitsPath=path.join(root,"src","lib","units.js");const tempDir=path.join(build,"__fitme_prerender_modules");const site=(process.env.SITE_URL||"https://fitme-pro.vercel.app").replace(/\/$/,"");
if(!fs.existsSync(indexPath))throw new Error("Build output not found");
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");const json=v=>JSON.stringify(v).replace(/</g,"\\u003c");
function write(route,html){const dir=path.join(build,route.replace(/^\//,"").replace(/\/$/,""));fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,"index.html"),html,"utf8")}
function faqSet(c){
  if(c.slug==="bench-press-1rm-calculator")return[
    "What is a bench press 1RM?","It is the heaviest bench-press load a lifter can complete for one repetition under a defined technique standard. This calculator estimates it from a completed set.",
    "Which 1RM formula does FitMe Pro use?","It uses the Epley equation: 1RM = load × (1 + reps ÷ 30).",
    "How do Epley, Brzycki and Lombardi differ?","They use different mathematical relationships between load and repetitions, so the same set can produce different estimates.",
    "How should I use the percentage table?","Use the percentages as planning loads derived from the estimated 1RM and recalculate after changing your input set.",
    "Is an estimated 1RM the same as a tested maximum?","No. A prediction can differ because of technique, fatigue, equipment and individual performance.",
    "What repetition range is useful for 1RM estimates?","Prediction equations are generally more useful for moderate-repetition sets than very high-repetition sets.",
    "Can I use an estimated 1RM to choose a training load?","It can provide a starting point, but it is not a guarantee of what you can lift safely.",
    "Why do 1RM calculators disagree?","They may use different equations, repetition limits, rounding and assumptions."
  ].map(function(v,i,arr){return i%2===0?[v,arr[i+1]]:null}).filter(Boolean);
  if(c.slug==="vo2-max-calculator")return[
    ["What does the VO₂ max calculator estimate?","It estimates aerobic capacity from the distance covered in a 12-minute Cooper field test."],
    ["What is the Cooper 12-minute test?","You cover as much distance as practical in 12 minutes and enter that distance into the Cooper equation."],
    ["What formula is used?","VO₂ max ≈ (distance in metres − 504.9) ÷ 44.73."],
    ["What is the Rockport test?","The Rockport One-Mile Walk is another field protocol that estimates aerobic capacity from a one-mile walk and participant characteristics. It is not the formula implemented here."],
    ["Is field-test VO₂ max the same as a laboratory value?","No. Pacing, weather, terrain, motivation and measurement conditions can affect a field-test estimate."],
    ["How should I compare VO₂ max values?","Repeat the same protocol under similar conditions and use age- and sex-specific reference data from a defined population."]
  ];
  if(c.slug==="target-heart-rate-calculator"||c.slug==="aerobic-training-zone-calculator")return[
    ["What method is used for target heart rate?","The Karvonen heart-rate-reserve method uses estimated maximum heart rate and resting heart rate."],
    ["What is heart-rate reserve?","HRR = estimated maximum heart rate − resting heart rate; target HR = resting heart rate + HRR × intensity."],
    ["Why is resting heart rate needed?","It personalizes the heart-rate-reserve calculation instead of relying only on a percentage of maximum heart rate."],
    ["How should I measure resting heart rate?","Measure when rested, ideally after waking or after several quiet minutes, and repeat under similar conditions."],
    ["What are the five named zones?","Recovery, Fat-burning, Cardio, Threshold and Peak are the five descriptive training zones shown on this page."],
    ["Are these zones medical limits?","No. They are exercise-training estimates and individual heart-rate response can vary."]
  ];
  if(c.slug==="anaerobic-threshold-calculator")return[
    ["What does this threshold calculator estimate?","It estimates a threshold-oriented heart rate from maximum heart rate and a selected percentage."],
    ["What formula does it use?","Estimated threshold HR ≈ maximum heart rate × selected percentage, with 88% as the default."],
    ["Is this a measured lactate threshold?","No. A percentage-based estimate is not a laboratory measurement of lactate or ventilatory threshold."],
    ["Why does threshold heart rate differ between runners?","Threshold response depends on training status, physiology, test protocol and exercise conditions."],
    ["Can the result guide training?","It can be a planning reference, but perceived effort, performance and better-validated testing also matter."],
    ["Is the result medical advice?","No. It is an educational training estimate."]
  ];
  return[
    ["What does this calculator do?",c.name+" applies its stated method to the inputs shown on the page and returns an estimate."],
    ["How accurate is the result?","Accuracy depends on the method, measurement quality and individual variation. Treat equation-based outputs as estimates."],
    ["Why can another calculator differ?","Different equations, assumptions, reference populations and rounding rules can produce different results."],
    ["Can this result diagnose a medical condition?","No. FitMe Pro calculators are educational tools and are not a substitute for individualized medical assessment."]
  ];
}
function specialSections(c){
  if(c.slug==="bench-press-1rm-calculator"){var w=Number(c.inputFields[0].default),r=Number(c.inputFields[1].default),e=w*(1+Math.min(30,r)/30),b=r<37?w*36/(37-r):NaN,l=w*Math.pow(r,.1),ps=[100,95,90,85,80,75,70,65,60,55,50],rows=ps.map(function(p){return "<tr><td>"+p+"%</td><td>"+(e*p/100).toFixed(1)+" kg</td></tr>"}).join("");return "<section><h2>1RM equations compared</h2><p>FitMe Pro uses Epley. Brzycki and Lombardi are comparison equations. For the default example of "+w+" kg × "+r+" reps, Epley is "+e.toFixed(1)+" kg, Brzycki is "+b.toFixed(1)+" kg, and Lombardi is "+l.toFixed(1)+" kg.</p><table><thead><tr><th>Method</th><th>Estimated 1RM</th></tr></thead><tbody><tr><td>Epley</td><td>"+e.toFixed(1)+" kg</td></tr><tr><td>Brzycki</td><td>"+b.toFixed(1)+" kg</td></tr><tr><td>Lombardi</td><td>"+l.toFixed(1)+" kg</td></tr></tbody></table><h2>Rep-max percentage table</h2><p>Suggested loads are percentages of the Epley estimate for the example; they are not universal prescriptions.</p><table><thead><tr><th>Percentage</th><th>Suggested load</th></tr></thead><tbody>"+rows+"</tbody></table><h2>Worked example</h2><p>For 60 kg × 8 repetitions, Epley gives 60 × (1 + 8 ÷ 30) = 76.0 kg. A 70% planning load is about 53.2 kg.</p><p>An estimated 1RM is not a tested maximum. Technique, fatigue, range of motion and equipment can change actual performance.</p></section>";}
  if(c.slug==="vo2-max-calculator")return "<section><h2>Named field-test methods</h2><p>The calculator uses the Cooper 12-minute test. VO₂ max ≈ (distance in metres − 504.9) ÷ 44.73. Cooper published the field method in 1968. The Rockport One-Mile Walk, published in 1991, is another named field protocol using a one-mile walk plus participant characteristics; FitMe Pro does not use that equation.</p><table><thead><tr><th>Method</th><th>Primary input</th><th>Used here?</th></tr></thead><tbody><tr><td>Cooper (1968)</td><td>12-minute distance</td><td>Yes</td></tr><tr><td>Rockport (1991)</td><td>1-mile walk + participant data</td><td>No</td></tr></tbody></table><h2>Reference-range context</h2><p>VO₂ max norms vary by age, sex, training status and reference population. There is no single universal normal range. Compare against a published age- and sex-specific reference population and treat this field-test result as an estimate, not a laboratory measurement.</p><p>References: Cooper KH, A Means of Assessing Maximal Oxygen Intake (1968); Kline GM et al., Rockport One-Mile Walking Test (1991).</p></section>";
  if(c.slug==="target-heart-rate-calculator"||c.slug==="aerobic-training-zone-calculator")return "<section><h2>Karvonen heart-rate-reserve method</h2><p>Estimate HRmax as 220 − age. Then HRR = HRmax − resting heart rate and target HR = resting heart rate + HRR × intensity.</p><table><thead><tr><th>Zone</th><th>HRR intensity</th><th>Training description</th></tr></thead><tbody><tr><td>Recovery</td><td>50–60%</td><td>Very easy recovery work</td></tr><tr><td>Fat-burning</td><td>60–70%</td><td>Easy-to-moderate aerobic work</td></tr><tr><td>Cardio</td><td>70–80%</td><td>Moderate aerobic training</td></tr><tr><td>Threshold</td><td>80–90%</td><td>Hard sustained work</td></tr><tr><td>Peak</td><td>90–100%</td><td>Very hard efforts</td></tr></tbody></table><h2>How to measure resting heart rate</h2><p>Measure when rested, ideally after waking or after several quiet minutes. Avoid recent exercise and caffeine when practical, use the same device or pulse method, and repeat readings under similar conditions.</p><p>Example: age 30 and resting HR 60 gives estimated HRmax 190 and HRR 130. At 70% HRR, target HR is 60 + 130 × 0.70 = 151 bpm.</p></section>";
  if(c.slug==="anaerobic-threshold-calculator")return "<section><h2>Threshold estimate</h2><p>This calculator estimates threshold heart rate as maximum heart rate multiplied by a selected percentage, with 88% as the default. It is a simplified training estimate, not a direct lactate or ventilatory-threshold measurement.</p><table><thead><tr><th>Threshold intensity</th><th>Percentage of maximum heart rate</th><th>Use as a planning reference</th></tr></thead><tbody><tr><td>Lower estimate</td><td>85%</td><td>Moderate threshold-oriented work</td></tr><tr><td>Default estimate</td><td>88%</td><td>Default FitMe Pro calculation</td></tr><tr><td>Upper estimate</td><td>90%</td><td>Higher threshold-oriented work</td></tr></tbody></table><h2>Worked example</h2><p>With a maximum heart rate of 190 bpm and the default 88%, the result is 167 bpm after rounding.</p><h2>Limitations</h2><p>Threshold response varies with training status, physiology, protocol, fatigue, temperature and pacing. A laboratory or validated field protocol can provide a more individualized estimate.</p></section>";
  return "";
}
function pageHtml(base,c,canonical){
  const faqs=faqSet(c);
  const schema={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:c.name,url:canonical,description:c.description,applicationCategory:"HealthApplication",operatingSystem:"Web",isAccessibleForFree:true,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"FitMe Pro",item:site+"/"},{"@type":"ListItem",position:2,name:"Calculators",item:site+"/calculators"},{"@type":"ListItem",position:3,name:c.name,item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(function(f){return{"@type":"Question",name:f[0],acceptedAnswer:{"@type":"Answer",text:f[1]}}})}]};
  const faqHtml=faqs.map(function(f){return "<div><h3>"+esc(f[0])+"</h3><p>"+esc(f[1])+"</p></div>"}).join("");
  const body="<main><article style=\"max-width:900px;margin:0 auto;padding:40px 20px;font-family:Arial,sans-serif\"><nav aria-label=\"Breadcrumb\"><a href=\"/\">FitMe Pro</a> / <a href=\"/calculators\">Calculators</a> / <span>"+esc(c.name)+"</span></nav><h1>"+esc(c.name)+"</h1><p>"+esc(c.description)+"</p><section><h2>How this calculator works</h2><p>"+esc(c.formula||"This tool uses the inputs shown on the calculator to produce an estimate.")+"</p></section><section><h2>How to use it</h2><ol><li>Enter the required values.</li><li>Use consistent units and measurement technique.</li><li>Review the result as an estimate rather than a diagnosis.</li><li>For medical concerns, consult a qualified professional.</li></ol></section>"+specialSections(c)+"<section><h2>Accuracy and limitations</h2><p>"+esc(c.name)+" is an estimate for "+esc(c.category||"health and fitness")+" use. Results can shift with measurement technique, individual variation and the assumptions behind the formula.</p></section><section><h2>Frequently Asked Questions</h2>"+faqHtml+"</section><section><h2>Related FitMe Pro calculators</h2><ul><li><a href=\"/bmi-calculator\">BMI Calculator</a></li><li><a href=\"/body-fat-calculator\">Body Fat Calculator</a></li><li><a href=\"/bmr-calculator\">BMR Calculator</a></li><li><a href=\"/tdee-calculator\">TDEE Calculator</a></li></ul></section><p><a href=\"/\">Explore all FitMe Pro calculators</a></p></article></main>";
  return base.replace(/<title>[\s\S]*?<\/title>/i,"<title>"+esc(c.name)+" · FitMe Pro</title>").replace(/<meta name="description" content="[^"]*"\s*\/?>(\s*)/i,"<meta name=\"description\" content=\""+esc(c.description)+"\" />$1").replace(/<\/head>/i,"<meta name=\"robots\" content=\"index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1\" /><link rel=\"canonical\" href=\""+canonical+"\" /><meta property=\"og:type\" content=\"website\" /><meta property=\"og:title\" content=\""+esc(c.name)+"\" /><meta property=\"og:description\" content=\""+esc(c.description)+"\" /><meta property=\"og:url\" content=\""+canonical+"\" /><script type=\"application/ld+json\">"+json(schema)+"</script></head>").replace(/<div id="root"><\/div>/i,"<div id=\"root\">"+body+"</div>");
}
(async()=>{try{fs.mkdirSync(tempDir,{recursive:true});const base=fs.readFileSync(indexPath,"utf8");const tempUnits=path.join(tempDir,"units.mjs");const specializedTemp=path.join(tempDir,"specializedCalculators.mjs");const newSpecializedTemp=path.join(tempDir,"newSpecializedCalculators.mjs");const newDataTemp=path.join(tempDir,"newSpecializedCalculatorsData.mjs");const missingTemp=path.join(tempDir,"missingCalculators.mjs");fs.writeFileSync(tempUnits,fs.readFileSync(unitsPath,"utf8"),"utf8");const newDataSource=fs.readFileSync(path.join(root,"src","lib","newSpecializedCalculatorsData.js"),"utf8").replace(/from\s+["']\.\/units["']/g,'from "./units.mjs"');fs.writeFileSync(newDataTemp,newDataSource,"utf8");const newSource=fs.readFileSync(path.join(root,"src","lib","newSpecializedCalculators.js"),"utf8").replace(/from\s+["']\.\/newSpecializedCalculatorsData["']/g,'from "./newSpecializedCalculatorsData.mjs"');fs.writeFileSync(newSpecializedTemp,newSource,"utf8");const specializedSource=fs.readFileSync(path.join(root,"src","lib","specializedCalculators.js"),"utf8").replace(/from\s+["']\.\/units["']/g,'from "./units.mjs"').replace(/from\s+["']\.\/newSpecializedCalculators["']/g,'from "./newSpecializedCalculators.mjs"');fs.writeFileSync(specializedTemp,specializedSource,"utf8");fs.writeFileSync(missingTemp,fs.readFileSync(path.join(root,"src","lib","missingCalculators.js"),"utf8"),"utf8");const mod=await import(`${pathToFileURL(specializedTemp).href}?v=${Date.now()}`);const missing=await import(`${pathToFileURL(missingTemp).href}?v=${Date.now()}`);const calcs=[...(mod.SPECIALIZED_CALCULATORS||[]),...(missing.MISSING_CALCULATORS||[])];let total=0;for(const c of [...new Map(calcs.map(c=>[c.id,c])).values()]){const canonical=`${site}/${c.slug}`;write(`/${c.slug}`,pageHtml(base,c,canonical));total++}console.log(`Prerendered ${total} specialized and formerly missing calculators.`)}finally{try{fs.rmSync(tempDir,{recursive:true,force:true})}catch(_){}}})().catch(e=>{console.error("Specialized prerender failed:",e);process.exit(1)});
