const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const build=path.join(root,'build');const indexPath=path.join(build,'index.html');const site=(process.env.SITE_URL||'https://fitme-pro.vercel.app').replace(/\/$/,'');
if(!fs.existsSync(indexPath))throw new Error(`Build output not found: ${indexPath}`);
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function stripSeoMeta(html){return html.replace(/<meta\s+name=["']description["'][^>]*>\s*/gi,'').replace(/<meta\s+name=["']robots["'][^>]*>\s*/gi,'').replace(/<meta\s+property=["']og:(?:type|title|description|url|site_name)["'][^>]*>\s*/gi,'').replace(/<meta\s+name=["']twitter:[^"']+["'][^>]*>\s*/gi,'').replace(/<link\s+rel=["']canonical["'][^>]*>\s*/gi,'')}
function setMeta(html,title,description,canonical){html=stripSeoMeta(html).replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(title)}</title>`);return html.replace(/<\/head>/i,`<meta name="description" content="${esc(description)}" /><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1" /><link rel="canonical" href="${canonical}" /><meta property="og:type" content="website" /><meta property="og:title" content="${esc(title)}" /><meta property="og:description" content="${esc(description)}" /><meta property="og:url" content="${canonical}" /></head>`)}
function writeRoute(route,html){const clean=route.replace(/^\//,'').replace(/\/$/,'');const dir=path.join(build,clean);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html,'utf8')}
function htmlFiles(dir){let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name==='static')continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...htmlFiles(p));else if(e.name==='index.html')out.push(p)}return out}
function main(){const base=fs.readFileSync(indexPath,'utf8');const staticPages=[['about','About FitMe Pro','FitMe Pro provides free health, body composition, nutrition, running, strength and fitness calculators with transparent formulas and practical explanations.'],['contact','Contact FitMe Pro','Contact FitMe Pro about calculator corrections, technical issues, source updates and feedback.'],['privacy-policy','Privacy Policy — FitMe Pro','Read how FitMe Pro handles browser storage, optional profile sync, analytics and contact requests.'],['terms','Terms of Use — FitMe Pro','Read the FitMe Pro terms of use, educational purpose and calculator limitations.']];for(const [slug,title,description] of staticPages){const route=`/${slug}`;const extra=slug==='about'?'<h2>Our approach</h2><p>We combine accessible tools with clear formulas, measurement guidance, limitations and links to authoritative health information. Calculator results are estimates and should be interpreted with context.</p><h2>Explore the tools</h2><p><a href="/calculators">Browse all calculators</a> or start with the <a href="/bmi-calculator">BMI Calculator</a>, <a href="/bmr-calculator">BMR Calculator</a> or <a href="/tdee-calculator">TDEE Calculator</a>.</p>':slug==='contact'?'<h2>What to include</h2><p>For a correction, include the calculator URL, inputs used, expected result, observed result and relevant source. Do not send sensitive medical information.</p><h2>Evidence and standards</h2><p>Review our <a href="/journal/editorial-standards">editorial standards</a> and <a href="/journal/evidence-sources">evidence sources</a> before submitting feedback.</p>':`<h2>Important information</h2><p>${esc(description)} FitMe Pro is not a medical provider and does not replace individualized professional advice.</p><p><a href="/calculators">Browse calculators</a> · <a href="/contact">Contact FitMe Pro</a> · <a href="/journal">Read the journal</a></p>`;const html=setMeta(base,title,description,`${site}${route}`).replace(/<div id="root"><\/div>/i,`<div id="root"><main><article style="max-width:900px;margin:0 auto;padding:40px 20px"><nav><a href="/">FitMe Pro</a> / ${esc(title)}</nav><h1>${esc(title)}</h1><p>${esc(description)}</p>${extra}</article></main></div>`);writeRoute(route,html)}
const urls=new Set();for(const file of htmlFiles(build)){const rel=path.relative(build,file).replace(/\\/g,'/');const route=rel==='index.html'?'':`/${rel.replace(/\/index\.html$/,'')}`;if(route==='/bmi'||route==='/bmr'||route==='/tdee'||route==='/absi'||route==='/body-fat'||route==='/waist-height-ratio'||route==='/ponderal-index'||route==='/obesity-class'||route==='/weight-loss-goal'||route==='/weight-gain-goal'||route==='/weight-loss-goal-calculator'||route==='/weight-gain-goal-calculator'||route==='/navy-body-fat')continue;urls.add(site+(route||'/'))}
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${[...urls].sort().map(u=>`  <url><loc>${esc(u)}</loc></url>`).join('\n')}\n</urlset>\n`;fs.writeFileSync(path.join(build,'sitemap.xml'),sitemap,'utf8');console.log(`Generated sitemap with ${urls.size} verified URLs.`)}
try{main()}catch(error){console.error(error);process.exit(1)}
