export const PHASE3_BATCH3_EXTRA_SECTIONS = {
"long-term-nutritional-requirements-after-weight-loss-surgery":[
["How procedure type changes the nutrition conversation","A sleeve and a gastric bypass do not create the same nutritional situation. The amount of stomach tissue that remains, the route food takes through the intestine and the patient's ability to tolerate foods can all influence the long-term plan. That is why a supplement list copied from a friend or an online forum may be inappropriate even when the operations sound similar. Patients should know the name of their procedure and keep the operative and follow-up records available. At appointments, ask which laboratory tests are being monitored, what symptoms should trigger an earlier visit and whether supplements need adjustment as recovery progresses. Nutrition after surgery is a continuing clinical process rather than a short diet phase."],
["Making follow-up information easy to use","A simple personal record can make long-term bariatric care more effective. Note the prescribed supplements, approximate timing, foods that are consistently tolerated, fluid intake problems and any new symptoms. Bring laboratory results and medication lists to visits rather than trying to remember everything. If a supplement causes nausea or constipation, report that instead of quietly stopping it for months. The care team can often change the formulation or schedule when there is a legitimate problem. This approach also helps distinguish a temporary food-tolerance issue from a persistent nutritional concern. Good records do not replace clinical care; they make the clinical conversation more precise."]
],
"understanding-the-biomarkers-of-healthy-metabolism":[
["How trends are more useful than isolated values","Metabolic markers are easier to understand when they are viewed as trends under comparable conditions. A single blood-pressure reading can differ from another because of timing or stress, and laboratory values can vary for reasons unrelated to a recent meal. When a clinician is monitoring a risk factor, use the requested testing schedule rather than creating a private testing routine that generates anxiety. Record the date, relevant medication changes and major health changes alongside results. A trend can show whether an intervention is associated with improvement, stability or worsening, but it still requires clinical interpretation. The aim is useful information, not perfect numbers every day."],
["Separating screening from diagnosis","Screening measurements help identify people who may need closer assessment. Diagnosis requires appropriate clinical criteria and, in many cases, repeated or confirmatory testing. This distinction matters because online calculators often present a numerical output that looks more definitive than it really is. A BMI result can prompt a discussion about weight-related risk; it cannot diagnose diabetes. A waist measurement can signal abdominal-risk concerns; it cannot measure visceral fat directly. Treat each tool according to what it actually measures. That keeps the interpretation evidence-based and prevents a convenient number from becoming an unsupported medical label."]
],
"managing-pcos-symptoms-through-strategic-weight-management":[
["Choosing outcomes that are meaningful in PCOS","Progress in PCOS should be defined by the problem being treated. Someone may care most about more regular cycles, improved glucose markers, better fitness, reduced sleep problems or fertility planning. Another person may not need weight loss at all but may benefit from activity and nutritional improvements. Recording the relevant outcome prevents the scale from becoming the sole measure of success. If menstrual changes, androgen-related symptoms or fertility concerns persist, medical review remains important even when weight is changing. A plan is stronger when it has more than one success measure and does not promise that every symptom will respond to the same intervention."],
["Avoiding the cycle of restriction and rebound","Very restrictive diets can make eating feel like a short-term treatment rather than a sustainable routine. For someone with PCOS, a better structure is often one that can be repeated across workdays, weekends and social meals. Build meals around foods the person can afford and enjoy, then adjust portions or meal composition when clinically appropriate. If repeated dieting has produced guilt, binge episodes or loss of control, behavioral support may be more useful than another restrictive menu. PCOS management should improve health without turning food into a constant test of willpower."]
],
"the-ultimate-pre-bariatric-surgery-diet-guide":[
["Shopping and preparation before the diet starts","Preparation is easier when the prescribed foods are available before the first day. Ask the bariatric team for the approved food list, portion instructions and product requirements. Check whether protein drinks, broths or other products need a particular nutritional profile. Plan meals around the work schedule and arrange support for situations in which food is normally purchased spontaneously. This is especially useful for patients who have diabetes or other conditions requiring medication coordination. Preparation should reduce improvisation, not encourage the patient to make the diet more restrictive than prescribed. If the plan is unclear, contact the dietitian before surgery rather than relying on a social-media version."],
["How to judge whether the plan is working","The success of a pre-operative diet is not measured only by how hungry the patient can tolerate being. The team may be looking for appropriate preparation, adequate hydration and readiness for the next stage. If the patient experiences repeated vomiting, severe weakness, dizziness, dehydration or uncontrolled glucose, the plan needs clinical review. A person should report difficulty rather than assuming that suffering means the diet is more effective. The purpose of the pre-operative period is to arrive at surgery safely and prepared for the post-operative pathway. That makes communication with the clinical team more important than achieving the lowest possible scale reading."]
],
"thyroid-health-and-weight-management-hypothyroidism-explained":[
["What a realistic thyroid-weight plan looks like","After thyroid treatment is established, weight management can use the same practical tools used for many other adults: consistent meals, appropriate portions, physical activity, sleep and a multi-week trend. The difference is that thyroid status is a medical variable that should be monitored separately. If thyroid tests are stable but weight changes unexpectedly, investigate other contributors instead of assuming the dose needs to rise. Conversely, if thyroid symptoms return, speak with the clinician rather than trying to solve them through a harsher diet. Keeping thyroid care and weight-management decisions in their proper roles prevents both undertreatment and unnecessary restriction."],
["Why 'slow metabolism' is an incomplete explanation","People often describe difficulty losing weight as a slow metabolism, but body weight reflects energy intake, expenditure, body composition, activity, appetite and many environmental and biological factors. Hypothyroidism can contribute to the picture when it is present, but correcting it does not make all other factors disappear. This distinction is useful because it directs attention to what can actually be measured and changed. A clinician can assess thyroid function, while the patient can monitor food patterns, activity and weight trends. Neither side needs to be reduced to a single explanation."]
],
"how-bariatric-surgery-can-change-hunger-and-satiety-signals":[
["Meal satisfaction is more than stomach size","Feeling satisfied after surgery can depend on portion size, protein content, food texture, eating speed and physiological signals. A very small meal that is eaten quickly may feel different from a small meal eaten slowly and attentively. Patients should therefore learn the eating pattern recommended by their program rather than focusing only on the maximum amount the stomach can hold. If meals consistently leave the person weak, dizzy or unable to meet nutrition goals, the solution is not to suppress appetite further. The dietitian can review meal composition and timing and make adjustments that protect nutrition."],
["Why appetite should be tracked without judgment","A brief appetite log can record hunger before meals, fullness afterward, sleep quality and unusual stress. The purpose is to identify patterns, not to grade the patient. Hunger may increase after poor sleep or long gaps between meals and may decrease during illness. If the pattern changes dramatically without an obvious reason, share the record with the bariatric team. This can be more informative than relying on memory. The long-term objective is a workable relationship with hunger and fullness, not the permanent absence of appetite."]
],
"am-i-a-candidate-for-bariatric-surgery-eligibility-criteria-explained":[
["Medical readiness is different from numerical eligibility","Even when a person appears to meet a BMI-based screening criterion, the team still has to assess whether the operation is appropriate now. Medical readiness can include control of major conditions, medication review, nutritional status and an understanding of post-operative care. Some issues may need treatment before surgery, while others may change the choice of procedure. This is not an arbitrary extra hurdle. Surgery has risks, and the team needs enough information to balance those risks against expected benefit. A good evaluation should leave the patient understanding why surgery is being considered and what alternatives remain."],
["Insurance criteria and clinical criteria are not identical","A patient may encounter two separate questions: whether surgery is medically appropriate and whether a particular insurer or health system will pay for it. Those questions can have different rules. A clinic can help with documentation, but the patient should verify coverage directly with the payer. Ask which requirements are clinical, which are administrative and which are specific to the chosen facility. Keeping these categories separate prevents a denial of coverage from being mistaken for a medical judgment that surgery is inappropriate, or vice versa."]
]
};