import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";

export default function CarbohydrateCalculator() {
  const [calories, setCalories] = useState(2000);
  const [percent, setPercent] = useState(45);
  const grams = useMemo(() => ((Number(calories) || 0) * (Number(percent) || 0)) / 100 / 4, [calories, percent]);
  return <main className="mx-auto max-w-4xl px-4 py-10"><h1 className="text-4xl font-bold">Carbohydrate Calculator</h1><p className="mt-3 text-lg">Calculate daily carbohydrate grams from your calorie target and carbohydrate percentage.</p><section className="mt-8 rounded-2xl border p-6 grid gap-5 sm:grid-cols-2"><label>Daily calories<input className="mt-2 w-full rounded-lg border p-3" type="number" value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>Carbohydrate %<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" max="100" value={percent} onChange={e=>setPercent(e.target.value)}/></label><div className="sm:col-span-2 rounded-xl border p-5"><b>Carbohydrates</b><div className="text-3xl font-semibold">{grams.toFixed(0)} g/day</div></div></section><article className="prose mt-10 max-w-none"><h2>How the Carbohydrate Calculator Works</h2><p>It converts the chosen percentage of your daily calorie target into an estimated carbohydrate amount in grams.</p><h2>Carbohydrate Formula</h2><p>Carbohydrate grams = daily calories × carbohydrate percentage ÷ 100 ÷ 4. Carbohydrate provides about 4 calories per gram.</p><h2>Using Your Result</h2><p>Use your calorie target from the <Link to="/tdee-calculator">TDEE Calculator</Link> and combine carbohydrate planning with your protein and fat targets.</p><h2>Accuracy and Limitations</h2><p>This is a nutrition-planning estimate. Individual needs vary with activity, training, health, goals and dietary preferences.</p><h2>Frequently Asked Questions</h2><h3>How many calories are in a gram of carbohydrate?</h3><p>Carbohydrate is conventionally counted as about 4 calories per gram.</p><h3>Is this a medical prescription?</h3><p>No. People with medical conditions should follow advice from a qualified healthcare professional.</p></article></main>;
}
