import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";

export default function FatIntakeCalculator() {
  const [calories, setCalories] = useState(2000);
  const [percent, setPercent] = useState(30);
  const grams = useMemo(() => ((Number(calories) || 0) * (Number(percent) || 0)) / 100 / 9, [calories, percent]);
  return <main className="mx-auto max-w-4xl px-4 py-10"><h1 className="text-4xl font-bold">Fat Intake Calculator</h1><p className="mt-3 text-lg">Estimate daily dietary fat intake from your calorie target and fat percentage.</p><section className="mt-8 rounded-2xl border p-6 grid gap-5 sm:grid-cols-2"><label>Daily calories<input className="mt-2 w-full rounded-lg border p-3" type="number" value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>Fat %<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" max="100" value={percent} onChange={e=>setPercent(e.target.value)}/></label><div className="sm:col-span-2 rounded-xl border p-5"><b>Fat intake</b><div className="text-3xl font-semibold">{grams.toFixed(0)} g/day</div></div></section><article className="prose mt-10 max-w-none"><h2>How the Fat Intake Calculator Works</h2><p>Enter a calorie target and the percentage of calories you want to allocate to fat. The result converts those calories into grams.</p><h2>Fat Intake Formula</h2><p>Fat grams = daily calories × fat percentage ÷ 100 ÷ 9. Dietary fat is conventionally counted as about 9 calories per gram.</p><h2>Planning Fat Intake</h2><p>Use the <Link to="/tdee-calculator">TDEE Calculator</Link> to estimate energy needs, then balance fat with protein and carbohydrate intake.</p><h2>Accuracy and Limitations</h2><p>The result is a planning estimate, not individualized medical nutrition advice. Food choices and individual needs still matter.</p><h2>Frequently Asked Questions</h2><h3>How many calories are in a gram of fat?</h3><p>Fat is conventionally counted as about 9 calories per gram.</p><h3>Should everyone use the same fat percentage?</h3><p>No. Appropriate intake depends on dietary pattern, goals, energy needs and individual circumstances.</p></article></main>;
}
