import React,{useEffect}from"react";import{Link,useParams}from"react-router-dom";import{getJournalArticle}from"@/lib/journalContent";import{getExpandedJournalArticle}from"@/lib/journalExpansion";import{SEO_COMPETITOR_ARTICLES}from"@/lib/seoCompetitorArticles";import{SEO_COMPETITOR_ARTICLES_2}from"@/lib/seoCompetitorArticles2";import{getLongFormJournalArticle}from"@/lib/journalLongform";
const SITE_URL="https://fitme-pro.vercel.app";
const SECTION_IMAGES={
  nutrition:["https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80"],
  fitness:["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80"],
  "weight-loss":["https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1554284126-aa88f22d8b74?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80"],
  "body-composition":["https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=1200&q=80"],
  wellness:["https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1474418397713-7ede21d49118?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80"],
  "health-education":["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80"]
};
function meta(n,c,p=false){const s=p?`meta[property="${n}"]`:`meta[name="${n}"]`;let e=document.querySelector(s);if(!e){e=document.createElement("meta");e.setAttribute(p?"property":"name",n);document.head.appendChild(e)}e.content=c}
function canonical(u){let l=document.querySelector('link[rel="canonical"]');if(!l){l=document.createElement("link");l.rel="canonical";document.head.appendChild(l)}l.href=u}
function sectionImage(article,heading,index){const pool=SECTION_IMAGES[article.categorySlug]||SECTION_IMAGES.wellness;const h=heading.toLowerCase();const keywordIndex=h.includes("sleep")?0:h.includes("water")||h.includes("hydration")?1:h.includes("exercise")||h.includes("training")||h.includes("activity")?2:h.includes("food")||h.includes("diet")||h.includes("nutrition")?3:index;return pool[keywordIndex%pool.length]}
function renderSection(article,[heading,text],index){return <section key={`${heading}-${index}`} className="mb-14"><h2 className="mb-5 text-2xl font-bold sm:text-3xl">{heading}</h2><img src={sectionImage(article,heading,index)} alt={`${heading} — FitMe Pro Journal`} loading={index<2?"eager":"lazy"} className="mb-6 h-56 w-full rounded-2xl object-cover sm:h-72"/><div className="space-y-5">{text.split(/(?<=[.!?])\s+(?=[A-Z])/).map((p,j)=><p key={j} className="text-base leading-8 text-muted-foreground">{p}</p>)}</div></section>}
export default function JournalArticle(){const{slug}=useParams();const source=getJournalArticle(slug)||getExpandedJournalArticle(slug)||SEO_COMPETITOR_ARTICLES.find(a=>a.slug===slug)||SEO_COMPETITOR_ARTICLES_2.find(a=>a.slug===slug);const article=getLongFormJournalArticle(source);useEffect(()=>{if(!article)return;const url=`${SITE_URL}/journal/${article.categorySlug}/${article.slug}`;document.title=`${article.title} | FitMe Pro Journal`;meta("description",article.description);meta("keywords",article.keywords);meta("robots","index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1");meta("og:title",article.title,true);meta("og:description",article.description,true);meta("og:type","article",true);meta("og:url",url,true);canonical(url);const id="fitme-journal-article-schema";document.getElementById(id)?.remove();const s=document.createElement("script");s.id=id;s.type="application/ld+json";s.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:"2026-09-04",dateModified:"2026-09-04",mainEntityOfPage:{"@type":"WebPage","@id":url},author:{"@type":"Organization",name:"FitMe Pro"},publisher:{"@type":"Organization",name:"FitMe Pro",url:SITE_URL},articleSection:article.category,keywords:article.keywords,isAccessibleForFree:true});document.head.appendChild(s);return()=>document.getElementById(id)?.remove()},[article]);if(!article)return <main className="mx-auto max-w-4xl px-4 py-20"><h1 className="text-3xl font-bold">Article not found</h1><Link className="mt-4 inline-block text-primary" to="/journal">Back to Journal →</Link></main>;
const sections=article.sections||[];const internalLinks=<section className="mb-14 rounded-3xl border border-primary/20 bg-primary/5 p-7"><h2 className="text-2xl font-bold">Explore related FitMe Pro tools</h2><p className="mt-3 leading-7 text-muted-foreground">Use these internal tools alongside the guide to explore your own numbers and continue learning about related topics.</p><div className="mt-5 flex flex-wrap gap-3"><Link className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground" to="/calculators">All calculators</Link><Link className="rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold" to="/bmi-calculator">BMI Calculator</Link><Link className="rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold" to="/tdee-calculator">TDEE Calculator</Link><Link className="rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold" to="/protein-calculator">Protein Calculator</Link></div></section>;
return <main className="min-h-screen px-4 py-10 sm:px-6 lg:px-10"><article className="mx-auto max-w-4xl"><Link to={`/journal/${article.categorySlug}`} className="text-sm font-medium text-primary">← {article.category} Journal</Link><header className="mt-7 border-b border-white/10 pb-10"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">{article.category} · {article.readTime}</p><h1 className="mt-4 text-4xl font-bold leading-[1.15] sm:text-5xl">{article.title}</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">{article.description}</p><p className="mt-5 text-sm text-muted-foreground">Updated September 4, 2026 · FitMe Pro Journal</p></header><div className="mt-12">{sections.map((section,index)=><React.Fragment key={`${section[0]}-${index}`}>{renderSection(article,section,index)}{index===2&&internalLinks}</React.Fragment>)}</div><section className="mt-12 border-t border-white/10 pt-8"><h2 className="mb-5 text-xl font-semibold">Sources & further reading</h2><ul className="space-y-3">{article.sources.map(s=><li key={s.url}><a className="text-sm text-primary hover:underline" href={s.url} target="_blank" rel="noopener noreferrer">{s.label} ↗</a></li>)}</ul><p className="mt-6 text-xs leading-6 text-muted-foreground">FitMe Pro uses authoritative public-health guidance as a reference. Our wording is original and is not copied from source publications or competitor websites.</p></section></article></main>}
