import React,{useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {ArrowLeft,ArrowRight,Copy} from "@phosphor-icons/react";
import MeasurementPanel from "@/components/MeasurementPanel";
import {useMeasurements} from "@/context/MeasurementContext";
import {NEW_CALCULATORS} from "@/lib/newSpecializedCalculators";
import {toMetric} from "@/lib/units";
import {toast} from "sonner";

const getNewCalculator=id=>NEW_CALCULATORS.find(c=>c.id===id)||null;
const COLORS={"Body Composition":"#059669","Weight, BMI & Weight Goals":"#059669","Calories & Metabolism":"#059669","Nutrition & Macronutrients":"#059669","Running, Cardio & Endurance":"#059669","Strength & Gym Performance":"#059669","Heart Rate & Cardiovascular Metrics":"#059669"};
const ready=(c,s)=>{const m=toMetric(s);return c.requires.every(r=>r==="sex"?(m.sex==="male"||m.sex==="female"):r==="activity"?!!m.activity:r==="age"?m.age>0:r==="height"?m.heightCm>0:r==="weight"?m.weightKg>0:r==="waist"?m.waistCm>0:r==="neck"?m.neckCm>0:true)};
const Field=({f,v,set})=><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">{f.label}{f.unit?<span className="ml-1 text-[var(--brand-lime)]">/ {f.unit}</span>:null}</span><input type="number" inputMode="decimal" min={f.min} max={f.max} step={f.step||"any"} value={v??""} onChange={e=>set(e.target.value)} placeholder={f.default!=null?String(f.default):""} className="w-full border-b-2 border-border bg-transparent px-0 py-2 text-lg font-mono-data focus:border-[var(--brand-lime)] focus:outline-none"/></label>;
function extra(c,v,s){if(c.id==="pace-calculator"){const d=+v.distance,t=+v.minutes*60+(+v.seconds||0);if(!(d>0&&t>0))return null;const p=t/d;return{value:`${Math.floor(p/60)}:${String(Math.round(p%60)).padStart(2,"0")}`,unit:"min/km",category:`${(d/(t/3600)).toFixed(1)} km/h`,interpretation:"Calculated from distance and elapsed time."}}if(c.id==="one-rep-max-calculator"){const w=+(v.liftWeight||v.load),r=+v.reps;if(!(w>0&&r>0&&r<=30))return null;return{value:(w*(1+r/30)).toFixed(1),unit:"kg estimated 1RM",category:"Epley equation",interpretation:"Estimated from weight and repetitions."}}return c.computeExtra?c.computeExtra({...v,state:s}):null}
const humanize=k=>({height:"height",weight:"body weight",age:"age",sex:"sex",activity:"activity level",waist:"waist circumference",neck:"neck circumference"}[k]||k.replace(/([A-Z])/g," $1").toLowerCase());
const faqFor=c=>[
 {q:`What does the ${c.name} measure?`,a:`The ${c.name} provides a calculated estimate based on the inputs shown on this page. It is designed for education, planning and tracking rather than diagnosis.`},
 {q:`How does the ${c.name} work?`,a:`The calculator applies the formula shown below to your entered values. The method is displayed so you can understand what the result represents.`},
 {q:`What information do I need?`,a:c.requires.length?`The shared profile inputs are ${c.requires.map(humanize).join(", ")}. Some versions of this calculator also ask for additional values on this page.`:`This calculator does not require your body profile. Enter the additional values shown in the Calculator Inputs section.`},
 {q:`Is this result medically accurate?`,a:`No calculator can replace an appropriate measurement or professional assessment. Estimates can differ because equations depend on population data, measurement technique and individual characteristics.`},
 {q:`Can I use the result to track progress?`,a:`Yes. For many fitness metrics, consistent measurements over time can be more useful than a single reading. Try to use similar conditions and methods each time.`},
 {q:`Why might another calculator give a different answer?`,a:`Different calculators can use different equations, assumptions, units, reference populations and rounding rules. Check the stated formula and inputs when comparing results.`},
 {q:`Is FitMe Pro free to use?`,a:`Yes. FitMe Pro provides free health and fitness calculators for educational and planning purposes.`},
 {q:`Should I make health decisions from this number alone?`,a:`No. Treat the result as one piece of information. For symptoms, medical conditions, medication-related questions or concerning results, use advice from a qualified healthcare professional.`}
];
function upsertMeta(name,content,property=false){const key=property?"property":"name";let el=document.head.querySelector(`meta[${key}="${name}"]`);if(!el){el=document.createElement("meta");el.setAttribute(key,name);document.head.appendChild(el)}el.setAttribute("content",content)}
function setJsonLd(c,faqs){document.getElementById("fitme-new-calculator-jsonld")?.remove();const script=document.createElement("script");script.id="fitme-new-calculator-jsonld";script.type="application/ld+json";script.textContent=JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:c.name,url:`${location.origin}/${c.slug}`,applicationCategory:"HealthApplication",operatingSystem:"Web",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"FitMe Pro",item:`${location.origin}/`},{"@type":"ListItem",position:2,name:c.category,item:`${location.origin}/`},{"@type":"ListItem",position:3,name:c.name,item:`${location.origin}/${c.slug}`} ]},{"@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))}]});document.head.appendChild(script)}
export default function NewCalculatorPage({calculatorId}){
 const {state,calculatorInputs,updateCalculatorInputs}=useMeasurements();const c=getNewCalculator(calculatorId);const fs=c?.inputFields||[];const saved=calculatorInputs?.[calculatorId]||{};const [v,setV]=useState({});
 useEffect(()=>{if(!c)return;setV(Object.fromEntries(fs.map(f=>[f.name,saved[f.name]??f.default??""])))},[calculatorId,c]);
 const r=useMemo(()=>{if(!c)return null;try{return c.computeExtra?extra(c,v,state):ready(c,state)?c.compute(state):null}catch{return null}},[c,v,state]);
 const faqs=useMemo(()=>c?faqFor(c):[],[c]);
 useEffect(()=>{if(!c)return;const title=`${c.name} — Free Online Calculator | FitMe Pro`;const description=`${c.description} Learn the formula, understand your result and use the free ${c.name.toLowerCase()} from FitMe Pro.`;document.title=title;upsertMeta("description",description);upsertMeta("og:title",title,true);upsertMeta("og:description",description,true);upsertMeta("og:type","website",true);const l=document.querySelector('link[rel="canonical"]')||document.head.appendChild(Object.assign(document.createElement("link"),{rel:"canonical"}));l.href=`${location.origin}/${c.slug}`;setJsonLd(c,faqs);return()=>document.getElementById("fitme-new-calculator-jsonld")?.remove()},[c,faqs]);
 if(!c)return <main className="p-10"><h1>Calculator not found</h1><Link to="/">Back to dashboard</Link></main>;
 const set=(k,x)=>{setV(q=>({...q,[k]:x}));updateCalculatorInputs(calculatorId,{[k]:x})};const copy=async()=>{try{await navigator.clipboard.writeText(`${c.name}: ${r?.value??"—"} ${r?.unit??""}`);toast.success("Copied")}catch{toast.error("Copy failed")}};const related=NEW_CALCULATORS.filter(x=>x.category===c.category&&x.id!==c.id).slice(0,6);const inputText=c.requires.length?`This calculator uses ${c.requires.map(humanize).join(", ")} from your shared Body Profile. Keeping those measurements consistent makes repeated calculations easier to compare.`:`This calculator uses dedicated inputs because its result cannot be derived from the shared Body Profile alone. Enter the requested values below.`;
 return <div className="flex min-h-screen flex-col lg:flex-row"><MeasurementPanel/><main className="min-w-0 flex-1"><section className="border-b border-border"><div className="max-w-4xl px-6 py-8 sm:px-10"><Link to="/" className="mb-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.25em] text-muted-foreground"><ArrowLeft size={14}/> Back to dashboard</Link><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.3em]" style={{color:COLORS[c.category]||"#059669"}}>{c.category}</div><h1 className="font-display text-3xl uppercase leading-tight tracking-tighter sm:text-4xl lg:text-5xl">{c.name}</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground sm:text-base">{c.description}</p></div></section>
 <section className="px-6 py-8 sm:px-10"><div className="max-w-4xl border border-border bg-card p-6 sm:p-8"><div className="mb-5 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.25em] text-muted-foreground">Your Result</span><button onClick={copy} aria-label="Copy result" className="border border-border px-3 py-1.5 text-[10px] font-bold uppercase"><Copy size={12}/></button></div>{r?<><div className="font-mono-data text-4xl font-black text-[var(--brand-lime)] sm:text-6xl">{r.value}<span className="ml-2 text-lg font-normal text-muted-foreground">{r.unit}</span></div>{r.category&&<div className="mt-3 text-sm font-bold uppercase tracking-[0.2em]">{r.category}</div>}<p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">{r.interpretation}</p></>:<p className="text-sm text-muted-foreground">Enter the required values below to see your result.</p>}</div>
 {fs.length>0&&<div className="mt-8 max-w-4xl border border-border bg-card p-6 sm:p-8"><div className="mb-5 text-[10px] font-bold uppercase tracking-[0.25em] text-[var(--brand-lime)]">Calculator Inputs</div><p className="mb-5 text-xs leading-6 text-muted-foreground">{inputText} Your entries are saved on this device for this calculator only.</p><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{fs.map(f=><Field key={f.name} f={f} v={v[f.name]} set={x=>set(f.name,x)}/>)}</div></div>}{fs.length===0&&<div className="mt-8 max-w-4xl border border-border bg-card p-5 text-xs leading-6 text-muted-foreground">{inputText} Update your profile on the dashboard and the result will recalculate automatically.</div>}
 <article className="mt-10 max-w-4xl border-t border-border pt-10 space-y-8"><section><div className="mb-2 text-[10px] font-bold uppercase tracking-[0.25em] text-[var(--brand-lime)]">Complete Guide</div><h2 className="font-display text-3xl uppercase tracking-tighter">What Is the {c.name}?</h2><p className="mt-4 text-sm leading-8 text-muted-foreground">The {c.name.toLowerCase()} is a calculation tool for estimating or converting a specific health, nutrition or fitness metric. FitMe Pro shows the underlying method instead of presenting the number as a diagnosis. This helps you understand what the result means, which inputs influence it and where the calculation has limits.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">How It Works</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">The calculator applies the stated formula to the values you provide. {c.description} The result is an estimate when the underlying method is an equation or prediction model. If your inputs change, the result updates so you can compare different scenarios.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Formula</h2><pre className="mt-3 overflow-x-auto whitespace-pre-wrap border border-border bg-card p-4 font-mono-data text-sm">{c.formula}</pre></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Inputs and Measurement Tips</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">{inputText} Use the same units and measurement technique when tracking changes. Avoid entering guessed values when a more reliable measurement is available. Small differences in body measurements, timing or rounding can change calculated results.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">How to Interpret Your Result</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">A calculated value should be interpreted in the context of the method used, the quality of the inputs and your individual circumstances. A single number rarely describes overall health or fitness. For progress tracking, consistent conditions and trends are generally more informative than reacting to one result.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Accuracy and Limitations</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">Equations are simplified models. They may not account for every individual characteristic, measurement error, training status, medical condition or environmental factor. Two legitimate equations can also produce different estimates. FitMe Pro therefore presents these calculators as educational tools rather than diagnostic instruments.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Common Mistakes to Avoid</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-muted-foreground"><li>Mixing metric and imperial units without converting them correctly.</li><li>Using inconsistent measurement locations or conditions between readings.</li><li>Treating an estimate as a directly measured value.</li><li>Comparing results from different formulas without checking their assumptions.</li><li>Using a health or fitness estimate as a diagnosis.</li></ul></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Using the Result for Planning</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">You can use this result as one input when setting training, nutrition or tracking goals. Recheck the inputs periodically and focus on sustainable changes. If the calculation relates to blood pressure, heart rate, body composition, nutrition or another health measure, consider the broader context rather than optimizing around one number.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Why Trends Matter</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">Body weight, exercise performance, heart rate and other measurements naturally fluctuate. Recording results under similar conditions can reveal a more useful trend than a single reading. When a value changes unexpectedly, first check the measurement conditions and formula before drawing conclusions.</p></section>
 <section><h2 className="font-display text-2xl uppercase tracking-tight">Important Health Note</h2><p className="mt-3 text-sm leading-8 text-muted-foreground">FitMe Pro calculators are for educational and informational use. They do not diagnose disease, prescribe treatment or replace professional assessment. If you have symptoms, a medical condition, take medication that affects the metric, or receive a concerning result, discuss it with a qualified healthcare professional.</p></section></article>
 <section className="mt-10 max-w-4xl"><h2 className="font-display text-2xl uppercase tracking-tight mb-5">Frequently Asked Questions</h2><div className="divide-y divide-border border-y border-border">{faqs.map((f,i)=><details key={i} className="group py-4"><summary className="cursor-pointer list-none pr-6 text-sm font-bold leading-6"><span>{f.q}</span></summary><p className="mt-3 text-sm leading-7 text-muted-foreground">{f.a}</p></details>)}</div></section>
 {related.length>0&&<section className="mt-10 max-w-4xl border border-border bg-card p-6"><div className="mb-4 text-[10px] font-bold uppercase tracking-[0.25em] text-muted-foreground">Related Calculators</div><div className="grid gap-2 sm:grid-cols-2">{related.map(x=><Link key={x.id} to={`/${x.slug}`} className="flex items-center justify-between border border-border px-4 py-3 text-sm font-bold hover:border-[var(--brand-lime)] hover:text-[var(--brand-lime)]">{x.name}<ArrowRight size={14}/></Link>)}</div></section>}
 </section></main></div>;
}
