import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";

export default function ProteinCalculator() {
  const [weight, setWeight] = useState(70);
  const [factor, setFactor] = useState(1.6);
  const grams = useMemo(() => Math.max(0, Number(weight) || 0) * Math.max(0, Number(factor) || 0), [weight, factor]);
  return <main className="mx-auto max-w-4xl px-4 py-10"><h1 className="text-4xl font-bold">Protein Calculator</h1><p className="mt-3 text-lg">Estimate a daily protein target based on body weight and your activity or fitness goal.</p>
    <section className="mt-8 rounded-2xl border p-6"><div className="grid gap-5 sm:grid-cols-2"><label>Body weight (kg)<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label>Protein factor (g/kg)<input className="mt-2 w-full rounded-lg border p-3" type="number" min="0" step="0.1" value={factor} onChange={e=>setFactor(e.target.value)}/></label></div><div className="mt-6 rounded-xl border p-5"><span>Estimated daily protein</span><div className="text-3xl font-bold">{grams.toFixed(0)} g/day</div></div></section>
    <article className="prose mt-10 max-w-none"><h2>How the Protein Calculator Works</h2><p>The calculator multiplies body weight in kilograms by a selected protein factor in grams per kilogram. A factor can be adjusted to reflect different activity levels and goals.</p><h2>Protein Formula</h2><p>Daily protein target = body weight (kg) × protein target (g/kg/day).</p><h2>Choosing a Protein Target</h2><p>Protein requirements differ between individuals. Training volume, age, energy intake, body composition, and health status can all affect an appropriate target. Use the result as a planning estimate rather than an absolute requirement.</p><h2>Related FitMe Pro Calculators</h2><p>Pair this estimate with the <Link to="/calorie-calculator">Calorie Calculator</Link> and <Link to="/macro-calculator">Macro Calculator</Link> for a broader nutrition plan.</p><h2>Frequently Asked Questions</h2><h3>Is more protein always better?</h3><p>No. More is not automatically better, and overall diet quality and adequate energy intake also matter.</p><h3>Can protein targets change?</h3><p>Yes. Recalculate when body weight, training, goals, or other relevant circumstances change.</p><h3>Is this medical advice?</h3><p>No. People with kidney disease or other medical or dietary concerns should seek individualized professional advice.</p></article></main>;
}
