export const JOURNAL_CATEGORIES = [
  { slug: "nutrition", name: "Nutrition", description: "Evidence-informed guidance on healthy eating, calories, protein, carbohydrates, fats, fibre and hydration for people worldwide." },
  { slug: "fitness", name: "Fitness", description: "Movement, strength, cardio, recovery and practical ways to build a more active life." },
  { slug: "weight-loss", name: "Weight Management", description: "Sustainable approaches to energy balance, healthy weight management, habits and progress." },
  { slug: "body-composition", name: "Body Composition", description: "Plain-language guides to BMI, body fat, waist measures, lean mass and other body metrics." },
  { slug: "wellness", name: "Wellness", description: "Sleep, hydration, stress, recovery and everyday behaviours that support health and wellbeing." },
  { slug: "health-education", name: "Health Education", description: "Accessible explanations of common health topics, prevention and when professional advice matters." },
];

const WHO_DIET = "https://www.who.int/news-room/fact-sheets/detail/healthy-diet";
const WHO_PHYSICAL = "https://www.who.int/news-room/fact-sheets/detail/physical-activity";
const WHO_OBESITY = "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight";
const WHO_FAO = "https://www.who.int/publications/i/item/9789240101876";
const WHO_SALT = "https://www.who.int/news-room/fact-sheets/detail/salt-reduction";
const WHO_SUGAR = "https://www.who.int/publications/i/item/9789241549028";

const src = (extra = []) => [{ label: "WHO — Healthy diet", url: WHO_DIET }, ...extra];

export const JOURNAL_ARTICLES = [
  {
    slug: "what-is-a-healthy-diet", category: "Nutrition", categorySlug: "nutrition",
    title: "What Is a Healthy Diet? A Practical Guide to Balanced Eating",
    description: "Learn the global principles of a healthy diet, including variety, balance, moderation, fibre, fruits and vegetables, fats, sugars and sodium.",
    readTime: "8 min read", date: "September 3, 2026", featured: true,
    keywords: "healthy diet, balanced diet, healthy eating, nutrition guide, healthy foods",
    sources: src([{ label: "WHO & FAO — What are healthy diets?", url: WHO_FAO }]),
    sections: [
      ["What does a healthy diet mean?", "A healthy diet is not one fixed menu. It can differ with age, activity level, culture, food availability, preferences and individual needs. WHO describes adequacy, balance, moderation and diversity as core principles. Food safety is also essential. The goal is a dietary pattern that supplies needed nutrients and energy while limiting excesses that can harm health."],
      ["Build meals around nutritious foods", "A practical foundation is a variety of minimally processed or unprocessed foods. Depending on personal dietary choices, this can include vegetables, fruits, legumes, whole grains, nuts and seeds, and nutritious sources of protein. Processed food is not automatically unhealthy; the overall pattern, portion, frequency and nutritional quality matter."],
      ["Carbohydrates, protein and fats all have a role", "Carbohydrates, protein and fats are macronutrients with different functions. Healthy eating is not about eliminating an entire macronutrient group. WHO guidance emphasizes nutrient-dense carbohydrate sources, appropriate protein and a shift toward healthier unsaturated fats while limiting saturated and industrial trans fats."],
      ["Fruits, vegetables and fibre", "WHO recommends at least 400 grams of fruits and vegetables per day for adults and children older than 10 years. It also recommends at least 25 grams of naturally occurring dietary fibre per day for people older than 10. These foods can be distributed across meals and snacks."],
      ["Sugar, salt and unhealthy fats", "A healthy pattern does not require perfection. It does require moderation. WHO recommends limiting free sugars, sodium and unhealthy fats, while choosing more nutritious foods more often. Read labels when available and consider the whole dietary pattern rather than judging one food in isolation."],
      ["A global approach", "Healthy diets can look different around the world. Local foods, cultural traditions, affordability and dietary preferences should be respected while keeping the same basic principles. FitMe Pro uses public-health guidance to explain nutrition concepts without prescribing a single menu for everyone."],
    ],
  },
  {
    slug: "how-many-calories-should-i-eat", category: "Nutrition", categorySlug: "nutrition",
    title: "How Many Calories Should I Eat Per Day?",
    description: "Understand energy needs, BMR, TDEE and calorie balance without turning nutrition into a one-number rule.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "calories per day, daily calorie needs, calorie intake, TDEE, BMR",
    sources: src([{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }]),
    sections: [
      ["There is no single calorie target for everyone", "Daily energy needs vary with factors including age, sex, body size, growth, activity and other individual characteristics. Two people of the same height can have different energy requirements. A calorie target seen online should therefore be treated as an estimate, not a universal prescription."],
      ["BMR and TDEE explained", "Basal metabolic rate, or BMR, estimates energy used to support basic physiological functions at rest. Total daily energy expenditure, or TDEE, is broader and includes resting needs plus activity and other energy expenditure. FitMe Pro calculators estimate these values using mathematical models rather than directly measuring metabolism."],
      ["Calories and body weight", "Energy intake and expenditure influence body weight, but real-world weight management is more complex than a simple daily equation. Appetite, food environment, sleep, activity, medications, health conditions and other factors can affect outcomes. WHO describes overweight and obesity as complex conditions with biological, behavioural, environmental and social influences."],
      ["If your goal is weight loss", "A calorie deficit means consuming less energy than the body uses over time. The appropriate approach depends on the person and goal. Very aggressive restriction can make it difficult to meet nutrient needs and may be difficult to sustain. A practical plan emphasizes nutritious foods, activity, sleep and realistic monitoring."],
      ["Use calorie estimates with context", "Calories are one part of nutrition. WHO recommends a varied diet based on nutritious foods and advises limiting free sugars, unhealthy fats and excess sodium. Use FitMe Pro calorie tools as educational estimates rather than as a substitute for individualized medical or dietetic advice."],
    ],
  },
  {
    slug: "how-much-protein-do-i-need", category: "Nutrition", categorySlug: "nutrition",
    title: "How Much Protein Do You Need Per Day?",
    description: "Understand protein, dietary needs and the factors that can change how much protein a person may need.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "protein per day, protein intake, daily protein needs, protein nutrition",
    sources: src(),
    sections: [
      ["What protein does in the body", "Protein provides amino acids needed for growth, maintenance and repair of body tissues. Protein also contributes to enzymes, hormones and other biological functions. Dietary protein comes from many foods, including legumes, grains, nuts, seeds, dairy foods, eggs, fish and meat, depending on dietary preferences."],
      ["Protein needs are individual", "Protein requirements vary across the life course and can be influenced by body size, age, activity, pregnancy, illness and other circumstances. A single high protein target should not automatically be applied to everyone. People with kidney disease or other medical conditions may need individualized guidance."],
      ["Quality and variety matter", "A varied diet can provide protein from multiple sources. Plant proteins can be combined across the overall diet rather than requiring a particular combination at every meal. Choosing nutritious protein sources also brings other nutrients, such as fibre and minerals, depending on the food."],
      ["Protein and exercise", "People who train regularly often pay close attention to protein because exercise increases the importance of recovery and tissue maintenance. Protein is useful, but muscle development also depends on progressive training, sufficient energy, sleep and overall dietary quality."],
      ["Using a protein calculator", "A calculator can provide a starting estimate based on selected assumptions. It cannot account for every health condition or dietary need. Use the FitMe Pro Protein Calculator as an educational tool and seek professional advice when medical or specialized nutrition needs are involved."],
    ],
  },
  {
    slug: "carbohydrates-explained", category: "Nutrition", categorySlug: "nutrition",
    title: "Carbohydrates Explained: Types, Food Sources and Healthy Choices",
    description: "Learn what carbohydrates are, where they come from and how to choose carbohydrate-rich foods within a balanced diet.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "carbohydrates, carbs, complex carbohydrates, healthy carbs, fibre",
    sources: src(),
    sections: [
      ["What are carbohydrates?", "Carbohydrates are a major source of energy and are found in foods such as grains, fruits, vegetables, legumes and many packaged foods. They include sugars, starches and dietary fibre. Calling all carbohydrates either good or bad oversimplifies nutrition."],
      ["Choose nutrient-rich sources", "WHO guidance emphasizes carbohydrate sources such as whole grains, vegetables, fruits and pulses. These foods can provide fibre, vitamins, minerals and other useful components in addition to carbohydrate. The best choices depend on the overall dietary pattern and personal needs."],
      ["Simple versus complex is not the whole story", "Carbohydrate chemistry can be described in different ways, but food quality is more useful than relying only on labels such as simple or complex. A whole fruit and a sugary drink both contain sugars, yet their overall nutritional characteristics are very different."],
      ["Carbohydrates and exercise", "Carbohydrate availability can matter for physical activity because carbohydrate is an important fuel source. The amount and timing that works best varies with activity type, duration and individual tolerance. A balanced eating pattern remains important outside training sessions."],
      ["The practical takeaway", "You do not need to remove carbohydrates to eat healthily. Focus on variety, fibre-rich foods and minimally processed sources more often, while limiting foods and drinks high in free sugars."],
    ],
  },
  {
    slug: "dietary-fats-explained", category: "Nutrition", categorySlug: "nutrition",
    title: "Dietary Fats Explained: Saturated, Unsaturated and Trans Fats",
    description: "Learn why dietary fat matters, how different types of fat differ and what global guidance says about healthier choices.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "dietary fat, saturated fat, unsaturated fat, trans fat, healthy fats",
    sources: src(),
    sections: [
      ["Why dietary fat matters", "Dietary fat is a concentrated source of energy and helps the body absorb fat-soluble vitamins. Fat is not something that needs to be eliminated from a healthy diet. The type and overall amount of fat matter."],
      ["Unsaturated fats", "Unsaturated fats are commonly found in foods such as nuts, seeds, fish, avocados and some plant oils. WHO recommends shifting fat intake away from saturated and trans fats toward unsaturated fats as part of a healthy dietary pattern."],
      ["Saturated fats", "Saturated fats occur naturally in many foods. WHO recommends limiting saturated fat intake and replacing some sources with unsaturated fats where appropriate. The practical focus is on improving the overall pattern rather than declaring a single food completely forbidden."],
      ["Industrial trans fats", "Industrial trans fats are particularly undesirable. WHO recommends eliminating industrially produced trans fats from the food supply. Check nutrition labels where available and prefer foods prepared with healthier fat sources."],
      ["Fat and calories", "Because fat is energy-dense, portions can matter when managing total energy intake. This does not mean low-fat automatically means healthy: a food can be low in fat but high in free sugars or sodium. Consider the complete nutritional profile."],
    ],
  },
  {
    slug: "dietary-fibre-guide", category: "Nutrition", categorySlug: "nutrition",
    title: "Dietary Fibre: What It Is, Why It Matters and How to Get More",
    description: "A practical guide to dietary fibre, fibre-rich foods and how to build a varied diet that supports adequate fibre intake.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "dietary fibre, fiber, high fibre foods, fibre benefits, whole grains",
    sources: src(),
    sections: [
      ["What is dietary fibre?", "Dietary fibre refers to components of plant foods that are not digested and absorbed in the same way as many other nutrients. Different fibres have different properties. Fibre is naturally present in foods such as whole grains, vegetables, fruits, legumes, nuts and seeds."],
      ["How much fibre?", "WHO's 2026 healthy-diet fact sheet recommends at least 25 grams of naturally occurring dietary fibre per day for people older than 10 years. Individual needs and tolerance can differ, so a gradual approach may be useful when increasing intake."],
      ["Where to find fibre", "Beans, lentils, chickpeas, whole grains, vegetables, fruits, nuts and seeds can all contribute. Choosing a range of these foods also increases dietary diversity, which is one of the core principles of a healthy diet."],
      ["Increase fibre gradually", "A sudden large increase can cause digestive discomfort for some people. Increase fibre progressively and maintain adequate fluid intake. If persistent digestive symptoms occur, discuss them with a healthcare professional rather than assuming fibre is always the cause."],
      ["Fibre is part of a bigger pattern", "There is no single miracle food. Fibre-rich foods are useful because they contribute to an overall nutrient-dense dietary pattern. Aim for variety rather than relying on one supplement or one food."],
    ],
  },
  {
    slug: "how-much-sugar-should-you-eat", category: "Nutrition", categorySlug: "nutrition",
    title: "How Much Sugar Should You Eat? Understanding Free Sugars",
    description: "Learn the difference between free sugars and sugars naturally present in whole foods, and understand WHO guidance.",
    readTime: "7 min read", date: "September 3, 2026", keywords: "sugar intake, free sugars, added sugar, daily sugar, WHO sugar guidelines",
    sources: [{ label: "WHO — Guideline: sugars intake", url: WHO_SUGAR }, { label: "WHO — Healthy diet", url: WHO_DIET }],
    sections: [
      ["What are free sugars?", "Free sugars include sugars added to foods and drinks by manufacturers, cooks or consumers, as well as sugars naturally present in honey, syrups, fruit juices and fruit juice concentrates. They are different from sugars naturally contained within intact whole fruits and many other whole foods."],
      ["WHO guidance", "WHO recommends limiting free sugars to less than 10% of total energy intake, with a further reduction to below 5% suggested for additional health benefits. These percentages are population-level guidance and should not be interpreted as a personalized prescription for every person."],
      ["Where free sugars often appear", "Sweetened drinks, confectionery, desserts and many packaged foods can contribute substantial amounts. Nutrition labels can help identify sugar content, although labels and definitions vary between countries."],
      ["Practical ways to reduce excess", "Choose water or unsweetened drinks more often, compare labels, reduce the frequency of very sweet foods and use whole fruit more often than sugary snacks or drinks. The aim is a sustainable dietary pattern rather than perfection."],
      ["A note about fruit", "Whole fruits provide nutrients and fibre in addition to naturally occurring sugars. WHO's free-sugar guidance should not be misunderstood as saying that whole fruit is equivalent to a sugar-sweetened beverage."],
    ],
  },
  {
    slug: "salt-and-sodium-explained", category: "Nutrition", categorySlug: "nutrition",
    title: "Salt and Sodium: How Much Is Too Much?",
    description: "Understand sodium, salt, common sources and practical ways to reduce excess sodium in a global diet.",
    readTime: "7 min read", date: "September 3, 2026", keywords: "salt intake, sodium, daily sodium, salt reduction, WHO sodium",
    sources: [{ label: "WHO — Healthy diet", url: WHO_DIET }, { label: "WHO — Salt reduction", url: WHO_SALT }],
    sections: [
      ["Sodium and salt are related", "Sodium is a mineral found in salt and many foods. Table salt is sodium chloride. Because the terms are sometimes used interchangeably, check whether a nutrition label reports sodium or salt before comparing products."],
      ["WHO recommendation", "WHO recommends limiting sodium intake to less than 2 grams per day for adults, equivalent to less than 5 grams of salt per day. The recommendation is intended to help reduce population-level health risks, particularly high blood pressure."],
      ["Where sodium comes from", "Sodium can come from salt added during cooking or at the table, but processed and packaged foods can also be important sources. The main sources vary between countries and diets."],
      ["Simple ways to reduce excess", "Taste food before automatically adding salt, use herbs and spices for flavour, compare packaged-food labels and choose lower-sodium options when practical. Gradual changes can make a lower-sodium pattern easier to maintain."],
      ["Not all sodium needs are identical", "Certain medical situations can require individualized dietary advice. If a healthcare professional has given you a specific sodium target, follow that advice rather than a general online recommendation."],
    ],
  },
  {
    slug: "how-to-read-a-nutrition-label", category: "Nutrition", categorySlug: "nutrition",
    title: "How to Read a Nutrition Label: A Simple Step-by-Step Guide",
    description: "Learn how to compare serving sizes, calories, protein, fibre, sugars, fats and sodium when choosing packaged foods.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "nutrition label, food label, serving size, calories, nutrition facts",
    sources: src(),
    sections: [
      ["Start with the serving information", "Before comparing numbers, check the serving size and how many servings the package contains. A package may contain multiple servings, so the listed values may not represent everything you eat."],
      ["Look at energy and macronutrients", "Calories, protein, carbohydrate and fat can help you understand a food's energy and macronutrient contribution. Use these numbers in the context of your overall diet rather than judging a food by one nutrient."],
      ["Check fibre and sugars", "Fibre can help you identify more fibre-rich choices. Sugar information requires context because labels may combine sugars naturally present in foods with added or free sugars depending on the country's labeling system."],
      ["Pay attention to sodium", "Compare sodium amounts across similar products if you are trying to reduce sodium. A product can taste only mildly salty and still contain significant sodium, so labels can be useful."],
      ["Compare similar products", "A label is most useful when comparing two or more similar foods. Consider serving size, nutrient density, ingredients, price and how the food fits into your usual eating pattern."],
    ],
  },
  {
    slug: "healthy-eating-on-a-budget", category: "Nutrition", categorySlug: "nutrition",
    title: "Healthy Eating on a Budget: Practical Strategies for Any Country",
    description: "Build a nutritious eating pattern without assuming one country's foods, prices or diet culture.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "healthy eating on a budget, affordable healthy food, budget nutrition",
    sources: [{ label: "WHO — Healthy diet", url: WHO_DIET }, { label: "SOFI 2026 — Cost of a healthy diet", url: "https://www.who.int/publications/m/item/the-state-of-food-security-and-nutrition-in-the-world-2026" }],
    sections: [
      ["Healthy eating does not require expensive superfoods", "Nutritious diets can be built from many different foods. WHO notes that healthy diets vary with local availability, culture and circumstances. Expensive specialty products are not necessary for a healthy dietary pattern."],
      ["Plan before shopping", "Planning a few meals, checking what you already have and making a simple shopping list can reduce waste and impulse purchases. Choose foods that can be used across several meals."],
      ["Use affordable staples", "Staple grains, legumes, vegetables, fruits and other locally available nutritious foods can form the foundation of meals. Frozen or canned produce can also be practical in many settings; compare added sodium or sugars when relevant."],
      ["Reduce waste", "Use perishable foods first, store food appropriately and repurpose leftovers safely. Reducing waste can lower the effective cost of a nutritious diet."],
      ["Affordability is a real public-health issue", "The ability to afford a healthy diet differs greatly around the world. Individual choices matter, but food prices, availability, marketing and the broader food environment also influence what people can realistically eat."],
    ],
  },
  {
    slug: "hydration-and-water", category: "Nutrition", categorySlug: "nutrition",
    title: "Hydration and Water: How to Support Healthy Fluid Intake",
    description: "Understand hydration, thirst, activity, climate and why fluid needs are not identical for everyone.",
    readTime: "7 min read", date: "September 3, 2026", keywords: "hydration, water intake, drinking water, hydration needs",
    sources: src(),
    sections: [
      ["Why fluids matter", "Water is essential for normal physiological functions. Fluid balance is influenced by drinking, the water contained in foods and losses through urine, sweat, breathing and other processes."],
      ["There is no universal glass count", "Fluid requirements vary with body size, activity, climate, diet, age and health status. Rather than treating one fixed number as correct for everyone, pay attention to thirst and circumstances that increase fluid losses."],
      ["Hydration during exercise", "Long or vigorous activity, especially in hot environments, can increase fluid losses through sweat. Drinking appropriately around activity is important. Very prolonged exercise may require a more individualized hydration strategy."],
      ["Choose beverages thoughtfully", "Water is a simple choice for hydration. Sugar-sweetened beverages can add substantial free sugars, so limiting them is consistent with healthy-diet guidance. Alcohol has health risks and should not be treated as a hydration strategy."],
      ["When to seek advice", "Some illnesses and medications can alter fluid needs. People with conditions affecting the heart, kidneys or fluid balance may need individualized instructions from a healthcare professional."],
    ],
  },
  {
    slug: "how-to-build-a-balanced-meal", category: "Nutrition", categorySlug: "nutrition",
    title: "How to Build a Balanced Meal Without Following a Rigid Diet",
    description: "A flexible framework for combining nutritious foods while respecting different cultures, budgets and dietary preferences.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "balanced meal, healthy meal, balanced diet, meal planning",
    sources: src([{ label: "WHO & FAO — What are healthy diets?", url: WHO_FAO }]),
    sections: [
      ["Think pattern, not perfection", "A balanced meal does not need to follow one exact plate diagram. A useful approach is to combine several food groups and prioritize variety over time. WHO and FAO emphasize that healthy diets can differ across cultures while sharing core principles."],
      ["Include plant foods regularly", "Vegetables, fruits, legumes, whole grains, nuts and seeds can provide fibre and a range of micronutrients. Use the foods that are affordable, accessible and culturally appropriate where you live."],
      ["Add a protein source", "Depending on dietary preference, protein can come from legumes, dairy foods, eggs, fish, meat, nuts, seeds or other sources. Variety can help broaden nutrient intake."],
      ["Choose fats thoughtfully", "Use unsaturated-fat sources more often and limit saturated and industrial trans fats. Remember that portion size can matter because fats are energy-dense."],
      ["Make it sustainable", "A healthy meal plan should be realistic enough to repeat. Consider cooking time, budget, food availability, taste, culture and household needs. Consistency over weeks matters more than a perfect individual meal."],
    ],
  },
  {
    slug: "what-are-macros", category: "Nutrition", categorySlug: "nutrition",
    title: "What Are Macros? Protein, Carbohydrates and Fat Explained",
    description: "Understand macronutrients and how they fit into energy balance and a varied diet.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "macros, macronutrients, protein carbs fat, macro calculator",
    sources: src(),
    sections: [
      ["What does macro mean?", "Macronutrients are nutrients required in relatively large amounts. The three commonly discussed macros are protein, carbohydrates and fat. Alcohol also provides energy but is not considered an essential macronutrient."],
      ["Protein", "Protein supplies amino acids needed for growth, maintenance and repair. Sources vary widely by dietary pattern. Total protein intake should be considered alongside overall diet quality and individual needs."],
      ["Carbohydrates", "Carbohydrates are an important energy source and are found in grains, legumes, fruits, vegetables and many packaged foods. Higher-fibre and less-refined sources can contribute to a nutritious dietary pattern."],
      ["Fat", "Fat provides energy and supports several physiological functions. WHO recommends shifting toward unsaturated fats and limiting saturated and industrial trans fats."],
      ["Should you track macros?", "Macro tracking can be useful for some people, but it is not required for everyone. It should not replace attention to food quality, variety, fibre, fruit and vegetables, sodium and free sugars."],
    ],
  },
  {
    slug: "nutrition-for-muscle-growth", category: "Nutrition", categorySlug: "nutrition",
    title: "Nutrition for Muscle Growth: The Basics That Matter Most",
    description: "Understand the roles of training, protein, energy, sleep and dietary quality in supporting muscle development.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "muscle growth nutrition, protein muscle, nutrition for muscle gain",
    sources: src([{ label: "WHO — Physical activity", url: WHO_PHYSICAL }]),
    sections: [
      ["Muscle growth is not only about protein", "Resistance training provides the stimulus for muscle adaptation. Nutrition supplies energy and amino acids, while recovery and sleep support the process. No single food or supplement can replace a well-designed training routine."],
      ["Get enough protein", "Adequate protein is important for tissue maintenance and adaptation. The ideal amount varies by person and context. A calculator can provide an estimate, but specialized needs should be discussed with a qualified professional."],
      ["Do not ignore energy intake", "Building muscle can be difficult if energy intake is chronically insufficient. On the other hand, very large calorie surpluses can lead to unnecessary fat gain. The appropriate approach depends on goals and individual circumstances."],
      ["Choose a varied diet", "Carbohydrate-rich foods can support training, while fruits, vegetables, whole grains, legumes, nuts, seeds and other nutritious foods provide fibre and micronutrients. A varied diet is more useful than focusing on a single nutrient."],
      ["Recovery matters", "Regular sleep and recovery days complement training. WHO recommends regular physical activity and muscle-strengthening activities for adults, but training volume should be adjusted to fitness, experience and health status."],
    ],
  },
  {
    slug: "pre-workout-and-post-workout-nutrition", category: "Nutrition", categorySlug: "nutrition",
    title: "Pre-Workout and Post-Workout Nutrition: What Actually Matters",
    description: "A practical overview of eating around exercise without unnecessary complexity or rigid timing rules.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "pre workout nutrition, post workout nutrition, workout meal, exercise nutrition",
    sources: src([{ label: "WHO — Physical activity", url: WHO_PHYSICAL }]),
    sections: [
      ["Start with the whole day", "Nutrition around a workout is only one part of the picture. Total energy intake, dietary quality, protein, carbohydrates, hydration and recovery habits generally matter more than chasing a perfect minute-by-minute eating schedule."],
      ["Before exercise", "A meal or snack containing carbohydrate and, when useful, some protein can support training for many people. The best timing and portion depend on the exercise, meal size, digestion and individual preference."],
      ["After exercise", "A balanced meal containing protein and carbohydrate can support recovery. You do not need a special commercial recovery product if ordinary nutritious foods meet your needs."],
      ["Hydration", "Fluid needs increase when sweating increases. Hot weather and prolonged exercise can change requirements. Drink appropriately and use individualized advice when exercise or health circumstances are unusual."],
      ["Avoid unnecessary complexity", "Supplements, special shakes and exact nutrient timing are not requirements for most recreational exercisers. Build a consistent eating pattern first, then consider specialized strategies when there is a clear reason."],
    ],
  },
  {
    slug: "what-is-a-calorie-deficit", category: "Weight Management", categorySlug: "weight-loss",
    title: "What Is a Calorie Deficit? A Clear Guide to Energy Balance",
    description: "Understand calorie deficits, energy expenditure and why sustainable weight management is more complex than one equation.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "calorie deficit, energy deficit, weight loss, calorie balance",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }, { label: "WHO — Healthy diet", url: WHO_DIET }],
    sections: [
      ["What a calorie deficit means", "A calorie deficit occurs when energy intake is lower than energy expenditure over a period of time. It is a useful concept for understanding weight change, but it does not capture every biological, behavioural and environmental factor that affects weight management."],
      ["Why maintenance calories vary", "Energy expenditure changes with body size, age, activity and other factors. As weight changes, energy requirements can also change. Calculator estimates should therefore be treated as starting points rather than permanent targets."],
      ["Avoid extreme restriction", "Very restrictive diets can make it difficult to meet nutrient needs and may be difficult to sustain. A practical approach emphasizes nutritious foods, adequate protein and fibre, regular activity and realistic habits."],
      ["Track progress thoughtfully", "Body weight naturally fluctuates because of water, food in the digestive tract and other factors. Looking at trends over time can be more informative than reacting to one day's measurement."],
      ["When professional support is useful", "People with eating disorders, pregnancy, certain medical conditions or other specialized circumstances should seek individualized guidance rather than following generic calorie-deficit advice."],
    ],
  },
  {
    slug: "healthy-weight-loss-basics", category: "Weight Management", categorySlug: "weight-loss",
    title: "Healthy Weight Loss: Evidence-Informed Basics That Can Last",
    description: "Learn practical principles for sustainable weight management without crash diets or unrealistic promises.",
    readTime: "10 min read", date: "September 3, 2026", keywords: "healthy weight loss, sustainable weight loss, weight management tips",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }, { label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["Weight management is more than willpower", "WHO describes overweight and obesity as complex conditions influenced by biological, behavioural and environmental factors. This means sustainable change is not simply a test of motivation."],
      ["Build a nutritious eating pattern", "Prioritize a variety of vegetables, fruits, legumes, whole grains and other nutritious foods. Limit frequent intake of foods and drinks high in free sugars, sodium and unhealthy fats."],
      ["Move regularly", "WHO recommends regular physical activity because it benefits physical and mental health and helps with weight management. Some activity is better than none, and activity can be accumulated in different ways."],
      ["Set realistic expectations", "Weight change is not perfectly linear. Plateaus and fluctuations can occur. Focus on behaviours you can repeat rather than promising a specific amount of weight loss by a particular date."],
      ["Protect your relationship with food", "Avoid advice that encourages guilt, fear or unnecessary food restriction. If eating or weight concerns are causing significant distress, seek support from a qualified health professional."],
    ],
  },
  {
    slug: "why-am-i-not-losing-weight", category: "Weight Management", categorySlug: "weight-loss",
    title: "Why Am I Not Losing Weight? Common Reasons and Better Next Steps",
    description: "Understand plateaus, measurement error, energy needs and factors that can affect weight trends.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "not losing weight, weight loss plateau, weight loss stalled",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["First, check the trend", "Daily body weight can change because of water, food intake, bowel contents and other short-term factors. A few days of unchanged weight does not necessarily mean fat loss has stopped."],
      ["Estimates are not measurements", "Calorie calculators use equations and assumptions. Actual energy expenditure can differ. As body weight changes, maintenance needs may change too. Treat calculator results as estimates rather than exact physiological measurements."],
      ["Look at the whole pattern", "Portions, drinks, snacks, weekends, activity and changes in routine can influence total intake and expenditure. This is not a reason for guilt; it is a reason to examine the pattern calmly."],
      ["Consider sleep and activity", "Sleep, sedentary time and physical activity can influence health and weight-management behaviours. WHO recommends regular physical activity and reducing sedentary behaviour."],
      ["When to talk to a professional", "If weight changes are unexpected, rapid, persistent or accompanied by other symptoms, discuss them with a healthcare professional. Medications and medical conditions can affect body weight."],
    ],
  },
  {
    slug: "bmi-vs-body-fat", category: "Body Composition", categorySlug: "body-composition",
    title: "BMI vs Body Fat Percentage: What Is the Difference?",
    description: "Understand what BMI and body-fat estimates measure, what they can and cannot tell you, and why context matters.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "BMI vs body fat, body fat percentage, BMI meaning, body composition",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["BMI is a screening measure", "Body mass index is calculated from weight and height. It is useful for population-level assessment and as a screening measure, but it does not directly measure body fat or distinguish muscle from fat."],
      ["Body-fat percentage estimates fat mass", "Body-fat percentage expresses estimated fat mass as a proportion of total body mass. Different methods have different levels of accuracy, and many consumer methods are estimates rather than direct measurements."],
      ["Why the numbers can disagree", "A muscular person can have a relatively high BMI without having high body fat. Conversely, someone can have a BMI within a conventional range while carrying more body fat than expected. This is why context matters."],
      ["Use more than one measure", "Waist circumference, body weight, activity, blood pressure, laboratory measures and other health information can provide additional context. No single body-composition number provides a complete picture of health."],
      ["Use FitMe Pro responsibly", "FitMe Pro calculators are educational tools. They can help you understand calculations and trends but should not be used to diagnose a disease or determine medical treatment."],
    ],
  },
  {
    slug: "what-is-body-fat-percentage", category: "Body Composition", categorySlug: "body-composition",
    title: "What Is Body Fat Percentage and How Is It Estimated?",
    description: "Learn what body-fat percentage means, why estimates differ and how to interpret the number cautiously.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "body fat percentage, body fat calculator, body composition measurement",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["What body-fat percentage means", "Body-fat percentage is the proportion of total body mass that is estimated to be fat tissue. It is one measure of body composition, not a complete measure of health."],
      ["Methods differ", "Skinfold measurements, bioelectrical impedance, circumference equations and laboratory methods can produce different estimates. Hydration, equipment, technique and assumptions can influence results."],
      ["Trends can be more useful than one reading", "If you use the same method consistently, repeated measurements may help identify a trend. Comparing numbers from different methods can create misleading changes."],
      ["There is no single ideal number for everyone", "Body composition varies with age, sex and other factors. Fitness goals also differ. Avoid treating one internet chart as a universal medical threshold."],
      ["Interpret alongside other information", "Combine body-composition measurements with activity, diet quality, waist measures, health history and professional advice where appropriate."],
    ],
  },
  {
    slug: "waist-circumference-health", category: "Body Composition", categorySlug: "body-composition",
    title: "Waist Circumference and Health: Why This Measurement Matters",
    description: "Understand why waist circumference can add context to BMI and how measurement technique affects the result.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "waist circumference, waist measurement, abdominal obesity, health risk",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["Why waist circumference is useful", "Where body fat is distributed can provide information that body weight alone does not. Waist circumference is one simple measure used in health assessment, particularly in relation to central adiposity."],
      ["Measure consistently", "Use a consistent measurement site and technique. Keep the tape level and avoid pulling it excessively tight. Repeating the measurement can reduce accidental errors."],
      ["It is not a diagnosis", "Waist circumference is a screening or risk-related measure. Thresholds can vary by population and guideline, so a result should be interpreted in context rather than treated as a diagnosis."],
      ["Combine it with other measures", "BMI, blood pressure, blood glucose, lipid measures, activity and medical history can provide additional information. A single tape measurement cannot determine overall health."],
      ["Use trends carefully", "If you are tracking waist circumference, use the same conditions and technique each time. Short-term changes can reflect posture, meals and measurement variability."],
    ],
  },
  {
    slug: "what-is-bmr", category: "Body Composition", categorySlug: "body-composition",
    title: "What Is BMR? Basal Metabolic Rate Explained",
    description: "Learn what basal metabolic rate means, what affects it and how BMR calculators should be interpreted.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "BMR, basal metabolic rate, BMR calculator, metabolism",
    sources: src(),
    sections: [
      ["BMR in simple terms", "Basal metabolic rate refers to the energy the body uses to support basic physiological functions under specified resting conditions. It is only one component of total daily energy expenditure."],
      ["What influences metabolic needs", "Body size, age, sex, body composition and other physiological factors influence resting energy expenditure. Two people can therefore have different BMRs even if they share some characteristics."],
      ["BMR is not your calorie target", "Eating exactly your BMR is not a standard weight-loss strategy. Your body uses energy for movement and other processes beyond resting metabolism. TDEE estimates are designed to account for a broader picture."],
      ["Why calculator results differ", "Different equations use different variables and assumptions. A calculated BMR is an estimate and may not equal a measurement from indirect calorimetry."],
      ["Use it as a starting point", "BMR can be useful for understanding energy expenditure and building a broader estimate of calorie needs. FitMe Pro provides calculators for BMR, TDEE and daily calorie needs so the concepts can be viewed together."],
    ],
  },
  {
    slug: "what-is-tdee", category: "Body Composition", categorySlug: "body-composition",
    title: "What Is TDEE? Understanding Total Daily Energy Expenditure",
    description: "Learn how resting metabolism, activity and other components contribute to daily energy expenditure.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "TDEE, total daily energy expenditure, TDEE calculator, maintenance calories",
    sources: src(),
    sections: [
      ["TDEE explained", "Total daily energy expenditure is an estimate of the energy a person uses across a day. It includes resting energy expenditure plus physical activity and other components of energy use."],
      ["Activity matters", "Physical activity includes exercise as well as movement during work, transportation and daily life. WHO defines physical activity broadly as bodily movement produced by skeletal muscles that requires energy expenditure."],
      ["TDEE changes", "Energy expenditure is not fixed. Changes in body weight, activity, routine and other factors can change the estimate. This is one reason maintenance-calorie estimates should be revisited when circumstances change."],
      ["TDEE and weight goals", "A TDEE estimate can be used as one input when planning a calorie deficit or surplus. It should not be treated as a precise measurement or a guarantee of future weight change."],
      ["Use the result with nutrition quality", "A calorie target is only one part of a healthy approach. WHO emphasizes dietary diversity, adequacy, balance and moderation. Use energy estimates alongside nutritious food choices and regular activity."],
    ],
  },
  {
    slug: "how-to-measure-body-composition", category: "Body Composition", categorySlug: "body-composition",
    title: "How to Measure Body Composition: A Guide to Common Methods",
    description: "Compare BMI, waist measurements, circumference methods, bioelectrical impedance and other approaches to tracking body composition.",
    readTime: "10 min read", date: "September 3, 2026", keywords: "body composition measurement, body fat measurement, body composition methods",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["No single method is perfect", "Body composition can be assessed in several ways, each with strengths and limitations. The best choice depends on the purpose, available equipment, cost and need for precision."],
      ["BMI and waist measures", "BMI is easy to calculate and useful as a screening measure. Waist circumference adds information about fat distribution. Both are simple but do not directly measure total body fat."],
      ["Bioelectrical impedance", "BIA devices estimate body composition using electrical properties of the body and predictive equations. Hydration and other factors can affect results, so consistent measurement conditions matter."],
      ["Circumference and skinfold methods", "Circumference equations and skinfold measurements use body dimensions to estimate body fat. Technique and equation selection can influence the result."],
      ["Track trends, not false precision", "If your goal is progress tracking, consistency may be more useful than chasing tiny changes. Use the same method and conditions when possible, and consider multiple indicators of health and fitness."],
    ],
  },
  {
    slug: "physical-activity-guidelines", category: "Fitness", categorySlug: "fitness",
    title: "How Much Physical Activity Do Adults Need? WHO Guidelines Explained",
    description: "A practical summary of WHO physical-activity recommendations for adults and why every bit of movement can help.",
    readTime: "9 min read", date: "September 3, 2026", keywords: "physical activity guidelines, WHO exercise recommendations, 150 minutes exercise",
    sources: [{ label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["The basic adult recommendation", "WHO recommends that adults aged 18–64 do at least 150 minutes of moderate-intensity physical activity per week, or at least 75 minutes of vigorous-intensity activity, or an equivalent combination. More activity can provide additional benefits."],
      ["Strength training matters too", "WHO recommends muscle-strengthening activities involving major muscle groups on at least two days per week for adults. Strength work complements aerobic activity."],
      ["Some movement is better than none", "People who are inactive can benefit from starting with manageable amounts of movement and gradually building up. Walking, cycling, active recreation, sport and physically active work can all contribute."],
      ["Reduce sedentary time", "Sedentary behaviour is distinct from simply not exercising. Long periods of sitting or reclining can be reduced by breaking up sitting and incorporating more movement throughout the day."],
      ["Adapt activity to your circumstances", "Fitness level, age, disability, chronic conditions and pregnancy can change what is appropriate. If you have a health condition or have been inactive for a long time, individualized professional guidance can be useful."],
    ],
  },
  {
    slug: "strength-training-for-beginners", category: "Fitness", categorySlug: "fitness",
    title: "Strength Training for Beginners: A Safe, Simple Starting Point",
    description: "Learn the fundamentals of resistance training, progression, recovery and realistic expectations for beginners.",
    readTime: "10 min read", date: "September 3, 2026", keywords: "strength training beginners, resistance training, beginner workout",
    sources: [{ label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["What strength training is", "Strength training uses resistance to challenge muscles. Resistance can come from weights, machines, resistance bands or bodyweight exercises. The goal is to gradually improve the ability to perform movements under resistance."],
      ["Start with major movement patterns", "A beginner program can include movements that train the legs, hips, pushing muscles, pulling muscles and trunk. Technique and manageable loads are more important initially than lifting as much as possible."],
      ["Progress gradually", "Progression can involve increasing repetitions, resistance, sets, range of motion or movement quality. Make changes gradually enough that recovery remains manageable."],
      ["Recovery is part of training", "Muscles need time to recover. Sleep, adequate food and rest days all contribute to a sustainable program. More training is not automatically better."],
      ["Know when to seek help", "Pain, dizziness, chest symptoms or other concerning symptoms during exercise warrant stopping and seeking appropriate medical advice. A qualified trainer can also help beginners learn technique."],
    ],
  },
  {
    slug: "walking-for-health", category: "Fitness", categorySlug: "fitness",
    title: "Walking for Health: Benefits, Ideas and Ways to Build a Routine",
    description: "Walking is accessible in many settings. Learn how it contributes to physical activity and how to build a sustainable routine.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "walking for health, walking exercise, daily walking, walking benefits",
    sources: [{ label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["Walking counts as physical activity", "WHO includes walking among common forms of physical activity. Activity can occur during leisure, transportation, work and daily life, not only in a gym."],
      ["Start where you are", "If you are inactive, begin with manageable walks and increase duration or frequency gradually. Even small increases in movement can be a practical step toward a more active routine."],
      ["Intensity can vary", "A comfortable walk and a brisk walk are both useful forms of movement. Moderate intensity means breathing and heart rate increase while conversation remains possible for many people."],
      ["Make it easier to repeat", "Choose routes and times that fit your routine. Walking with a friend, walking for transportation or using short activity breaks can improve consistency."],
      ["Walking is one part of fitness", "Walking supports aerobic activity, but strength and other forms of movement can add benefits. A varied routine can address different aspects of physical fitness."],
    ],
  },
  {
    slug: "exercise-recovery-and-rest", category: "Fitness", categorySlug: "fitness",
    title: "Exercise Recovery and Rest: Why More Training Is Not Always Better",
    description: "Understand recovery, fatigue, sleep and how to build sustainable training habits.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "exercise recovery, rest days, workout recovery, overtraining",
    sources: [{ label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["Training creates stress", "Exercise challenges the body. Adaptation requires recovery as well as training. Increasing volume rapidly without enough recovery can lead to excessive fatigue and reduced performance."],
      ["Sleep supports recovery", "Sleep is part of a healthy lifestyle and can affect how well people recover and function. Consistent sleep habits can support training and general wellbeing."],
      ["Use rest strategically", "Rest does not mean doing nothing. Easy movement can be useful between harder sessions, while complete rest may be appropriate when fatigue is high or illness is present."],
      ["Watch for warning signs", "Persistent performance decline, unusual fatigue, recurring injuries, sleep problems or mood changes can signal that training or recovery needs attention. Seek professional advice when symptoms persist."],
      ["Build sustainable training", "A good program balances challenge and recovery. The best routine is one that you can maintain over time while meeting your health and fitness goals."],
    ],
  },
  {
    slug: "sleep-and-health", category: "Wellness", categorySlug: "wellness",
    title: "Sleep and Health: Why Recovery Belongs in a Healthy Lifestyle",
    description: "Explore the role of sleep in everyday wellbeing, recovery and healthy routines without promising a one-size-fits-all sleep target.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "sleep and health, sleep recovery, healthy sleep habits",
    sources: [{ label: "WHO — Self-care for health and well-being", url: "https://www.who.int/news-room/fact-sheets/detail/self-care-health-interventions" }],
    sections: [
      ["Sleep is part of health", "Sleep supports everyday functioning, recovery and wellbeing. It works alongside nutrition, physical activity and other health behaviours rather than existing as a separate wellness trend."],
      ["Build a consistent routine", "Going to bed and waking at broadly consistent times can make a routine easier to maintain. A calm pre-sleep period and a suitable sleep environment may also help."],
      ["Exercise and sleep", "Regular physical activity is associated with several health benefits, including improvements in sleep. Avoid treating exercise as a punishment for poor sleep; recovery should remain part of the plan."],
      ["Look at the bigger picture", "Caffeine, alcohol, stress, screen use, work schedules and medical conditions can influence sleep. Changes in sleep should be considered in the context of your life rather than one isolated habit."],
      ["When to seek help", "Persistent insomnia, loud snoring with breathing pauses, severe daytime sleepiness or other ongoing symptoms should be discussed with a healthcare professional."],
    ],
  },
  {
    slug: "sedentary-behaviour-and-health", category: "Wellness", categorySlug: "wellness",
    title: "Sedentary Behaviour: Why Sitting Less Matters",
    description: "Understand sedentary behaviour, movement breaks and how to make everyday life more active.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "sedentary behaviour, sitting too much, movement breaks, inactive lifestyle",
    sources: [{ label: "WHO — Physical activity", url: WHO_PHYSICAL }],
    sections: [
      ["What is sedentary behaviour?", "Sedentary behaviour refers to periods of low energy expenditure while awake, such as sitting, reclining or lying down. It is different from simply failing to complete a workout."],
      ["Why it matters", "WHO reports that higher amounts of sedentary behaviour are associated with several adverse health outcomes. Reducing long periods of sitting is therefore a useful complement to structured exercise."],
      ["Break up long sitting periods", "Stand, walk, stretch or change tasks periodically when practical. Short movement breaks can fit into work, study and travel routines without requiring a full workout."],
      ["Make movement part of daily life", "Walking for transportation, taking stairs when appropriate, household activities and active recreation can all add movement. The best approach depends on your environment and abilities."],
      ["Combine movement types", "Aim for both regular physical activity and less sedentary time. Aerobic activity, strength training and everyday movement can work together to support health."],
    ],
  },
  {
    slug: "stress-and-healthy-habits", category: "Wellness", categorySlug: "wellness",
    title: "Stress and Healthy Habits: Building a Sustainable Routine",
    description: "Practical ways to support healthy routines when work, study, family and daily pressures make consistency difficult.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "stress management, healthy habits, wellness routine, self care",
    sources: [{ label: "WHO — Self-care for health and well-being", url: "https://www.who.int/news-room/fact-sheets/detail/self-care-health-interventions" }],
    sections: [
      ["Healthy habits do not require a perfect schedule", "A sustainable routine is one that can survive busy days. Start with a few behaviours that have a realistic place in your life rather than attempting a complete lifestyle overhaul."],
      ["Movement can be a useful habit", "Physical activity can support physical and mental wellbeing. Choose forms of movement that are enjoyable and accessible, and increase gradually when needed."],
      ["Nutrition under stress", "Stress can change appetite, food choices and meal timing. Keeping simple nutritious foods available and maintaining regular meals when possible can make healthy eating easier."],
      ["Protect recovery", "Sleep and downtime are not wasted time. Recovery supports the ability to work, study, exercise and manage daily demands."],
      ["Know when self-care is not enough", "Self-care is not a substitute for medical or mental-health care when a problem is persistent or severe. Reach out to an appropriate professional when you need more support."],
    ],
  },
  {
    slug: "what-is-obesity", category: "Health Education", categorySlug: "health-education",
    title: "What Is Obesity? Understanding a Complex Health Condition",
    description: "A plain-language explanation of obesity, risk factors, measurement and why weight stigma can be harmful.",
    readTime: "10 min read", date: "September 3, 2026", keywords: "what is obesity, obesity explained, obesity health, overweight obesity",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["Obesity is a complex condition", "WHO describes obesity as a chronic, complex disease characterized by excessive fat accumulation that can impair health. It results from interactions among genetic, biological, behavioural and environmental factors rather than a single cause."],
      ["BMI has a role, but limits", "BMI is widely used as a screening measure. It does not directly measure body fat and should be interpreted with other information. Clinical assessment may involve additional measurements and health history."],
      ["Why the environment matters", "Food availability, marketing, urban design, opportunities for physical activity, socioeconomic conditions and other environmental factors can influence health behaviours and weight."],
      ["Health risks are individual", "Higher levels of excess body fat can be associated with increased risk of several health conditions, but individual risk varies. A calculator result cannot determine an individual's diagnosis or future health by itself."],
      ["Avoid stigma", "Weight stigma can harm wellbeing and may discourage people from seeking care. Health communication should focus on respectful, evidence-informed support rather than blame."],
    ],
  },
  {
    slug: "understanding-bmi", category: "Health Education", categorySlug: "health-education",
    title: "BMI Explained: What the Number Means and What It Does Not",
    description: "Learn how BMI is calculated, why it is useful as a screening tool and why it should not be interpreted alone.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "BMI explained, BMI meaning, body mass index, BMI categories",
    sources: [{ label: "WHO — Obesity and overweight", url: WHO_OBESITY }],
    sections: [
      ["What is BMI?", "BMI is calculated by dividing body weight in kilograms by height in metres squared. It provides a simple numerical relationship between weight and height."],
      ["Why BMI is used", "BMI is inexpensive and easy to calculate, which makes it useful for population studies and as a screening measure. It is not a direct measurement of body fat."],
      ["Important limitations", "BMI does not distinguish fat from muscle and does not show where fat is distributed. Age, sex, ethnicity, muscularity and other factors can affect how the number should be interpreted."],
      ["Use BMI with context", "Waist circumference, health history, blood pressure, laboratory results, physical activity and other information can add context. For individual medical decisions, use professional assessment."],
      ["Try the calculator", "The FitMe Pro BMI Calculator can perform the arithmetic quickly. Treat the result as an educational screening value, not a diagnosis."],
    ],
  },
  {
    slug: "nutrition-myths-facts", category: "Health Education", categorySlug: "health-education",
    title: "Nutrition Myths vs Facts: How to Evaluate Health Claims",
    description: "A practical framework for spotting exaggerated nutrition claims and finding more trustworthy evidence.",
    readTime: "10 min read", date: "September 3, 2026", keywords: "nutrition myths, nutrition facts, health misinformation, diet myths",
    sources: [{ label: "WHO — Healthy diet", url: WHO_DIET }, { label: "WHO — Nutrition", url: "https://www.who.int/en/health-topics/nutrition" }],
    sections: [
      ["Beware of miracle claims", "Nutrition is complex. Claims that one food, drink or supplement can prevent disease, melt fat or replace a balanced diet deserve skepticism. Strong health claims should be supported by appropriate evidence."],
      ["Look for primary or authoritative sources", "WHO, national public-health agencies, professional organizations and high-quality research can be more useful than anonymous social posts. Check the date because nutrition guidance can be updated."],
      ["Ask what the claim actually measures", "A study may examine a biomarker, short-term weight change or a clinical outcome. These are not interchangeable. Understanding the outcome helps prevent exaggerated conclusions."],
      ["Watch for absolute language", "Words such as always, never, detox, guaranteed and cure can signal oversimplification. Healthy diets are generally about patterns rather than a single perfect food."],
      ["FitMe Pro's approach", "FitMe Pro Journal uses authoritative public-health sources as references and aims to explain evidence in plain language without copying source publications or presenting calculators as medical diagnosis tools."],
    ],
  },
  {
    slug: "when-to-see-a-health-professional", category: "Health Education", categorySlug: "health-education",
    title: "When Should You Talk to a Health Professional About Nutrition or Weight?",
    description: "Know when general online guidance is not enough and individualized medical or dietetic support is appropriate.",
    readTime: "8 min read", date: "September 3, 2026", keywords: "nutritionist when to see, doctor weight loss, dietitian advice, health professional",
    sources: [{ label: "WHO — Self-care for health and well-being", url: "https://www.who.int/news-room/fact-sheets/detail/self-care-health-interventions" }],
    sections: [
      ["Online tools have limits", "Calculators and articles can explain concepts and provide estimates, but they cannot take a full medical history, perform an examination or interpret every health factor."],
      ["Unexpected weight change", "Unexplained, rapid or persistent changes in weight can have many causes. If a change is concerning or accompanied by other symptoms, discuss it with a healthcare professional."],
      ["Medical conditions and medications", "Diabetes, kidney disease, gastrointestinal disorders, eating disorders, pregnancy and many medications can affect nutrition or weight-management needs. Generic calculator targets may not be appropriate."],
      ["Eating-disorder concerns", "If food, exercise or body image is causing significant distress or restrictive, bingeing or compensatory behaviours are present, seek qualified professional support rather than following weight-loss content online."],
      ["Use tools as supplements to care", "FitMe Pro is designed for education and calculation. It should complement—not replace—appropriate professional healthcare when individualized assessment is needed."],
    ],
  },
];

export function getJournalArticle(slug) { return JOURNAL_ARTICLES.find((article) => article.slug === slug); }
export function getJournalCategory(slug) { return JOURNAL_CATEGORIES.find((category) => category.slug === slug); }
