// Long-form SEO content for prerendered calculator pages.
// The renderer expands each topic into a substantial, structured article and 10 FAQs.
// Keep claims conservative: calculators are estimates and are not medical diagnoses.

const BASE_FAQS = [
  ["What does the {name} calculate?", "It provides an estimate of {what}. The result should be interpreted in the context of the inputs, the formula used, and the limitations described below."],
  ["How is the {name} calculated?", "The calculator uses {formula}. Enter the requested measurements in the stated units and the calculator applies the formula consistently."],
  ["What information do I need to use the {name}?", "You need {inputs}. Accurate, consistently measured inputs generally produce a more useful estimate."],
  ["How accurate is the {name}?", "Accuracy depends on the formula, measurement technique, population, and individual characteristics. A calculated value is an estimate rather than a direct laboratory or clinical measurement."],
  ["Can I use this calculator for weight loss or fitness planning?", "Yes, it can be used as one piece of a broader plan. It should not be treated as a guarantee of a particular rate of weight change, muscle gain, or health outcome."],
  ["Why can my result change even when I feel the same?", "Small changes in body weight, tape measurements, hydration, posture, measurement location, or other inputs can change a calculated result. Consistent measurement conditions make trends easier to interpret."],
  ["What is the biggest mistake people make with this calculation?", "The most common problems are inconsistent measurements, incorrect units, entering an estimate as though it were a precise measurement, or applying a population reference as a personal diagnosis."],
  ["Should I compare my result with other calculators?", "Comparison can be useful when the calculators measure related concepts, but different formulas can legitimately produce different estimates. Look at the method and intended use rather than choosing the highest or lowest number."],
  ["How often should I recalculate it?", "Recalculate when a meaningful input changes or when you are tracking a trend. For body measurements, using the same time of day, equipment, and technique can reduce noise."],
  ["Does this calculator replace medical advice?", "No. It is an educational calculation tool. If a result concerns you or relates to a medical condition, discuss it with a qualified healthcare professional."],
];

const TOPICS = {
  bmi: { name:"BMI Calculator", what:"body mass index from body weight and height", inputs:"height and body weight", formula:"BMI = weight in kilograms divided by height in meters squared", why:"BMI is a simple screening measure that places weight relative to height", interpretation:"For adults, commonly used BMI categories are underweight below 18.5, healthy weight from 18.5 to 24.9, overweight from 25.0 to 29.9, and obesity at 30 or above. These are screening categories rather than a complete assessment of health.", accuracy:"BMI does not distinguish fat from muscle, bone, water, or organ tissue. Athletes and people with unusual body composition can therefore receive a misleading category.", mistakes:"Measure height without shoes, use a reliable scale, and do not mix inches with centimeters or pounds with kilograms without conversion.", use:"screening body size, tracking broad weight trends, discussing weight with a clinician, and deciding whether a more detailed body-composition measure may be useful", related:["Healthy Weight Range Calculator","Body Fat Calculator","Waist-to-Height Ratio Calculator","BMI Prime Calculator"] },
  "bmi-prime": { name:"BMI Prime Calculator", what:"BMI Prime by comparing BMI with the upper boundary of the commonly used adult healthy BMI range", inputs:"your BMI", formula:"BMI Prime = BMI / 25", why:"BMI Prime expresses BMI as a simple ratio relative to 25", interpretation:"A BMI Prime of 1.00 corresponds to a BMI of 25. Values below 1 are below that reference point and values above 1 are above it. It is a ratio, not a diagnosis or a measure of body-fat percentage.", accuracy:"Its accuracy is inherited from BMI because it is calculated from BMI rather than measured directly.", mistakes:"Do not interpret BMI Prime as a percentage of body fat and do not use it as a standalone measure of health.", use:"quickly comparing BMI with the upper reference point, explaining BMI in ratio form, and tracking changes in BMI over time", related:["BMI Calculator","Healthy Weight Range Calculator","Body Fat Calculator"] },
  "healthy-weight-range": { name:"Healthy Weight Range Calculator", what:"an estimated weight range corresponding to the adult BMI reference range", inputs:"height", formula:"weight range = BMI reference value × height²", why:"People often want to translate a BMI reference range into actual kilograms or pounds", interpretation:"For adults, a commonly used reference is BMI 18.5 through 24.9. The resulting weight range changes substantially with height and is intended as a population-level screening reference rather than a personal target that every person must reach.", accuracy:"The range inherits BMI's limitations and does not account for muscle mass, fat distribution, ethnicity, medical history, or individual goals.", mistakes:"Use the same unit system throughout the calculation and remember that a mathematical range is not automatically a medically appropriate goal weight.", use:"setting a broad reference range, understanding the relationship between height and weight, and preparing questions for a healthcare professional", related:["BMI Calculator","Ideal Body Weight Calculator","Weight Loss Goal Calculator","Body Frame Size Calculator"] },
  "ideal-body-weight": { name:"Ideal Body Weight Calculator", what:"an estimated ideal body weight using the Devine equation", inputs:"height and sex category used by the formula", formula:"Devine IBW: 50 kg + 2.3 kg for each inch over 5 feet for males; 45.5 kg + 2.3 kg for each inch over 5 feet for females", why:"Ideal body weight equations provide a standardized reference that is often encountered in clinical and educational settings", interpretation:"The Devine equation is a formula-based reference, not a universal definition of an ideal or attractive body. It should not override body composition, athletic build, age, health conditions, or a clinician's assessment.", accuracy:"Formula-based IBW is an estimate and can differ substantially from an individual's healthiest or most appropriate weight.", mistakes:"Do not treat IBW as a mandatory goal weight, and be careful when applying the equation outside the population or purpose for which it was designed.", use:"learning how clinical weight equations work, comparing weight references, and understanding why different ideal-weight formulas can disagree", related:["Healthy Weight Range Calculator","BMI Calculator","Adjusted Body Weight Calculator"] },
  "weight-loss-goal": { name:"Weight Loss Goal Calculator", what:"the approximate amount of weight to lose and a planning timeline under an assumed rate", inputs:"current weight, goal weight, and the calculator's assumed rate or deficit", formula:"goal loss = current weight − goal weight; estimated time = goal loss ÷ assumed weekly loss", why:"A clear target can turn a vague weight-loss intention into a measurable plan", interpretation:"The timeline is a planning estimate. Real weight change is nonlinear because water, glycogen, food mass, energy expenditure, adherence, and body composition all change over time.", accuracy:"No simple calculator can predict an exact date for reaching a goal weight. Actual progress should be evaluated from multi-week trends rather than individual scale readings.", mistakes:"Avoid assuming every kilogram of scale change is body fat and avoid using an aggressive deficit without considering nutritional adequacy and individual circumstances.", use:"setting realistic milestones, estimating a broad timeline, and monitoring progress while adjusting a plan based on real-world results", related:["Calorie Deficit Calculator","TDEE Calculator","Daily Calorie Needs Calculator","BMI Calculator"] },
  "weight-gain-goal": { name:"Weight Gain Goal Calculator", what:"the approximate amount of weight to gain and a planning timeline", inputs:"current weight, target weight, and the assumed gain rate", formula:"weight to gain = target weight − current weight; estimated time = weight to gain ÷ assumed weekly gain", why:"A target and timeline can make a weight-gain phase more measurable", interpretation:"Scale weight gained during a surplus can include muscle, fat, glycogen, water, and food mass. The calculator therefore estimates total weight change rather than guaranteed muscle gain.", accuracy:"The predicted timeline is approximate because energy needs, training response, appetite, and body composition vary between people.", mistakes:"Do not equate rapid scale gain with rapid muscle gain, and do not assume a fixed calorie surplus will create the same rate indefinitely.", use:"planning a gradual gain phase, tracking progress, and combining nutrition targets with resistance training", related:["Calorie Surplus Calculator","TDEE Calculator","Lean Body Mass Calculator","FFMI Calculator"] },
  "body-fat": { name:"Body Fat Percentage Calculator", what:"an estimated body-fat percentage from BMI, age, and sex using the Deurenberg equation", inputs:"BMI, age, and sex category", formula:"Deurenberg estimate = 1.20 × BMI + 0.23 × age − 10.8 × sex code − 5.4", why:"Body-fat percentage can add context that BMI alone cannot provide", interpretation:"Body-fat percentage estimates should be viewed as ranges and trends rather than exact measurements. The relationship between BMI and body fat varies between individuals and populations.", accuracy:"Prediction equations have population-level error and can be less accurate for athletes, older adults, very lean people, and people with unusual body composition.", mistakes:"Do not compare an equation estimate directly with a DXA or laboratory result as though they were interchangeable measurements.", use:"tracking broad body-composition trends and deciding whether a waist or direct body-composition method would add useful information", related:["Navy Body Fat Calculator","Relative Fat Mass Calculator","Fat Mass Calculator","Fat-Free Mass Calculator"] },
  "navy-body-fat": { name:"US Navy Body Fat Calculator", what:"an estimated body-fat percentage from height and circumference measurements", inputs:"height, waist, neck, and for the female equation, hip circumference", formula:"the US Navy circumference equations use logarithms of measured circumferences and height", why:"Tape measurements are inexpensive and can provide a practical estimate when direct body-composition testing is unavailable", interpretation:"The result is an estimate and measurement technique matters greatly. Waist location, tape tension, posture, and clothing can change the result.", accuracy:"Circumference equations can have meaningful individual error and should not be presented as equivalent to a clinical body-composition scan.", mistakes:"Use a flexible tape, keep it level, avoid compressing the skin, and measure consistently at the specified anatomical locations.", use:"home body-composition tracking, fitness progress monitoring, and comparing changes over time under consistent measurement conditions", related:["Body Fat Calculator","Relative Fat Mass Calculator","Waist-to-Height Ratio Calculator"] },
  "relative-fat-mass": { name:"Relative Fat Mass Calculator", what:"an estimated body-fat percentage from height, waist circumference, and sex", inputs:"height, waist circumference, and sex category", formula:"RFM uses a height-to-waist relationship with a sex-specific adjustment", why:"RFM attempts to capture body size and central adiposity with fewer inputs than many body-fat equations", interpretation:"RFM is an estimate, not a direct measurement of adipose tissue. Its usefulness depends on the population and measurement quality.", accuracy:"Research has found useful associations between RFM and body fat, but individual estimates can still differ from direct methods.", mistakes:"Do not change the waist measurement location between readings and do not assume a single RFM number defines health.", use:"screening and trend tracking when height and waist are readily available", related:["Navy Body Fat Calculator","Body Fat Calculator","Waist-to-Height Ratio Calculator"] },
  "body-adiposity-index": { name:"Body Adiposity Index Calculator", what:"an estimated adiposity index from hip circumference and height", inputs:"hip circumference and height", formula:"BAI = hip circumference / height^1.5 − 18", why:"BAI is an alternative body-size measure that does not require body weight", interpretation:"BAI is intended as an estimate and can behave differently from BMI because it relies on hip size and height. It should not be interpreted as an exact body-fat measurement.", accuracy:"Performance varies across populations, and individual estimates can differ from measured body fat.", mistakes:"Use the same units consistently and measure the hip at the widest practical point according to the method used by the calculator.", use:"exploring alternative adiposity measures and comparing body-size indicators", related:["Body Fat Calculator","Relative Fat Mass Calculator","BMI Calculator"] },
  "lean-body-mass": { name:"Lean Body Mass Calculator", what:"an estimate of fat-free or lean body mass using a height-and-weight equation", inputs:"height, weight, and sex category used by the selected equation", formula:"the Boer equation estimates lean body mass from height and body weight with sex-specific coefficients", why:"Lean mass provides context that total body weight alone cannot provide", interpretation:"Lean body mass includes water, organs, bone, connective tissue, and muscle rather than muscle alone. It should not be treated as a direct measurement of skeletal muscle.", accuracy:"Equation-based lean mass is approximate and can vary from direct body-composition methods.", mistakes:"Do not label all lean mass as muscle and do not compare results from different equations without noting the method.", use:"fitness tracking, body-composition education, and understanding how weight can be separated conceptually into fat and non-fat mass", related:["Fat-Free Mass Calculator","Fat Mass Calculator","FFMI Calculator","BMR Calculator"] },
  "fat-mass": { name:"Fat Mass Calculator", what:"estimated kilograms or pounds of body fat from body weight and body-fat percentage", inputs:"body weight and body-fat percentage", formula:"fat mass = body weight × body-fat percentage / 100", why:"Separating fat mass from total body weight can make body-composition changes easier to understand", interpretation:"Fat mass is only as accurate as the body-fat estimate supplied to the calculation. If body-fat percentage is estimated, the resulting fat mass is also estimated.", accuracy:"Errors in body-fat percentage are carried directly into the fat-mass result.", mistakes:"Do not mix kilograms with pounds, and do not assume changes in fat mass are exact when the underlying body-fat estimate is approximate.", use:"tracking body-composition trends, comparing fat and lean compartments, and setting more informative fitness goals", related:["Body Fat Calculator","Fat-Free Mass Calculator","Lean Body Mass Calculator"] },
  "fat-free-mass": { name:"Fat-Free Mass Calculator", what:"estimated body mass excluding fat", inputs:"body weight and body-fat percentage", formula:"fat-free mass = body weight × (1 − body-fat percentage / 100)", why:"Fat-free mass helps explain why two people with the same body weight can have very different body compositions", interpretation:"Fat-free mass includes muscle, water, bone, organs, connective tissue, and other non-fat components. It is not synonymous with muscle mass.", accuracy:"The estimate depends on the accuracy of the body-fat percentage and body weight.", mistakes:"Do not compare estimates from different body-fat methods without noting the method, and do not interpret short-term hydration changes as muscle gain.", use:"tracking lean-versus-fat trends, estimating FFMI, and understanding changes during weight loss or gain", related:["Fat Mass Calculator","Lean Body Mass Calculator","FFMI Calculator"] },
  ffmi: { name:"Fat-Free Mass Index Calculator", what:"fat-free mass normalized to height", inputs:"fat-free mass and height", formula:"FFMI = fat-free mass in kg / height in meters²", why:"FFMI puts lean mass into a height-adjusted index that can be useful for comparing people of different heights", interpretation:"FFMI is an index of fat-free mass, not a direct measure of muscle quality, strength, athletic performance, or health.", accuracy:"Because FFMI depends on estimated fat-free mass, errors in body-fat estimation can affect the result.", mistakes:"Do not use a single FFMI value as proof of natural or enhanced status, and avoid treating published reference ranges as universal limits.", use:"fitness tracking, comparing lean-mass trends, and studying the relationship between height and fat-free mass", related:["Fat-Free Mass Calculator","Lean Body Mass Calculator","Body Fat Calculator"] },
  "waist-hip-ratio": { name:"Waist-to-Hip Ratio Calculator", what:"the ratio of waist circumference to hip circumference", inputs:"waist and hip circumferences", formula:"WHR = waist circumference / hip circumference", why:"WHR describes where body mass is distributed rather than only how much a person weighs", interpretation:"Higher waist relative to hip circumference is generally associated with greater central adiposity. Reference thresholds vary by sex, age, population, and guideline.", accuracy:"Measurement technique and anatomical location strongly influence the ratio.", mistakes:"Measure waist and hip consistently, keep the tape level, and do not compare readings taken at different anatomical sites.", use:"tracking fat distribution and adding context to BMI and total body weight", related:["Waist-to-Height Ratio Calculator","ABSI Calculator","BMI Calculator"] },
  "waist-height-ratio": { name:"Waist-to-Height Ratio Calculator", what:"the ratio of waist circumference to height", inputs:"waist circumference and height", formula:"WHtR = waist circumference / height using the same units", why:"The measure relates waist size to body height and is often used as a simple indicator of central adiposity", interpretation:"A commonly discussed rule of thumb is keeping waist below half of height, but thresholds can vary and the measure is not a diagnosis.", accuracy:"It depends on consistent waist measurement and the reference population used for interpretation.", mistakes:"Use the same unit for waist and height and measure the waist at a consistent location.", use:"screening central adiposity, monitoring waist changes, and complementing BMI", related:["Waist-to-Hip Ratio Calculator","ABSI Calculator","BMI Calculator"] },
  absi: { name:"A Body Shape Index Calculator", what:"a waist-based body-shape index adjusted for BMI and height", inputs:"waist circumference, BMI, and height", formula:"ABSI = waist / (BMI^(2/3) × height^(1/2))", why:"ABSI was designed to capture waist size relative to overall body size", interpretation:"ABSI is mainly a statistical risk-related index. There is no single value that diagnoses disease or determines an individual's future health.", accuracy:"Its associations depend on population, age, sex, and measurement quality.", mistakes:"Keep waist, height, and BMI units consistent and do not interpret the index outside its intended statistical context.", use:"exploring central body shape and comparing waist size after accounting for BMI and height", related:["Waist-to-Height Ratio Calculator","BRI Calculator","BMI Calculator"] },
  bri: { name:"Body Roundness Index Calculator", what:"a body-roundness index derived primarily from waist and height", inputs:"waist circumference and height", formula:"BRI uses an equation based on waist-to-height geometry to produce a roundness index", why:"BRI provides another way to describe central body shape beyond BMI", interpretation:"BRI is a continuous index rather than a universal disease cutoff. Reference distributions differ by population and age.", accuracy:"It is sensitive to the quality and location of waist measurement and should be interpreted with other health information.", mistakes:"Do not compare BRI values from inconsistent waist measurements or assume that a universal 'normal' number applies to everyone.", use:"tracking central body shape and exploring alternatives to BMI", related:["ABSI Calculator","Waist-to-Height Ratio Calculator","Conicity Index Calculator"] },
  "conicity-index": { name:"Conicity Index Calculator", what:"a waist-to-body-shape index related to central fat distribution", inputs:"waist, weight, and height", formula:"Conicity Index compares measured waist with a weight-and-height-based reference circumference", why:"It attempts to describe whether body shape is relatively more concentrated around the abdomen", interpretation:"Higher values generally indicate a more centrally concentrated body shape, but interpretation depends on reference population and measurement method.", accuracy:"The index is sensitive to circumference measurement and is not a diagnostic test.", mistakes:"Use consistent metric units and measure waist at the same anatomical location each time.", use:"studying abdominal body shape and complementing other anthropometric measures", related:["Waist-to-Hip Ratio Calculator","Waist-to-Height Ratio Calculator","BRI Calculator"] },
  "body-frame-size": { name:"Body Frame Size Calculator", what:"an estimated small, medium, or large body frame from height and wrist circumference", inputs:"height, wrist circumference, and sex category", formula:"frame size is estimated from a height-to-wrist relationship using sex-specific reference thresholds", why:"Frame size can explain some variation in body weight that BMI alone cannot", interpretation:"Frame size is a rough anthropometric classification. It does not determine a person's health, muscle mass, or ideal body weight by itself.", accuracy:"Thresholds vary between methods and populations, so treat the classification as approximate.", mistakes:"Measure the wrist consistently and do not treat frame size as a reason to ignore body-fat or waist measurements.", use:"understanding body proportions and adding context to ideal-weight or BMI estimates", related:["Ideal Body Weight Calculator","Healthy Weight Range Calculator","BMI Calculator"] },
  bmr: { name:"BMR Calculator", what:"basal metabolic rate, the estimated energy required to support essential functions at rest", inputs:"age, sex category, height, and body weight", formula:"Mifflin-St Jeor: male = 10W + 6.25H − 5A + 5; female = 10W + 6.25H − 5A − 161", why:"BMR is the starting point for estimating daily energy needs", interpretation:"BMR is not the same as total calories burned in a normal day. Walking, exercise, work, digestion, and ordinary movement increase total energy expenditure above BMR.", accuracy:"Equations estimate average resting needs and cannot precisely measure an individual's metabolism.", mistakes:"Do not eat exactly at BMR as a maintenance target; use TDEE or another appropriate energy estimate for daily planning.", use:"estimating energy needs, building a calorie plan, and understanding the relationship between resting metabolism and TDEE", related:["TDEE Calculator","Daily Calorie Needs Calculator","Calorie Deficit Calculator"] },
  tdee: { name:"TDEE Calculator", what:"total daily energy expenditure from estimated BMR and activity", inputs:"age, sex category, height, weight, and activity level", formula:"TDEE = estimated BMR × activity factor", why:"TDEE converts a resting metabolic estimate into a broader daily calorie estimate", interpretation:"TDEE is a starting estimate. Actual expenditure changes with movement, exercise, body weight, training, occupation, and day-to-day activity.", accuracy:"The activity multiplier is a major source of uncertainty, so real-world weight trends are useful for adjusting an initial estimate.", mistakes:"Do not assume a single activity category is perfectly accurate or add every exercise calorie on top without considering what the multiplier already represents.", use:"maintenance-calorie planning, weight-loss planning, weight-gain planning, and adjusting nutrition targets", related:["BMR Calculator","Daily Calorie Needs Calculator","Calorie Deficit Calculator","Calorie Surplus Calculator"] },
  "daily-calorie-needs": { name:"Daily Calorie Needs Calculator", what:"an estimate of calories needed to maintain current weight based on estimated energy expenditure", inputs:"age, sex category, height, weight, and activity level", formula:"daily maintenance calories are estimated from BMR and an activity factor", why:"Knowing an approximate maintenance intake provides a reference for weight loss, maintenance, or gain", interpretation:"Maintenance calories are not fixed. They can change as body weight, activity, training, occupation, and routine change.", accuracy:"The result is an estimate; several weeks of weight trends can help determine whether the starting estimate is close to reality.", mistakes:"Avoid changing targets because of one day's scale reading and avoid treating the estimate as a prescription.", use:"meal planning, maintenance tracking, calorie-deficit planning, and calorie-surplus planning", related:["BMR Calculator","TDEE Calculator","Calorie Deficit Calculator","Calorie Surplus Calculator"] },
  "calorie-deficit": { name:"Calorie Deficit Calculator", what:"a planning calorie target below estimated maintenance energy needs", inputs:"estimated maintenance calories and chosen deficit", formula:"target intake = estimated TDEE − chosen calorie deficit", why:"A calorie deficit is the basic energy-balance concept behind planned weight loss", interpretation:"A deficit means energy intake is below estimated expenditure. The amount of scale-weight change varies and is not a fixed conversion from calories to kilograms.", accuracy:"The result depends on the accuracy of TDEE and the assumption that the selected deficit is appropriate for the individual.", mistakes:"Avoid very aggressive restriction, do not ignore hunger or nutritional adequacy, and reassess targets as body weight changes.", use:"creating a starting calorie target for gradual weight loss and adjusting a plan using real-world progress", related:["TDEE Calculator","Weight Loss Goal Calculator","Daily Calorie Needs Calculator"] },
  "calorie-surplus": { name:"Calorie Surplus Calculator", what:"a planning calorie target above estimated maintenance energy needs", inputs:"estimated maintenance calories and chosen surplus", formula:"target intake = estimated TDEE + chosen calorie surplus", why:"A modest surplus can support weight gain when combined with adequate nutrition and, for muscle gain, resistance training", interpretation:"A calorie surplus increases energy availability but does not guarantee that all added weight will be muscle. The rate of gain and body composition should be monitored.", accuracy:"The estimate depends on TDEE accuracy and the individual's response to the chosen surplus.", mistakes:"Do not assume a larger surplus produces proportionally more muscle and do not ignore changes in body-fat or waist measurements.", use:"planning a controlled weight-gain phase, supporting resistance training, and monitoring total weight trends", related:["TDEE Calculator","Weight Gain Goal Calculator","Lean Body Mass Calculator"] },
  "body-surface-area": { name:"Body Surface Area Calculator", what:"an estimated body surface area from height and weight", inputs:"height and weight", formula:"Mosteller BSA = √((height in cm × weight in kg) / 3600)", why:"BSA is used in some clinical calculations and provides a standardized estimate of external body surface", interpretation:"BSA is a mathematical estimate, not a direct measurement. Clinical uses should follow the specific protocol and equation chosen by a healthcare professional.", accuracy:"Different BSA equations can produce slightly different values, especially at unusual body sizes.", mistakes:"Use centimeters and kilograms for the Mosteller equation and do not substitute BSA for a clinician's prescribed dosing calculation.", use:"educational understanding of clinical formulas and situations where a validated BSA estimate is required", related:["BMI Calculator","BMR Calculator","Adjusted Body Weight Calculator"] },
  "ponderal-index": { name:"Ponderal Index Calculator", what:"an index relating body weight to height cubed", inputs:"height and weight", formula:"Ponderal Index = weight in kg / height in meters³", why:"Ponderal Index can describe body proportionality and is related to BMI but uses height cubed", interpretation:"It is primarily a body-size index. Interpretation depends on age and population, and adult reference values should not be automatically applied to children.", accuracy:"As with BMI, it does not distinguish fat mass from lean tissue or assess health on its own.", mistakes:"Use consistent metric units and do not confuse the cubic-height denominator with BMI's squared-height denominator.", use:"studying body proportionality and comparing alternative weight-to-height indices", related:["BMI Calculator","Healthy Weight Range Calculator","Body Frame Size Calculator"] },
  "adjusted-body-weight": { name:"Adjusted Body Weight Calculator", what:"an adjusted weight estimate that modifies actual body weight using an ideal-body-weight reference", inputs:"actual body weight and ideal body weight", formula:"Adjusted body weight = IBW + adjustment factor × (actual weight − IBW)", why:"Adjusted weight equations are encountered in some clinical contexts where actual and ideal weight differ substantially", interpretation:"The adjustment factor and intended clinical use matter. This calculator is educational and should not be used to determine medication doses without professional guidance.", accuracy:"Different clinical protocols use different equations and adjustment factors.", mistakes:"Do not use a generic adjusted-weight result as a medication prescription and always verify the formula required by the relevant clinical protocol.", use:"understanding adjusted-weight equations and learning why clinical calculations sometimes use more than one weight reference", related:["Ideal Body Weight Calculator","BMI Calculator","Body Surface Area Calculator"] },
  "body-density": { name:"Body Density Calculator", what:"an estimated body density from body mass and body volume or from an applicable body-composition method", inputs:"the measurements required by the selected density equation", formula:"density = mass / volume; body-composition equations may use density to estimate fat and fat-free compartments", why:"Body density is a foundational concept in several body-composition methods", interpretation:"Density itself is not body-fat percentage. Converting density into body-fat estimates requires additional assumptions about the density of fat and fat-free tissue.", accuracy:"Results depend heavily on the measurement method and assumptions used to estimate body volume and tissue composition.", mistakes:"Do not interpret density as a direct body-fat measurement and do not mix units when calculating mass divided by volume.", use:"learning body-composition science, understanding hydrostatic or volumetric methods, and studying the relationship between density and body fat", related:["Body Fat Calculator","Fat-Free Mass Calculator","Body Surface Area Calculator"] },
  "obesity-class": { name:"Obesity Class Calculator", what:"the adult obesity class associated with a BMI value", inputs:"height and weight", formula:"BMI = weight / height², followed by adult BMI obesity-class thresholds", why:"Obesity classes provide a standardized screening vocabulary for higher BMI values", interpretation:"For adults, BMI 30.0–34.9 is commonly classified as class 1 obesity, 35.0–39.9 as class 2, and 40 or above as class 3. BMI is a screening measure and does not directly measure body fat or diagnose a health condition.", accuracy:"Classification inherits BMI's limitations and may not reflect body composition or individual health risk.", mistakes:"Do not treat an obesity class as a complete medical assessment and do not apply adult BMI categories to children without age- and sex-specific interpretation.", use:"understanding BMI terminology, preparing for clinical discussions, and identifying when additional assessment may be appropriate", related:["BMI Calculator","Body Fat Calculator","Waist-to-Height Ratio Calculator","Healthy Weight Range Calculator"] },
};

function fill(text, c) {
  return text.replaceAll("{name}", c.name).replaceAll("{what}", c.what).replaceAll("{inputs}", c.inputs).replaceAll("{formula}", c.formula);
}

function paragraphs(c) {
  return [
    `${c.name} is designed to make a commonly used fitness or body-composition calculation easier to understand. The number produced by a formula can be useful because it turns several measurements into a consistent reference point. At the same time, a calculated result should be treated as an estimate rather than a direct measurement of health. The most useful interpretation combines the number with the person's age, sex, body composition, activity, medical context, and the quality of the measurements entered.`,
    `${c.why}. That is why this page explains not only the result but also the assumptions behind the calculation. A formula can be mathematically correct while still being an imperfect description of an individual. Population equations summarize relationships observed in groups; they cannot account for every difference in muscle mass, fat distribution, hydration, genetics, training status, or medical history.`,
    `The first step is obtaining consistent inputs. ${c.inputs.charAt(0).toUpperCase()+c.inputs.slice(1)} should be measured or recorded carefully. If you are tracking changes, use similar conditions each time: similar time of day, the same scale or tape, the same measurement location, and similar posture. Consistency is often more important for trend tracking than trying to make one measurement look unusually precise.`,
    `The mathematical method used here is ${c.formula}. The calculation is deterministic: if the same inputs are entered, the same formula will produce the same result. This makes the calculator useful for education and repeat tracking. It does not, however, make the underlying estimate more accurate than the equation itself. Different calculators may use different formulas and therefore return different values from the same person.`,
    `How should the result be interpreted? ${c.interpretation} If your value is close to a boundary, avoid treating a small numerical difference as a dramatic change in health status. Reference categories are useful for communication and screening, but they are not a substitute for a complete assessment.`,
    `Accuracy is an important part of using any health calculator. ${c.accuracy} Measurement error can also be larger than the number of decimal places shown on a screen. Reporting a result to two decimal places does not mean the person's physiology is known to two-decimal-place precision. Use the calculator to identify useful patterns and questions, not to create false certainty.`,
    `Common measurement mistakes can make a result look more meaningful than it really is. ${c.mistakes} Unit conversion is especially important. A height entered in centimeters where meters are expected can create an extreme result, while mixing kilograms and pounds can produce a plausible-looking but incorrect number. Always check the input labels before interpreting the output.`,
    `For fitness planning, ${c.use}. A calculator is most useful when it becomes part of a feedback loop: calculate a starting estimate, apply a reasonable plan, observe the real-world trend, and adjust when the evidence shows that the original estimate was not a good match. This is more reliable than repeatedly changing a target because of a single day's result.`,
    `Related measurements can provide context. ${c.related.join(", ")} do not measure exactly the same thing, so disagreement between them is not automatically an error. BMI describes weight relative to height; waist-based measures describe fat distribution; body-fat equations estimate composition; calorie equations estimate energy needs. Looking at several relevant measures can provide a fuller picture than relying on one number.`,
    `When using this calculator for personal goals, focus on sustainable behavior and trends. Sleep, nutrition quality, resistance training, cardiovascular activity, daily movement, hydration, and stress can all affect body weight and performance. A calculator can organize information, but it cannot decide which goal is appropriate for a particular person.`,
    `It is also worth remembering that body weight and body measurements naturally fluctuate. Water retention, glycogen, food volume, bowel contents, menstrual-cycle changes, sodium intake, exercise-induced inflammation, and measurement technique can move the scale or tape without representing a comparable change in body fat. Longer trends are generally more informative than isolated readings.`,
    `For health-related decisions, context matters. A calculated value that is unexpectedly high or low, changes rapidly without an obvious explanation, or is being used alongside a medical condition deserves professional interpretation. The calculator is an educational tool and should not be used to diagnose disease, prescribe treatment, or determine medication dosing unless a qualified professional specifically directs how the calculation should be used.`,
  ];
}

export function getLongFormContent(slug) {
  const c = TOPICS[slug];
  if (!c) return null;
  const sections = paragraphs(c);
  const faqs = BASE_FAQS.map(([q,a]) => ({ q: fill(q,c), a: fill(a,c) }));
  return { ...c, sections, faqs };
}

export const LONG_FORM_SLUGS = Object.keys(TOPICS);
