import { toMetric, getActivityFactor, formatNumber } from "./units";

const out = (value, unit = "", category = "", interpretation = "") => ({ value: typeof value === "number" ? formatNumber(value, 1) : value, raw: typeof value === "number" ? value : undefined, unit, category, tone: "good", interpretation });
const field = (name, label, value) => ({ name, label, default: String(value) });
const extra = (id, name, category, description, formula, inputFields, computeExtra) => ({ id, slug: id, name, category, requires: [], description, formula, extraInputs: true, inputFields, computeExtra });
const shared = (id, name, category, description, formula, requires, compute) => ({ id, slug: id, name, category, description, formula, requires, compute });
const n = (v, k, d = 0) => Number.isFinite(+v?.[k]) ? +v[k] : d;
const m = (s) => toMetric(s);
const bmi = (x) => x.weightKg / Math.pow(x.heightCm / 100, 2);
const bodyFat = (x) => 1.2 * bmi(x) + 0.23 * x.age - (x.sex === "male" ? 10.8 : 0) - 5.4;
const lean = (x) => x.sex === "male" ? 0.407 * x.weightKg + 0.267 * x.heightCm - 19.2 : 0.252 * x.weightKg + 0.473 * x.heightCm - 48.3;
const bmr = (x) => 10 * x.weightKg + 6.25 * x.heightCm - 5 * x.age + (x.sex === "male" ? 5 : -161);
const tdee = (x) => bmr(x) * getActivityFactor(x.activity);
const riegel = (v, target) => (n(v,"minutes") + n(v,"seconds") / 60) * Math.pow(target / n(v,"distance",1), 1.06);
const epley = (v) => n(v,"load") * (1 + Math.min(30, n(v,"reps")) / 30);
const timeHours = (v) => (n(v,"minutes") * 60 + n(v,"seconds")) / 3600;
const MET = { walking: 3.5, running: 8.3, cycling: 7.5 };

export const NEW_CALCULATORS = [
  shared("fmi-calculator","Fat Mass Index (FMI) Calculator","Body Composition","Estimate fat mass relative to height squared.","FMI = fat mass ÷ height²",["height","weight","age","sex"],s=>{const x=m(s),fm=x.weightKg*bodyFat(x)/100;return out(fm/Math.pow(x.heightCm/100,2),"kg/m²","Estimated FMI","FMI is an estimate derived from body-fat estimation and is not a direct measurement.");}),
  shared("total-body-water-calculator","Total Body Water Calculator","Body Composition","Estimate total body water using the Watson equation.","Watson TBW equation using age, sex, height and weight",["height","weight","age","sex"],s=>{const x=m(s),tbw=x.sex==="male"?2.447-.09516*x.age+.1074*x.heightCm+.3362*x.weightKg:2.097-.1069*x.age+.2466*x.heightCm+.2466*x.weightKg;return out(tbw,"L","Estimated total body water","Population estimate; hydration status and body composition affect actual total body water.");}),
  shared("skeletal-muscle-mass-calculator","Skeletal Muscle Mass Calculator","Body Composition","Estimate skeletal muscle mass from estimated lean body mass.","Skeletal muscle mass ≈ 50% of estimated lean body mass",["height","weight","age","sex"],s=>out(lean(m(s))*.5,"kg","Estimated skeletal muscle mass","Rough population estimate, not a direct measurement.")),

  extra("target-weight-calculator","Target Weight Calculator","Weight, BMI & Weight Goals","Calculate the selected target weight.","Target weight = selected goal weight",[field("currentWeight","Current weight / kg",85),field("targetWeight","Target weight / kg",75)],v=>out(n(v,"targetWeight"),"kg","Target weight","A goal weight is a planning value, not a universal ideal.")),
  extra("target-weight-by-bmi-calculator","Target Weight by BMI Calculator","Weight, BMI & Weight Goals","Calculate the weight corresponding to a selected BMI and height.","Weight = target BMI × height²",[field("height","Height / cm",175),field("targetBMI","Target BMI",22)],v=>out(n(v,"targetBMI")*Math.pow(n(v,"height")/100,2),"kg","Weight at target BMI","BMI is a screening measure and does not directly measure body fat.")),
  extra("weight-loss-percentage-calculator","Weight Loss Percentage Calculator","Weight, BMI & Weight Goals","Calculate percentage of starting body weight lost.","Loss % = (starting − current) ÷ starting × 100",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",80)],v=>out((n(v,"startWeight")-n(v,"currentWeight"))/n(v,"startWeight")*100,"%","Weight loss","Calculated from starting body weight.")),
  extra("weight-gain-percentage-calculator","Weight Gain Percentage Calculator","Weight, BMI & Weight Goals","Calculate percentage of starting body weight gained.","Gain % = (current − starting) ÷ starting × 100",[field("startWeight","Starting weight / kg",70),field("currentWeight","Current weight / kg",75)],v=>out((n(v,"currentWeight")-n(v,"startWeight"))/n(v,"startWeight")*100,"%","Weight gain","Calculated from starting body weight.")),
  extra("weight-change-calculator","Weight Change Calculator","Weight, BMI & Weight Goals","Calculate absolute and percentage weight change.","Change = current − starting",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",82)],v=>{const d=n(v,"currentWeight")-n(v,"startWeight");return out(`${d.toFixed(1)} kg (${(d/n(v,"startWeight")*100).toFixed(1)}%)`,"","Weight change","Negative values indicate weight loss; positive values indicate weight gain.");}),
  extra("weight-loss-timeline-calculator","Weight Loss Timeline Calculator","Weight, BMI & Weight Goals","Estimate time to lose a selected amount of weight at a chosen deficit.","Weeks ≈ weight to lose × 7,700 ÷ daily deficit ÷ 7",[field("weightToLose","Weight to lose / kg",5),field("dailyDeficit","Daily deficit / kcal",500)],v=>out(n(v,"weightToLose")*7700/n(v,"dailyDeficit")/7,"weeks","Estimated timeline","7,700 kcal/kg is a simplified energy-equivalence estimate; actual weight change is not linear.")),
  extra("goal-weight-date-calculator","Goal Weight Date Calculator","Weight, BMI & Weight Goals","Estimate the date of reaching a goal weight at a chosen weekly rate.","Weeks = weight to lose ÷ weekly rate",[field("currentWeight","Current weight / kg",85),field("goalWeight","Goal weight / kg",75),field("weeklyRate","Weekly loss / kg",.5)],v=>{const days=Math.max(0,(n(v,"currentWeight")-n(v,"goalWeight"))/n(v,"weeklyRate")*7);return out(new Date(Date.now()+days*86400000).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}),"","Estimated goal date","Assumes the selected weekly rate remains constant.");}),
  extra("weekly-weight-loss-calculator","Weekly Weight Loss Calculator","Weight, BMI & Weight Goals","Estimate weekly weight change from a daily calorie deficit.","Weekly loss ≈ daily deficit × 7 ÷ 7,700",[field("dailyDeficit","Daily deficit / kcal",500)],v=>out(n(v,"dailyDeficit")*7/7700,"kg/week","Estimated weekly loss","Energy-equivalence estimate, not a guarantee of scale change.")),
  extra("calories-to-lose-1-kg-calculator","Calories to Lose 1 kg Calculator","Weight, BMI & Weight Goals","Show a simplified energy equivalent for 1 kg of body-mass loss.","Approximate energy equivalent ≈ 7,700 kcal/kg",[],()=>out(7700,"kcal","Approximate energy equivalent","Actual energy requirements vary and body weight change is not purely fat loss.")),
  extra("calories-to-gain-1-kg-calculator","Calories to Gain 1 kg Calculator","Weight, BMI & Weight Goals","Show a simplified energy equivalent for 1 kg of body-mass gain.","Simplified energy estimate ≈ 7,700 kcal/kg",[],()=>out(7700,"kcal","Approximate energy equivalent","Actual gain depends on the tissue gained and energy expenditure.")),

  shared("maintenance-calories-calculator","Maintenance Calories Calculator","Calories & Metabolism","Estimate daily maintenance calories from BMR and activity.","Maintenance = BMR × activity factor",["height","weight","age","sex","activity"],s=>out(tdee(m(s)),"kcal/day","Estimated maintenance","Actual energy needs vary from day to day.")),
  shared("weight-loss-calorie-calculator","Weight Loss Calorie Calculator","Calories & Metabolism","Estimate a starting calorie target using a moderate deficit.","Weight-loss target = estimated TDEE − 500 kcal/day",["height","weight","age","sex","activity"],s=>out(Math.max(0,tdee(m(s))-500),"kcal/day","Estimated weight-loss intake","A moderate deficit is a planning estimate; individual needs vary.")),
  shared("weight-gain-calorie-calculator","Weight Gain Calorie Calculator","Calories & Metabolism","Estimate a starting calorie target using a modest surplus.","Weight-gain target = estimated TDEE + 300 kcal/day",["height","weight","age","sex","activity"],s=>out(tdee(m(s))+300,"kcal/day","Estimated weight-gain intake","A modest surplus is a planning estimate; actual needs vary.")),
  extra("exercise-calorie-calculator","Exercise Calorie Calculator","Calories & Metabolism","Estimate exercise energy expenditure from MET, body weight and duration.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("met","Exercise MET",6),field("minutes","Duration / min",45)],v=>out(n(v,"met")*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated exercise calories","MET-based estimate; actual energy expenditure varies.")),
  extra("walking-calorie-calculator","Walking Calorie Calculator","Calories & Metabolism","Estimate calories burned during walking.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Walking duration / min",60)],v=>out(MET.walking*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated walking calories","Walking intensity, terrain and speed affect actual expenditure.")),
  extra("running-calorie-calculator","Running Calorie Calculator","Calories & Metabolism","Estimate calories burned during running.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Running duration / min",30)],v=>out(MET.running*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated running calories","Running speed, terrain and fitness affect actual expenditure.")),
  extra("cycling-calorie-calculator","Cycling Calorie Calculator","Calories & Metabolism","Estimate calories burned during cycling.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Cycling duration / min",45)],v=>out(MET.cycling*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated cycling calories","Cycling intensity, terrain and equipment affect actual expenditure.")),
  extra("reverse-diet-calculator","Reverse Diet Calculator","Calories & Metabolism","Estimate the number of planned weekly calorie increases needed to reach a target intake.","Weeks = calorie gap ÷ weekly increase",[field("currentCalories","Current intake / kcal",1800),field("targetCalories","Target intake / kcal",2400),field("weeklyIncrease","Weekly increase / kcal",100)],v=>out(Math.max(0,Math.ceil((n(v,"targetCalories")-n(v,"currentCalories"))/Math.max(1,n(v,"weeklyIncrease")))),"weeks","Planned calorie increases","Reverse dieting is a planning approach, not a proven way to permanently increase metabolic rate.")),
  extra("calorie-per-meal-calculator","Calorie per Meal Calculator","Calories & Metabolism","Divide a daily calorie target across meals.","Calories per meal = daily calories ÷ meals",[field("dailyCalories","Daily calories / kcal",2400),field("meals","Meals per day",4)],v=>out(n(v,"dailyCalories")/Math.max(1,n(v,"meals")),"kcal/meal","Meal calorie target","Meal distribution can be adjusted to preference and schedule.")),

  shared("protein-per-meal-calculator","Protein per Meal Calculator","Nutrition & Macronutrients","Divide a practical daily protein target across meals.","Protein per meal = daily protein ÷ meals",["weight","activity"],s=>{const x=m(s),factor={sedentary:1.2,light:1.4,moderate:1.6,active:1.7,very_active:1.8}[x.activity]||1.6;return out(x.weightKg*factor/4,"g/meal","Protein distribution","Uses an activity-based protein planning target.");}),
  extra("protein-to-calorie-ratio-calculator","Protein-to-Calorie Ratio Calculator","Nutrition & Macronutrients","Calculate protein grams per 100 calories.","Protein density = protein ÷ calories × 100",[field("protein","Protein / g",30),field("calories","Calories",300)],v=>out(n(v,"protein")/Math.max(1,n(v,"calories"))*100,"g/100 kcal","Protein density","Higher values indicate more protein relative to energy.")),
  shared("macronutrient-calculator","Macronutrient Calculator","Nutrition & Macronutrients","Estimate daily protein, carbohydrate and fat targets from calorie needs.","Protein ≈ 1.6 g/kg; fat ≈ 25% calories; carbs fill remaining calories",["height","weight","age","sex","activity"],s=>{const x=m(s),k=tdee(x),p=x.weightKg*1.6,f=k*.25/9,c=Math.max(0,(k-p*4-f*9)/4);return out(`P ${Math.round(p)}g · C ${Math.round(c)}g · F ${Math.round(f)}g`,"/day","Estimated macro targets","Starting macro estimate; individual nutrition needs vary.");}),
  extra("macro-percentage-calculator","Macro Percentage Calculator","Nutrition & Macronutrients","Convert macro grams into calorie percentages.","Protein/carbohydrate = g×4; fat = g×9",[field("protein","Protein / g",150),field("carbs","Carbohydrate / g",250),field("fat","Fat / g",70)],v=>{const p=n(v,"protein")*4,c=n(v,"carbs")*4,f=n(v,"fat")*9,t=p+c+f;return out(`P ${Math.round(p/t*100)}% · C ${Math.round(c/t*100)}% · F ${Math.round(f/t*100)}%`,"","Macro percentages","Uses 4 kcal/g for protein and carbohydrate and 9 kcal/g for fat.");}),
  extra("fiber-intake-calculator","Fiber Intake Calculator","Nutrition & Macronutrients","Estimate a daily fibre target using an energy-based starting point.","Fiber ≈ 14 g per 1,000 kcal",[field("calories","Daily calories / kcal",2400)],v=>out(n(v,"calories")/1000*14,"g/day","Estimated fibre target","Energy-based planning estimate; needs vary by age and sex.")),
  extra("net-carbohydrate-calculator","Net Carbohydrate Calculator","Nutrition & Macronutrients","Calculate net carbohydrate as total carbohydrate minus fibre.","Net carbs = total carbohydrate − fibre",[field("carbs","Total carbohydrate / g",40),field("fiber","Fibre / g",10)],v=>out(Math.max(0,n(v,"carbs")-n(v,"fiber")),"g","Net carbohydrate","Labeling conventions can differ and carbohydrate types vary.")),
  shared("water-intake-calculator","Water Intake Calculator","Nutrition & Macronutrients","Estimate a starting daily fluid target from body weight.","Starting estimate = 35 mL × body weight",["weight"],s=>{const x=m(s);return out(x.weightKg*35,"mL/day","Estimated fluid target","Fluid needs vary with climate, activity, diet and health status.");})
];
