import { toMetric, getActivityFactor, formatNumber } from "./units";

const out = (value, unit = "", category = "", interpretation = "") => ({
  value: typeof value === "number" ? formatNumber(value, 1) : value,
  raw: typeof value === "number" ? value : undefined,
  unit, category, tone: "good", interpretation,
});
const field = (name, label, value) => ({ name, label, default: String(value) });
const extra = (id, name, category, description, formula, inputFields, computeExtra) => ({
  id, slug: id, name, category, requires: [], description, formula,
  extraInputs: true, inputFields, computeExtra,
});
const shared = (id, name, category, description, formula, requires, compute) => ({
  id, slug: id, name, category, description, formula, requires, compute,
});
const n = (v, k, d = 0) => Number.isFinite(+v?.[k]) ? +v[k] : d;
const m = (s) => toMetric(s);
const bmi = (x) => x.weightKg / Math.pow(x.heightCm / 100, 2);
const bodyFat = (x) => 1.2 * bmi(x) + 0.23 * x.age - (x.sex === "male" ? 10.8 : 0) - 5.4;
const lean = (x) => x.sex === "male"
  ? 0.407 * x.weightKg + 0.267 * x.heightCm - 19.2
  : 0.252 * x.weightKg + 0.473 * x.heightCm - 48.3;
const bmr = (x) => 10 * x.weightKg + 6.25 * x.heightCm - 5 * x.age + (x.sex === "male" ? 5 : -161);
const tdee = (x) => bmr(x) * getActivityFactor(x.activity);
const riegel = (v, target) => (n(v,"minutes") + n(v,"seconds") / 60) * Math.pow(target / n(v,"distance",1), 1.06);
const epley = (v) => n(v,"load") * (1 + Math.min(30, n(v,"reps")) / 30);
const timeHours = (v) => (n(v,"minutes") * 60 + n(v,"seconds")) / 3600;
const MET = { walking: 3.5, running: 8.3, cycling: 7.5 };

export const NEW_CALCULATORS = [
  // BODY COMPOSITION — 3
  shared("fmi-calculator","Fat Mass Index (FMI) Calculator","Body Composition","Estimate fat mass relative to height squared.","FMI = fat mass ÷ height²",["height","weight","age","sex"],s=>{const x=m(s),fm=x.weightKg*bodyFat(x)/100;return out(fm/Math.pow(x.heightCm/100,2),"kg/m²","Estimated FMI","FMI is an estimate derived from body-fat estimation and is not a direct measurement.");}),
  shared("total-body-water-calculator","Total Body Water Calculator","Body Composition","Estimate total body water using the Watson equation.","Watson TBW equation using age, sex, height and weight",["height","weight","age","sex"],s=>{const x=m(s),tbw=x.sex==="male"?2.447-.09516*x.age+.1074*x.heightCm+.3362*x.weightKg:2.097-.1069*x.age+.2466*x.heightCm+.2466*x.weightKg;return out(tbw,"L","Estimated total body water","Population estimate; hydration status and body composition affect actual total body water.");}),
  shared("skeletal-muscle-mass-calculator","Skeletal Muscle Mass Calculator","Body Composition","Estimate skeletal muscle mass from estimated lean body mass.","Skeletal muscle mass ≈ 50% of estimated lean body mass",["height","weight","age","sex"],s=>out(lean(m(s))*.5,"kg","Estimated skeletal muscle mass","Rough population estimate, not a direct measurement.")),

  // WEIGHT, BMI & WEIGHT GOALS — 10
  extra("target-weight-calculator","Target Weight Calculator","Weight, BMI & Weight Goals","Calculate the weight difference between current and target weight.","Target weight = selected goal weight",[field("currentWeight","Current weight / kg",85),field("targetWeight","Target weight / kg",75)],v=>out(n(v,"targetWeight"),"kg","Target weight","A goal weight is a planning value, not a universal ideal.")),
  extra("target-weight-by-bmi-calculator","Target Weight by BMI Calculator","Weight, BMI & Weight Goals","Calculate the weight corresponding to a selected BMI and height.","Weight = target BMI × height²",[field("height","Height / cm",175),field("targetBMI","Target BMI",22)],v=>out(n(v,"targetBMI")*Math.pow(n(v,"height")/100,2),"kg","Weight at target BMI","BMI is a screening measure and does not directly measure body fat.")),
  extra("weight-loss-percentage-calculator","Weight Loss Percentage Calculator","Weight, BMI & Weight Goals","Calculate percentage of starting body weight lost.","Loss % = (starting − current) ÷ starting × 100",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",80)],v=>out((n(v,"startWeight")-n(v,"currentWeight"))/n(v,"startWeight")*100,"%","Weight loss","Calculated from starting body weight.")),
  extra("weight-gain-percentage-calculator","Weight Gain Percentage Calculator","Weight, BMI & Weight Goals","Calculate percentage of starting body weight gained.","Gain % = (current − starting) ÷ starting × 100",[field("startWeight","Starting weight / kg",70),field("currentWeight","Current weight / kg",75)],v=>out((n(v,"currentWeight")-n(v,"startWeight"))/n(v,"startWeight")*100,"%","Weight gain","Calculated from starting body weight.")),
  extra("weight-change-calculator","Weight Change Calculator","Weight, BMI & Weight Goals","Calculate absolute and percentage weight change.","Change = current − starting",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",82)],v=>{const d=n(v,"currentWeight")-n(v,"startWeight");return out(`${d.toFixed(1)} kg (${(d/n(v,"startWeight")*100).toFixed(1)}%)`,"","Weight change","Negative values indicate weight loss; positive values indicate weight gain.");}),
  extra("weight-loss-timeline-calculator","Weight Loss Timeline Calculator","Weight, BMI & Weight Goals","Estimate time to lose a selected amount of weight at a chosen deficit.","Weeks ≈ weight to lose × 7,700 ÷ daily deficit",[field("weightToLose","Weight to lose / kg",5),field("dailyDeficit","Daily deficit / kcal",500)],v=>out(n(v,"weightToLose")*7700/n(v,"dailyDeficit"),"weeks","Estimated timeline","7,700 kcal/kg is a simplified energy-equivalence estimate; actual weight change is not linear.")),
  extra("goal-weight-date-calculator","Goal Weight Date Calculator","Weight, BMI & Weight Goals","Estimate the date of reaching a goal weight at a chosen weekly rate.","Weeks = weight to lose ÷ weekly rate",[field("currentWeight","Current weight / kg",85),field("goalWeight","Goal weight / kg",75),field("weeklyRate","Weekly loss / kg",.5)],v=>{const days=Math.max(0,(n(v,"currentWeight")-n(v,"goalWeight"))/n(v,"weeklyRate")*7);return out(new Date(Date.now()+days*86400000).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}),"","Estimated goal date","Assumes the selected weekly rate remains constant.");}),
  extra("weekly-weight-loss-calculator","Weekly Weight Loss Calculator","Weight, BMI & Weight Goals","Estimate weekly weight change from a daily calorie deficit.","Weekly loss ≈ daily deficit × 7 ÷ 7,700",[field("dailyDeficit","Daily deficit / kcal",500)],v=>out(n(v,"dailyDeficit")*7/7700,"kg/week","Estimated weekly loss","Energy-equivalence estimate, not a guarantee of scale change.")),
  extra("calories-to-lose-1-kg-calculator","Calories to Lose 1 kg Calculator","Weight, BMI & Weight Goals","Show a simplified energy equivalent for 1 kg of body-mass loss.","Approximate energy equivalent ≈ 7,700 kcal/kg",[],()=>out(7700,"kcal","Approximate energy equivalent","Actual energy requirements vary and body weight change is not purely fat loss.")),
  extra("calories-to-gain-1-kg-calculator","Calories to Gain 1 kg Calculator","Weight, BMI & Weight Goals","Show a simplified energy equivalent for 1 kg of body-mass gain.","Simplified energy estimate ≈ 7,700 kcal/kg",[],()=>out(7700,"kcal","Approximate energy equivalent","Actual gain depends on the tissue gained and energy expenditure.")),

  // CALORIES & METABOLISM — 9
  shared("maintenance-calories-calculator","Maintenance Calories Calculator","Calories & Metabolism","Estimate daily maintenance calories from BMR and activity.","Maintenance = BMR × activity factor",["height","weight","age","sex","activity"],s=>out(tdee(m(s)),"kcal/day","Estimated maintenance","Actual energy needs vary from day to day.")),
  shared("weight-loss-calorie-calculator","Weight Loss Calorie Calculator","Calories & Metabolism","Estimate a starting calorie target using a moderate deficit.","Weight-loss target = estimated TDEE − 500 kcal/day",["height","weight","age","sex","activity"],s=>out(Math.max(0,tdee(m(s))-500),"kcal/day","Estimated weight-loss intake","A moderate deficit is a planning estimate; individual needs vary.")),
  shared("weight-gain-calorie-calculator","Weight Gain Calorie Calculator","Calories & Metabolism","Estimate a starting calorie target using a modest surplus.","Weight-gain target = estimated TDEE + 300 kcal/day",["height","weight","age","sex","activity"],s=>out(tdee(m(s))+300,"kcal/day","Estimated weight-gain intake","A modest surplus is a planning estimate; actual needs vary.")),
  extra("exercise-calorie-calculator","Exercise Calorie Calculator","Calories & Metabolism","Estimate exercise energy expenditure from MET, body weight and duration.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("met","Exercise MET",6),field("minutes","Duration / min",45)],v=>out(n(v,"met")*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated exercise calories","MET-based estimate; actual energy expenditure varies.")),
  extra("walking-calorie-calculator","Walking Calorie Calculator","Calories & Metabolism","Estimate calories burned during walking.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Walking duration / min",60)],v=>out(MET.walking*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated walking calories","Walking intensity, terrain and speed affect actual expenditure.")),
  extra("running-calorie-calculator","Running Calorie Calculator","Calories & Metabolism","Estimate calories burned during running.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Running duration / min",30)],v=>out(MET.running*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated running calories","Running speed, terrain and fitness affect actual expenditure.")),
  extra("cycling-calorie-calculator","Cycling Calorie Calculator","Calories & Metabolism","Estimate calories burned during cycling.","Calories ≈ MET × 3.5 × weight ÷ 200 × minutes",[field("weight","Body weight / kg",75),field("minutes","Cycling duration / min",45)],v=>out(MET.cycling*3.5*n(v,"weight")/200*n(v,"minutes"),"kcal","Estimated cycling calories","Cycling intensity, terrain and equipment affect actual expenditure.")),
  extra("reverse-diet-calculator","Reverse Diet Calculator","Calories & Metabolism","Estimate the number of planned weekly calorie increases needed to reach a target intake.","Weeks = calorie gap ÷ weekly increase",[field("currentCalories","Current intake / kcal",1800),field("targetCalories","Target intake / kcal",2400),field("weeklyIncrease","Weekly increase / kcal",100)],v=>out(Math.max(0,Math.ceil((n(v,"targetCalories")-n(v,"currentCalories"))/Math.max(1,n(v,"weeklyIncrease")))),"weeks","Planned calorie increases","Reverse dieting is a planning approach, not a proven way to permanently increase metabolic rate.")),
  extra("calorie-per-meal-calculator","Calorie per Meal Calculator","Calories & Metabolism","Divide a daily calorie target across meals.","Calories per meal = daily calories ÷ meals",[field("dailyCalories","Daily calories / kcal",2400),field("meals","Meals per day",4)],v=>out(n(v,"dailyCalories")/Math.max(1,n(v,"meals")),"kcal/meal","Meal calorie target","Meal distribution can be adjusted to preference and schedule.")),

  // NUTRITION & MACRONUTRIENTS — 11
  shared("protein-per-meal-calculator","Protein per Meal Calculator","Nutrition & Macronutrients","Divide a practical daily protein target across meals.","Protein per meal = daily protein ÷ meals",["weight","activity"],s=>{const x=m(s),factor={sedentary:1.2,light:1.4,moderate:1.6,active:1.7,very_active:1.8}[x.activity]||1.6;return out(x.weightKg*factor/4,"g/meal","Protein distribution","Uses an activity-based protein planning target." );}),
  extra("protein-to-calorie-ratio-calculator","Protein-to-Calorie Ratio Calculator","Nutrition & Macronutrients","Calculate protein grams per 100 calories.","Protein density = protein ÷ calories × 100",[field("protein","Protein / g",30),field("calories","Calories",300)],v=>out(n(v,"protein")/Math.max(1,n(v,"calories"))*100,"g/100 kcal","Protein density","Higher values indicate more protein relative to energy.")),
  shared("macronutrient-calculator","Macronutrient Calculator","Nutrition & Macronutrients","Estimate daily protein, carbohydrate and fat targets from calorie needs.","Protein ≈ 1.6 g/kg; fat ≈ 25% calories; carbs fill remaining calories",["height","weight","age","sex","activity"],s=>{const x=m(s),k=tdee(x),p=x.weightKg*1.6,f=k*.25/9,c=Math.max(0,(k-p*4-f*9)/4);return out(`P ${Math.round(p)}g · C ${Math.round(c)}g · F ${Math.round(f)}g`,"/day","Estimated macro targets","Starting macro estimate; individual nutrition needs vary.");}),
  extra("macro-percentage-calculator","Macro Percentage Calculator","Nutrition & Macronutrients","Convert macro grams into calorie percentages.","Protein/carbohydrate = g×4; fat = g×9",[field("protein","Protein / g",150),field("carbs","Carbohydrate / g",250),field("fat","Fat / g",70)],v=>{const p=n(v,"protein")*4,c=n(v,"carbs")*4,f=n(v,"fat")*9,t=p+c+f;return out(`P ${Math.round(p/t*100)}% · C ${Math.round(c/t*100)}% · F ${Math.round(f/t*100)}%`,"","Macro percentages","Uses 4 kcal/g for protein and carbohydrate and 9 kcal/g for fat.");}),
  extra("fiber-intake-calculator","Fiber Intake Calculator","Nutrition & Macronutrients","Estimate a daily fibre target using an energy-based starting point.","Fiber ≈ 14 g per 1,000 kcal",[field("calories","Daily calories / kcal",2400)],v=>out(n(v,"calories")/1000*14,"g/day","Estimated fibre target","Energy-based planning estimate; needs vary by age and sex.")),
  extra("net-carbohydrate-calculator","Net Carbohydrate Calculator","Nutrition & Macronutrients","Calculate net carbohydrate as total carbohydrate minus fibre.","Net carbs = total carbohydrate − fibre",[field("carbs","Total carbohydrate / g",40),field("fiber","Fibre / g",10)],v=>out(Math.max(0,n(v,"carbs")-n(v,"fiber")),"g","Net carbohydrate","Labeling conventions can differ and carbohydrate types vary.")),
  shared("water-intake-calculator","Water Intake Calculator","Nutrition & Macronutrients","Estimate a starting daily fluid target from body weight.","Starting estimate = 35 mL × body weight(kg)",["weight"],s=>out(m(s).weightKg*35,"mL/day","Starting fluid estimate","Fluid needs also depend on climate, exercise, illness and food intake.")),
  extra("sodium-intake-calculator","Sodium Intake Calculator","Nutrition & Macronutrients","Compare sodium intake with a common adult reference level.","Percentage = sodium ÷ 2,300 mg × 100",[field("sodium","Sodium / mg",2000)],v=>out(n(v,"sodium")/2300*100,"% of 2,300 mg","Reference comparison","Individual needs can differ from a general adult reference.")),
  extra("caffeine-intake-calculator","Caffeine Intake Calculator","Nutrition & Macronutrients","Add caffeine from several sources.","Total caffeine = sum of sources",[field("coffee","Coffee / mg",200),field("tea","Tea / mg",50),field("energy","Energy drinks / mg",0),field("other","Other sources / mg",0)],v=>out(n(v,"coffee")+n(v,"tea")+n(v,"energy")+n(v,"other"),"mg/day","Daily caffeine","Many healthy adults are advised to keep caffeine around or below 400 mg/day, but individual tolerance varies.")),
  extra("micronutrient-intake-calculator","Micronutrient Intake Calculator","Nutrition & Macronutrients","Show selected general micronutrient reference intakes by age and sex.","Reference values vary by age, sex and life stage",[field("age","Age / years",30),field("sexCode","Sex: 1 male / 0 female",1)],v=>{const female=n(v,"sexCode")===0,age=n(v,"age");return out(`Calcium ${age<19?1300:1000} mg · Iron ${female?18:8} mg · Vit D 15 µg · Magnesium ${female?310:400} mg`,"/day","Selected reference intakes","General reference values are not individualized prescriptions."),}),
  shared("daily-calorie-macro-calculator","Daily Calorie & Macro Calculator","Nutrition & Macronutrients","Combine estimated maintenance calories with a practical macro split.","TDEE; protein ≈ 1.6 g/kg; fat ≈ 25%; carbs fill remaining calories",["height","weight","age","sex","activity"],s=>{const x=m(s),k=tdee(x),p=x.weightKg*1.6,f=k*.25/9,c=Math.max(0,(k-p*4-f*9)/4);return out(`${Math.round(k)} kcal · P ${Math.round(p)}g · C ${Math.round(c)}g · F ${Math.round(f)}g`,"/day","Daily calorie & macro estimate","Starting estimate based on body data and activity." );}),
  extra("meal-macro-calculator","Meal Macro Calculator","Nutrition & Macronutrients","Divide daily macro targets across meals.","Meal macro = daily macro target ÷ meals",[field("protein","Daily protein / g",150),field("carbs","Daily carbohydrate / g",250),field("fat","Daily fat / g",70),field("meals","Meals per day",4)],v=>out(`P ${Math.round(n(v,"protein")/Math.max(1,n(v,"meals")))}g · C ${Math.round(n(v,"carbs")/Math.max(1,n(v,"meals")))}g · F ${Math.round(n(v,"fat")/Math.max(1,n(v,"meals")))}g`,"/meal","Meal macro target","Equal meal distribution is only a planning option.")),

  // RUNNING, CARDIO & ENDURANCE — 14
  extra("running-speed-calculator","Running Speed Calculator","Running, Cardio & Endurance","Calculate running speed from distance and elapsed time.","Speed = distance ÷ time",[field("distance","Distance / km",5),field("minutes","Minutes",30),field("seconds","Seconds",0)],v=>out(n(v,"distance")/timeHours(v),"km/h","Running speed","Calculated from distance and elapsed time.")),
  extra("pace-to-speed-converter","Pace-to-Speed Converter","Running, Cardio & Endurance","Convert running pace into speed.","Speed = 60 ÷ pace",[field("paceMinutes","Pace minutes / km",6),field("paceSeconds","Pace seconds / km",0)],v=>out(60/(n(v,"paceMinutes")+n(v,"paceSeconds")/60),"km/h","Equivalent speed","Assumes pace is expressed in minutes per kilometre.")),
  extra("5k-time-predictor","5K Time Predictor","Running, Cardio & Endurance","Predict 5K time from another distance and time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>out(riegel(v,5),"minutes","Predicted 5K time","Prediction is an estimate; conditions and training affect performance.")),
  extra("10k-time-predictor","10K Time Predictor","Running, Cardio & Endurance","Predict 10K time from another distance and time.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",5),field("minutes","Known time minutes",27),field("seconds","Known time seconds",0)],v=>out(riegel(v,10),"minutes","Predicted 10K time","Prediction is an estimate based on a reference performance.")),
  extra("half-marathon-time-predictor","Half-Marathon Time Predictor","Running, Cardio & Endurance","Predict half-marathon time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>out(riegel(v,21.0975),"minutes","Predicted half-marathon time","Use as a training estimate, not a guarantee.")),
  extra("marathon-time-predictor","Marathon Time Predictor","Running, Cardio & Endurance","Predict marathon time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>out(riegel(v,42.195),"minutes","Predicted marathon time","Long-distance performance depends strongly on endurance and fueling.")),
  extra("race-time-calculator","Race Time Calculator","Running, Cardio & Endurance","Calculate race time from distance and pace.","Time = distance × pace",[field("distance","Distance / km",10),field("paceMinutes","Pace minutes / km",5),field("paceSeconds","Pace seconds / km",0)],v=>{const total=n(v,"distance")*(n(v,"paceMinutes")+n(v,"paceSeconds")/60);return out(`${Math.floor(total/60)}:${String(Math.round(total%60)).padStart(2,"0")}`,"hh:mm","Race time","Calculated from distance and target pace.");}),
  extra("running-split-calculator","Running Split Calculator","Running, Cardio & Endurance","Calculate average split time for a selected distance segment.","Average split = total time ÷ number of splits",[field("distance","Total distance / km",5),field("minutes","Total minutes",30),field("seconds","Total seconds",0),field("splitKm","Split distance / km",1)],v=>out((n(v,"minutes")+n(v,"seconds")/60)/(n(v,"distance")/n(v,"splitKm")),"minutes","Average split","Average time for the selected split distance.")),
  extra("training-pace-calculator","Training Pace Calculator","Running, Cardio & Endurance","Estimate a training pace from a recent race effort.","Training pace = race pace × selected multiplier",[field("distance","Race distance / km",5),field("minutes","Race minutes",25),field("seconds","Race seconds",0),field("factor","Training multiplier",1.15)],v=>out(((n(v,"minutes")+n(v,"seconds")/60)/n(v,"distance"))*n(v,"factor"),"min/km","Suggested training pace","Multiplier is a planning tool; effort and terrain should guide adjustments.")),
  extra("vo2-max-calculator","VO₂ Max Calculator","Running, Cardio & Endurance","Estimate VO₂ max from a Cooper-style 12-minute run.","VO₂max ≈ (distance in metres − 504.9) ÷ 44.73",[field("distanceMeters","12-minute distance / m",2400)],v=>out((n(v,"distanceMeters")-504.9)/44.73,"mL/kg/min","Estimated VO₂ max","Field-test estimate influenced by pacing, terrain and weather.")),
  extra("cardio-fitness-level-calculator","Cardio Fitness Level Calculator","Running, Cardio & Endurance","Classify an entered VO₂ max estimate into a broad fitness band.","Broad fitness band based on VO₂ max",[field("vo2","VO₂ max / mL/kg/min",40)],v=>{const x=n(v,"vo2");return out(x<30?"Low":x<40?"Fair":x<50?"Good":"Very good","","Broad cardio fitness band","Norms differ substantially by age, sex and population." );}),
  extra("aerobic-training-zone-calculator","Aerobic Training Zone Calculator","Running, Cardio & Endurance","Estimate an aerobic heart-rate zone using heart-rate reserve.","Target HR = resting HR + intensity × HRR",[field("age","Age / years",30),field("resting","Resting HR / bpm",60),field("low","Low intensity / %",60),field("high","High intensity / %",70)],v=>{const hrr=220-n(v,"age")-n(v,"resting");return out(`${Math.round(n(v,"resting")+hrr*n(v,"low")/100)}–${Math.round(n(v,"resting")+hrr*n(v,"high")/100)}`,"bpm","Estimated aerobic zone","Heart-rate zones are estimates and can be affected by medication, fitness and measured maximum heart rate.");}),
  extra("anaerobic-threshold-calculator","Anaerobic Threshold Calculator","Running, Cardio & Endurance","Estimate threshold heart rate from a sustained hard effort.","Threshold estimate = average HR during a sustained hard effort",[field("heartRate","Average hard-effort HR / bpm",165)],v=>out(n(v,"heartRate"),"bpm","Threshold estimate","A field estimate is not equivalent to a laboratory threshold test.")),
  extra("fitness-age-calculator","Fitness Age Calculator","Running, Cardio & Endurance","Estimate a simple fitness age from chronological age and VO₂ max.","Fitness age = age + 0.5 × (35 − VO₂max)",[field("age","Age / years",30),field("vo2","VO₂ max / mL/kg/min",40)],v=>out(Math.max(18,n(v,"age")+(35-n(v,"vo2"))*.5),"years","Estimated fitness age","Illustrative estimate only; validated equations vary by assessment method.")),

  // STRENGTH & GYM PERFORMANCE — 9
  extra("bench-press-1rm-calculator","Bench Press 1RM Calculator","Strength & Gym Performance","Estimate bench press one-repetition maximum.","Epley: 1RM = load × (1 + reps/30)",[field("load","Bench weight / kg",80),field("reps","Repetitions",8)],v=>out(epley(v),"kg","Estimated bench 1RM","Prediction is an estimate and is not a substitute for safe lifting technique.")),
  extra("squat-1rm-calculator","Squat 1RM Calculator","Strength & Gym Performance","Estimate squat one-repetition maximum.","Epley: 1RM = load × (1 + reps/30)",[field("load","Squat weight / kg",100),field("reps","Repetitions",8)],v=>out(epley(v),"kg","Estimated squat 1RM","Use conservative loads when applying a predicted maximum.")),
  extra("deadlift-1rm-calculator","Deadlift 1RM Calculator","Strength & Gym Performance","Estimate deadlift one-repetition maximum.","Epley: 1RM = load × (1 + reps/30)",[field("load","Deadlift weight / kg",120),field("reps","Repetitions",5)],v=>out(epley(v),"kg","Estimated deadlift 1RM","A predicted maximum is not a substitute for safe technique.")),
  extra("rep-max-calculator","Rep Max Calculator","Strength & Gym Performance","Estimate 1RM and equivalent target-repetition load.","Epley 1RM = load × (1 + reps/30)",[field("load","Weight / kg",80),field("reps","Repetitions",8),field("targetReps","Target repetitions",5)],v=>out(epley(v)/(1+n(v,"targetReps")/30),"kg","Estimated target-rep load","Equivalent loads are approximate.")),
  extra("strength-level-calculator","Strength Level Calculator","Strength & Gym Performance","Estimate strength relative to body weight.","Strength ratio = 1RM ÷ body weight",[field("bodyWeight","Body weight / kg",85),field("liftWeight","Lift 1RM / kg",100)],v=>out(n(v,"liftWeight")/Math.max(1,n(v,"bodyWeight")),":1 bodyweight","Strength ratio","Simple ratio; not age- or sex-adjusted.")),
  extra("strength-to-weight-ratio-calculator","Strength-to-Weight Ratio Calculator","Strength & Gym Performance","Calculate lifting strength relative to body weight.","Ratio = lift ÷ body weight",[field("bodyWeight","Body weight / kg",85),field("liftWeight","Lift / kg",100)],v=>out(n(v,"liftWeight")/Math.max(1,n(v,"bodyWeight")),":1","Strength-to-weight","Useful for tracking relative strength as body weight changes.")),
  extra("training-volume-calculator","Training Volume Calculator","Strength & Gym Performance","Calculate resistance-training volume.","Volume = sets × reps × load",[field("sets","Sets",4),field("reps","Repetitions/set",8),field("load","Load / kg",80)],v=>out(n(v,"sets")*n(v,"reps")*n(v,"load"),"kg","Training volume","Useful for comparing sessions using the same exercise and load convention.")),
  extra("wilks-score-calculator","Wilks Score Calculator","Strength & Gym Performance","Calculate a Wilks-style powerlifting score.","Score = total × 500 ÷ Wilks coefficient(body weight)",[field("bodyWeight","Body weight / kg",85),field("total","Powerlifting total / kg",400),field("sexCode","Sex: 1 male / 0 female",1)],v=>{const w=n(v,"bodyWeight"),t=n(v,"total"),male=n(v,"sexCode")===1;const c=male?(-216.0475144+16.2606339*w-.002388645*w*w-.00113732*w*w*w+7.01863e-6*w**4-1.291e-8*w**5):(594.31747775582-27.23842536447*w+.82112226871*w*w-.00930733913*w**3+4.731582e-5*w**4-9.054e-8*w**5);return out(t*500/c,"points","Wilks-style score","Coefficient-based estimate; official competition scoring uses federation rules and current standards.");}),
  extra("dots-score-calculator","DOTS Score Calculator","Strength & Gym Performance","Calculate a DOTS-style powerlifting score.","DOTS = total × coefficient(body weight)",[field("bodyWeight","Body weight / kg",85),field("total","Powerlifting total / kg",400)],v=>{const w=n(v,"bodyWeight"),a=-216.0475144,b=16.2606339,c=-.002388645,d=-.00113732,e=7.01863e-6,f=-1.291e-8;const coef=a+b*w+c*w*w+d*w**3+e*w**4+f*w**5;return out(n(v,"total")*500/coef,"points","DOTS-style score","Simplified coefficient estimate; use federation rules for competition scoring.");}),

  // HEART RATE & CARDIOVASCULAR METRICS — 9
  extra("maximum-heart-rate-calculator","Maximum Heart Rate Calculator","Heart Rate & Cardiovascular Metrics","Estimate maximum heart rate from age.","HRmax ≈ 220 − age",[field("age","Age / years",30)],v=>out(220-n(v,"age"),"bpm","Estimated maximum heart rate","Age-based formulas are population estimates and can differ from measured maximum heart rate.")),
  extra("heart-rate-zone-calculator","Heart Rate Zone Calculator","Heart Rate & Cardiovascular Metrics","Calculate common percentage-based heart-rate zones.","Zones = HRmax × selected intensity ranges",[field("age","Age / years",30)],v=>{const max=220-n(v,"age");return out(`${Math.round(max*.5)}–${Math.round(max*.6)} · ${Math.round(max*.6)}–${Math.round(max*.7)} · ${Math.round(max*.7)}–${Math.round(max*.8)} · ${Math.round(max*.8)}–${Math.round(max*.9)}`,"bpm","50–60 / 60–70 / 70–80 / 80–90% HRmax","Percentage zones are estimates and should be individualized when appropriate." );}),
  extra("resting-heart-rate-calculator","Resting Heart Rate Calculator","Heart Rate & Cardiovascular Metrics","Calculate average resting heart rate from repeated readings.","Average = sum of readings ÷ number of readings",[field("r1","Reading 1 / bpm",65),field("r2","Reading 2 / bpm",64),field("r3","Reading 3 / bpm",66)],v=>out((n(v,"r1")+n(v,"r2")+n(v,"r3"))/3,"bpm","Average resting heart rate","Measure under consistent resting conditions; interpretation needs context.")),
  extra("heart-rate-reserve-calculator","Heart Rate Reserve Calculator","Heart Rate & Cardiovascular Metrics","Calculate heart-rate reserve from estimated maximum and resting heart rate.","HRR = HRmax − resting HR",[field("age","Age / years",30),field("resting","Resting HR / bpm",60)],v=>out(220-n(v,"age")-n(v,"resting"),"bpm","Heart-rate reserve","220 − age is a population estimate.")),
  extra("heart-rate-recovery-calculator","Heart Rate Recovery Calculator","Heart Rate & Cardiovascular Metrics","Calculate the heart-rate drop after exercise.","HRR = peak exercise HR − recovery HR",[field("peak","Peak exercise HR / bpm",160),field("recovery","Recovery HR / bpm",120)],v=>out(n(v,"peak")-n(v,"recovery"),"bpm","Heart-rate recovery","Use the same recovery interval when tracking changes.")),
  extra("pulse-pressure-calculator","Pulse Pressure Calculator","Heart Rate & Cardiovascular Metrics","Calculate pulse pressure from systolic and diastolic blood pressure.","Pulse pressure = systolic − diastolic",[field("systolic","Systolic / mmHg",120),field("diastolic","Diastolic / mmHg",80)],v=>out(n(v,"systolic")-n(v,"diastolic"),"mmHg","Pulse pressure","Blood-pressure interpretation should use repeated measurements and clinical context.")),
  extra("mean-arterial-pressure-calculator","Mean Arterial Pressure (MAP) Calculator","Heart Rate & Cardiovascular Metrics","Estimate mean arterial pressure.","MAP ≈ (SBP + 2×DBP) ÷ 3",[field("systolic","Systolic / mmHg",120),field("diastolic","Diastolic / mmHg",80)],v=>out((n(v,"systolic")+2*n(v,"diastolic"))/3,"mmHg","Estimated MAP","Approximation, not a substitute for clinical assessment.")),
  extra("rate-pressure-product-calculator","Rate Pressure Product Calculator","Heart Rate & Cardiovascular Metrics","Calculate rate-pressure product from heart rate and systolic pressure.","RPP = heart rate × systolic blood pressure",[field("heartRate","Heart rate / bpm",70),field("systolic","Systolic BP / mmHg",120)],v=>out(n(v,"heartRate")*n(v,"systolic"),"bpm·mmHg","Rate-pressure product","RPP is an exercise/cardiovascular workload index, not a diagnosis.")),
  extra("waist-circumference-health-risk-calculator","Waist Circumference Health Risk Calculator","Heart Rate & Cardiovascular Metrics","Classify waist circumference using common adult screening thresholds.","Risk band based on waist circumference and sex",[field("waist","Waist / cm",90),field("sexCode","Sex: 1 male / 0 female",1)],v=>{const w=n(v,"waist"),male=n(v,"sexCode")===1;const high=male?w>=102:w>=88,raised=male?w>=94:w>=80;return out(high?"Higher risk":raised?"Increased risk":"Lower risk","","Waist-risk screening","Thresholds are screening values and vary by population and guideline.");}),
];
