import { toMetric, getActivityFactor, formatNumber } from "./units";

const result = (value, unit, category, interpretation) => ({
  value: typeof value === "number" ? formatNumber(value, 1) : value,
  raw: typeof value === "number" ? value : undefined,
  unit,
  category,
  tone: "good",
  interpretation,
});
const extra = (inputFields) => ({ extraInputs: true, inputFields });
const n = (v, k, d = 0) => Number.isFinite(+v?.[k]) ? +v[k] : d;
const metric = (v) => toMetric(v.state || v);
const bmi = (m) => m.weightKg / Math.pow(m.heightCm / 100, 2);
const bf = (m) => 1.2 * bmi(m) + 0.23 * m.age - (m.sex === "male" ? 10.8 : 0) - 5.4;
const lbm = (m) => m.sex === "male" ? 0.407 * m.weightKg + 0.267 * m.heightCm - 19.2 : 0.252 * m.weightKg + 0.473 * m.heightCm - 48.3;
const bmr = (m) => 10 * m.weightKg + 6.25 * m.heightCm - 5 * m.age + (m.sex === "male" ? 5 : -161);
const tdee = (m) => bmr(m) * getActivityFactor(m.activity);
const riegel = (v, target) => (n(v, "minutes") + n(v, "seconds") / 60) * Math.pow(target / n(v, "distance", 10), 1.06);
const epley = (v) => n(v, "load") * (1 + Math.min(30, n(v, "reps")) / 30);

const field = (name, label, value) => ({ name, label, default: String(value) });
const make = (id, name, category, description, formula, inputFields, computeExtra) => ({
  id, slug: id, name, category, requires: [], description, formula, ...extra(inputFields), computeExtra,
});

export const NEW_CALCULATORS = [
  { id:"fmi-calculator", slug:"fmi-calculator", name:"FMI Calculator", category:"Body Composition", requires:["height","weight","age","sex"], description:"Estimate Fat Mass Index from body weight, height, age and sex.", formula:"FMI = fat mass ÷ height²", compute:s=>{const m=metric({state:s}),fm=m.weightKg*bf(m)/100;return result(fm/Math.pow(m.heightCm/100,2),"kg/m²","Fat Mass Index","Estimate only; body-fat equations introduce uncertainty.");}},
  { id:"skeletal-muscle-mass-calculator", slug:"skeletal-muscle-mass-calculator", name:"Skeletal Muscle Mass Calculator", category:"Body Composition", requires:["height","weight","age","sex"], description:"Estimate skeletal muscle mass from estimated lean body mass.", formula:"SMM ≈ 50% of estimated lean body mass", compute:s=>result(lbm(metric({state:s}))*.5,"kg","Estimated skeletal muscle mass","Rough population estimate, not a direct measurement.") },
  { id:"muscle-mass-percentage-calculator", slug:"muscle-mass-percentage-calculator", name:"Muscle Mass Percentage Calculator", category:"Body Composition", requires:["height","weight","age","sex"], description:"Estimate skeletal muscle as a percentage of body weight.", formula:"Muscle % = SMM ÷ weight × 100", compute:s=>{const m=metric({state:s});return result(lbm(m)*.5/m.weightKg*100,"%","Estimated muscle percentage","Derived estimate rather than direct tissue measurement.");}},
  { id:"muscle-to-fat-ratio-calculator", slug:"muscle-to-fat-ratio-calculator", name:"Muscle-to-Fat Ratio Calculator", category:"Body Composition", requires:["height","weight","age","sex"], description:"Compare estimated skeletal muscle mass with estimated fat mass.", formula:"Muscle-to-fat = SMM ÷ fat mass", compute:s=>{const m=metric({state:s}),fm=m.weightKg*bf(m)/100;return result(lbm(m)*.5/fm,":1","Estimated ratio","Use mainly to track changes over time.");}},
  make("body-composition-change-calculator","Body Composition Change Calculator","Body Composition","Compare weight and body-fat measurements between two time points.","Fat mass = weight × body-fat%",[field("startWeight","Start weight / kg",85),field("startBodyFat","Start body fat / %",25),field("endWeight","Current weight / kg",80),field("endBodyFat","Current body fat / %",22)],v=>{const sf=n(v,"startWeight")*n(v,"startBodyFat")/100,ef=n(v,"endWeight")*n(v,"endBodyFat")/100;return result(`${(ef-sf).toFixed(1)} kg fat · ${((n(v,"endWeight")-ef)-(n(v,"startWeight")-sf)).toFixed(1)} kg lean`,"change","Composition change","Negative fat change indicates estimated fat mass decreased.");}),
  make("body-fat-loss-calculator","Body Fat Loss Calculator","Body Composition","Estimate fat mass that would need to be lost to reach a target body-fat percentage.","Target weight = lean mass ÷ (1 − target body-fat%)",[field("weight","Current weight / kg",85),field("bodyFat","Current body fat / %",25),field("targetBodyFat","Target body fat / %",18)],v=>{const w=n(v,"weight"),lean=w*(1-n(v,"bodyFat")/100),target=lean/(1-n(v,"targetBodyFat")/100);return result(w-target,"kg","Estimated fat loss","Assumes lean mass stays constant; real-world change is more complex.");}),
  make("lean-mass-gain-calculator","Lean Mass Gain Calculator","Body Composition","Estimate lean-mass change between two body-composition measurements.","Lean mass = weight × (1 − body-fat%)",[field("startWeight","Start weight / kg",70),field("startBodyFat","Start body fat / %",18),field("endWeight","Current weight / kg",75),field("endBodyFat","Current body fat / %",17)],v=>result(n(v,"endWeight")*(1-n(v,"endBodyFat")/100)-n(v,"startWeight")*(1-n(v,"startBodyFat")/100),"kg","Estimated lean-mass change","Fat-free mass includes water and other tissues, so this is not pure muscle gain.")),
  make("body-fat-goal-calculator","Body Fat Goal Calculator","Body Composition","Estimate goal weight for a target body-fat percentage while preserving current lean mass.","Goal weight = lean mass ÷ (1 − target body-fat%)",[field("weight","Current weight / kg",85),field("bodyFat","Current body fat / %",25),field("targetBodyFat","Target body fat / %",18)],v=>{const w=n(v,"weight"),lean=w*(1-n(v,"bodyFat")/100);return result(lean/(1-n(v,"targetBodyFat")/100),"kg","Estimated goal weight","Mathematical estimate assuming lean mass stays constant.");}),
  make("target-waist-calculator","Target Waist Calculator","Body Composition","Estimate waist circumference from height and a selected waist-to-height ratio.","Target waist = height × target waist-to-height ratio",[field("height","Height / cm",175),field("targetWHtR","Target waist-to-height ratio",.5)],v=>result(n(v,"height")*n(v,"targetWHtR"),"cm","Estimated target waist","Waist-to-height ratio is a screening measure, not an ideal for every person.")),
  { id:"body-proportion-calculator", slug:"body-proportion-calculator", name:"Body Proportion Calculator", category:"Body Composition", requires:["height","waist"], description:"Calculate waist-to-height ratio from body measurements.", formula:"Waist-to-height = waist ÷ height", compute:s=>{const m=metric({state:s});return result(m.waistCm/m.heightCm,":1","Waist-to-height ratio","A screening ratio that puts waist size in height context.");}},
  { id:"maintenance-calories-calculator", slug:"maintenance-calories-calculator", name:"Maintenance Calories Calculator", category:"Calories & Weight Management", requires:["height","weight","age","sex","activity"], description:"Estimate daily maintenance calories using Mifflin-St Jeor and an activity factor.", formula:"Maintenance = BMR × activity factor", compute:s=>result(tdee(metric({state:s})),"kcal/day","Estimated maintenance","Actual needs vary with activity and energy expenditure.") },
  make("weight-loss-percentage-calculator","Weight Loss Percentage Calculator","Calories & Weight Management","Calculate percentage of starting body weight lost.","Loss % = (starting − current) ÷ starting × 100",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",80)],v=>result((n(v,"startWeight")-n(v,"currentWeight"))/n(v,"startWeight")*100,"%","Weight loss","Calculated from starting body weight.")),
  make("weight-gain-percentage-calculator","Weight Gain Percentage Calculator","Calories & Weight Management","Calculate percentage of starting body weight gained.","Gain % = (current − starting) ÷ starting × 100",[field("startWeight","Starting weight / kg",70),field("currentWeight","Current weight / kg",75)],v=>result((n(v,"currentWeight")-n(v,"startWeight"))/n(v,"startWeight")*100,"%","Weight gain","Calculated from starting body weight.")),
  make("weight-loss-timeline-calculator","Weight Loss Timeline Calculator","Calories & Weight Management","Estimate weeks to lose weight at a selected calorie deficit.","Weeks ≈ weight to lose × 7,700 ÷ daily deficit",[field("weightToLose","Weight to lose / kg",5),field("dailyDeficit","Daily deficit / kcal",500)],v=>result(n(v,"weightToLose")*7700/n(v,"dailyDeficit"),"weeks","Estimated timeline","7,700 kcal/kg is a rough energy-equivalence estimate; real weight loss is not linear.")),
  make("goal-weight-date-calculator","Goal Weight Date Calculator","Calories & Weight Management","Estimate a calendar date for reaching a goal weight at a selected weekly rate.","Weeks = weight to lose ÷ weekly rate",[field("currentWeight","Current weight / kg",85),field("goalWeight","Goal weight / kg",75),field("weeklyRate","Weekly loss / kg",.5)],v=>{const days=Math.max(0,(n(v,"currentWeight")-n(v,"goalWeight"))/n(v,"weeklyRate")*7);return result(new Date(Date.now()+days*86400000).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}),"","Estimated goal date","Assumes the selected weekly rate is maintained consistently.");}),
  make("weekly-weight-loss-calculator","Weekly Weight Loss Calculator","Calories & Weight Management","Estimate weekly weight change from a daily calorie deficit.","Weekly loss ≈ deficit × 7 ÷ 7,700",[field("dailyDeficit","Daily deficit / kcal",500)],v=>result(n(v,"dailyDeficit")*7/7700,"kg/week","Estimated weekly loss","Energy-equivalence estimate, not a promise of scale change.")),
  make("weight-change-calculator","Weight Change Calculator","Calories & Weight Management","Calculate absolute and percentage weight change.","Change = current − starting",[field("startWeight","Starting weight / kg",85),field("currentWeight","Current weight / kg",82)],v=>{const d=n(v,"currentWeight")-n(v,"startWeight");return result(`${d.toFixed(1)} kg (${(d/n(v,"startWeight")*100).toFixed(1)}%)`,"","Weight change","Negative values indicate weight loss; positive values indicate weight gain.");}),
  make("calories-to-lose-1-kg-calculator","Calories to Lose 1 kg Calculator","Calories & Weight Management","Show the simplified energy equivalent commonly used for 1 kg of body mass.","Approximate energy equivalent ≈ 7,700 kcal/kg",[],()=>result(7700,"kcal","Approximate energy equivalent","Simplified estimate; actual weight change varies.")),
  make("calories-to-gain-1-kg-calculator","Calories to Gain 1 kg Calculator","Calories & Weight Management","Show a simplified energy equivalent for 1 kg of body-mass gain.","Simplified energy estimate ≈ 7,700 kcal/kg",[],()=>result(7700,"kcal","Approximate energy equivalent","Actual gain depends on tissue gained and energy expenditure.")),
  make("reverse-diet-calculator","Reverse Diet Calculator","Calories & Weight Management","Plan gradual calorie increases toward a chosen intake.","Weeks = calorie gap ÷ weekly increase",[field("currentCalories","Current intake / kcal",1800),field("targetCalories","Target intake / kcal",2400),field("weeklyIncrease","Weekly increase / kcal",100)],v=>result(`${Math.max(0,Math.ceil((n(v,"targetCalories")-n(v,"currentCalories"))/n(v,"weeklyIncrease")))} weeks`,"","Planned increase","Reverse dieting is a planning approach, not an established method for permanently increasing metabolic rate.")),
  { id:"water-intake-calculator", slug:"water-intake-calculator", name:"Water Intake Calculator", category:"Nutrition & Macros", requires:["weight"], description:"Estimate a starting daily fluid target from body weight.", formula:"Starting estimate = 35 mL × body weight(kg)", compute:s=>result(metric({state:s}).weightKg*35,"mL/day","Starting fluid estimate","Fluid needs also depend on climate, exercise, illness, pregnancy and food intake.") },
  { id:"fiber-intake-calculator", slug:"fiber-intake-calculator", name:"Fiber Intake Calculator", category:"Nutrition & Macros", requires:["height","weight","age","sex","activity"], description:"Estimate a daily fibre target using an energy-based starting point.", formula:"Fiber ≈ 14 g per 1,000 kcal", compute:s=>result(tdee(metric({state:s}))/1000*14,"g/day","Estimated fibre target","Energy-based planning estimate; guidance may differ by age and sex.") },
  make("sodium-intake-calculator","Sodium Intake Calculator","Nutrition & Macros","Compare daily sodium intake with a common adult reference level.","Comparison = intake ÷ 2,300 mg × 100",[field("sodium","Sodium intake / mg",2000)],v=>result(n(v,"sodium")/2300*100,"% of 2,300 mg","Reference comparison","Individual needs can differ from a general adult reference.")),
  make("caffeine-intake-calculator","Caffeine Intake Calculator","Nutrition & Macros","Add caffeine from multiple sources and compare the total with a common adult reference.","Total caffeine = sum of sources",[field("coffee","Coffee / mg",200),field("tea","Tea / mg",50),field("energy","Energy drinks / mg",0),field("supplement","Supplements / mg",0)],v=>result(["coffee","tea","energy","supplement"].reduce((a,k)=>a+n(v,k),0),"mg/day","Daily caffeine","For many healthy adults, up to about 400 mg/day is commonly cited; some people need less.")),
  make("protein-per-meal-calculator","Protein per Meal Calculator","Nutrition & Macros","Divide a practical daily protein target across meals.","Protein per meal = daily target ÷ meals",[field("weight","Body weight / kg",85),field("meals","Meals per day",4)],v=>result(n(v,"weight")*1.6/n(v,"meals",1),"g/meal","Protein distribution","Uses 1.6 g/kg/day as a planning assumption; individual needs vary.")),
  make("protein-to-calorie-ratio-calculator","Protein-to-Calorie Ratio Calculator","Nutrition & Macros","Calculate protein grams per 100 calories.","Protein density = protein ÷ calories × 100",[field("protein","Protein / g",30),field("calories","Calories",300)],v=>result(n(v,"protein")/n(v,"calories")*100,"g/100 kcal","Protein density","Higher values indicate more protein relative to energy.")),
  make("macro-percentage-calculator","Macro Percentage Calculator","Nutrition & Macros","Convert protein, carbohydrate and fat grams into calorie percentages.","Protein/carbs = g×4; fat = g×9",[field("protein","Protein / g",150),field("carbs","Carbohydrate / g",250),field("fat","Fat / g",70)],v=>{const p=n(v,"protein")*4,c=n(v,"carbs")*4,f=n(v,"fat")*9,t=p+c+f;return result(`P ${(p/t*100).toFixed(0)}% · C ${(c/t*100).toFixed(0)}% · F ${(f/t*100).toFixed(0)}%`,"","Macro split","Uses 4 kcal/g for protein and carbohydrate and 9 kcal/g for fat.");}),
  make("net-carb-calculator","Net Carb Calculator","Nutrition & Macros","Calculate net carbohydrate as total carbohydrate minus fibre.","Net carbs = total carbohydrate − fibre",[field("carbs","Total carbs / g",40),field("fiber","Fibre / g",10)],v=>result(Math.max(0,n(v,"carbs")-n(v,"fiber")),"g","Net carbohydrate","Labeling conventions can differ and not every carbohydrate behaves identically.")),
  { id:"calorie-per-meal-calculator", slug:"calorie-per-meal-calculator", name:"Calorie per Meal Calculator", category:"Nutrition & Macros", requires:["height","weight","age","sex","activity"], description:"Divide estimated daily calories across a chosen number of meals.", formula:"Calories per meal = daily calories ÷ meals", ...extra([field("meals","Meals per day",4)]), computeExtra:v=>result(tdee(metric(v))/n(v,"meals",1),"kcal/meal","Meal calorie target","Meal distribution can be adjusted to preference and schedule.") },
  { id:"micronutrient-intake-calculator", slug:"micronutrient-intake-calculator", name:"Micronutrient Intake Calculator", category:"Nutrition & Macros", requires:["age","sex"], description:"Show selected daily micronutrient reference intakes by age and sex.", formula:"Reference values vary by age, sex and life stage", compute:s=>{const m=metric({state:s}),female=m.sex==="female";return result(`Calcium ${m.age<19?1300:1000} mg · Iron ${female?18:8} mg · Vit D 15 µg · Magnesium ${female?310:400} mg`,"/day","Selected reference intakes","General reference values, not individualized prescriptions.");}},
  make("running-speed-calculator","Running Speed Calculator","Running & Cardio","Calculate running speed from distance and elapsed time.","Speed = distance ÷ time",[field("distance","Distance / km",5),field("minutes","Minutes",30),field("seconds","Seconds",0)],v=>result(n(v,"distance")/((n(v,"minutes")*60+n(v,"seconds"))/3600),"km/h","Running speed","Calculated from distance and elapsed time.")),
  make("pace-to-speed-converter","Pace-to-Speed Converter","Running & Cardio","Convert running pace into speed.","Speed = 60 ÷ pace",[field("paceMinutes","Pace minutes / km",6),field("paceSeconds","Pace seconds / km",0)],v=>result(60/(n(v,"paceMinutes")+n(v,"paceSeconds")/60),"km/h","Equivalent speed","Assumes pace is minutes per kilometre.")),
  make("5k-time-predictor","5K Time Predictor","Running & Cardio","Predict 5K time from another race distance and time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>result(riegel(v,5),"minutes","Predicted 5K time","Riegel predictions are estimates; conditions and training affect performance.")),
  make("10k-time-predictor","10K Time Predictor","Running & Cardio","Predict 10K race time from another race distance and time.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",5),field("minutes","Known time minutes",27),field("seconds","Known time seconds",0)],v=>result(riegel(v,10),"minutes","Predicted 10K time","Prediction is an estimate based on the reference performance.")),
  make("half-marathon-time-predictor","Half-Marathon Time Predictor","Running & Cardio","Predict half-marathon time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>result(riegel(v,21.0975),"minutes","Predicted half-marathon time","Use as a training estimate, not a guarantee.")),
  make("marathon-time-predictor","Marathon Time Predictor","Running & Cardio","Predict marathon time using the Riegel model.","T2 = T1 × (D2/D1)^1.06",[field("distance","Known distance / km",10),field("minutes","Known time minutes",55),field("seconds","Known time seconds",0)],v=>result(riegel(v,42.195),"minutes","Predicted marathon time","Long-distance performance depends strongly on endurance and fueling.")),
  make("race-time-calculator","Race Time Calculator","Running & Cardio","Calculate elapsed race time from distance and pace.","Time = distance × pace",[field("distance","Distance / km",10),field("paceMinutes","Pace minutes / km",5),field("paceSeconds","Pace seconds / km",0)],v=>{const total=n(v,"distance")*(n(v,"paceMinutes")+n(v,"paceSeconds")/60);return result(`${Math.floor(total/60)}:${String(Math.round(total%60)).padStart(2,"0")}`,"hh:mm","Race time","Calculated from distance and target pace.");}),
  make("running-split-calculator","Running Split Calculator","Running & Cardio","Calculate average split time for a run or race.","Average split = total time ÷ number of splits",[field("distance","Distance / km",5),field("minutes","Total minutes",30),field("seconds","Total seconds",0),field("splitKm","Split distance / km",1)],v=>result((n(v,"minutes")+n(v,"seconds")/60)/(n(v,"distance")/n(v,"splitKm")),"minutes","Average split","Average time for the selected split distance.")),
  make("training-pace-calculator","Training Pace Calculator","Running & Cardio","Estimate a training pace from a recent race effort.","Training pace = race pace × selected multiplier",[field("distance","Race distance / km",5),field("minutes","Race minutes",25),field("seconds","Race seconds",0),field("factor","Training multiplier",1.15)],v=>result(((n(v,"minutes")+n(v,"seconds")/60)/n(v,"distance"))*n(v,"factor"),"min/km","Suggested training pace","Multiplier is a planning tool; effort and terrain should guide adjustments.")),
  make("vo2-max-calculator","VO₂ Max Calculator","Running & Cardio","Estimate VO₂ max from a Cooper-style 12-minute run distance.","VO₂max ≈ (distance in metres − 504.9) ÷ 44.73",[field("distanceMeters","12-minute distance / m",2400)],v=>result((n(v,"distanceMeters")-504.9)/44.73,"mL/kg/min","Estimated VO₂ max","Field-test estimate influenced by pacing, terrain and weather.")),
  make("strength-level-calculator","Strength Level Calculator","Strength & Gym","Estimate strength relative to body weight.","Strength ratio = 1RM ÷ body weight",[field("bodyWeight","Body weight / kg",85),field("liftWeight","Lift 1RM / kg",100)],v=>result(n(v,"liftWeight")/n(v,"bodyWeight"),":1 bodyweight","Strength ratio","Simple ratio, not an age- or sex-adjusted standard.")),
  make("strength-to-weight-ratio-calculator","Strength-to-Weight Ratio Calculator","Strength & Gym","Calculate lifting strength relative to body weight.","Ratio = lift ÷ body weight",[field("bodyWeight","Body weight / kg",85),field("liftWeight","Lift / kg",100)],v=>result(n(v,"liftWeight")/n(v,"bodyWeight"),":1","Strength-to-weight","Useful for tracking relative strength as body weight changes.")),
  make("bench-press-1rm-calculator","Bench Press 1RM Calculator","Strength & Gym","Estimate bench press one-repetition maximum.","Epley: 1RM = weight × (1 + reps/30)",[field("load","Bench weight / kg",80),field("reps","Repetitions",8)],v=>result(epley(v),"kg","Estimated bench 1RM","Epley is an estimate and becomes less reliable at high repetition counts.")),
  make("squat-1rm-calculator","Squat 1RM Calculator","Strength & Gym","Estimate squat one-repetition maximum.","Epley: 1RM = weight × (1 + reps/30)",[field("load","Squat weight / kg",100),field("reps","Repetitions",8)],v=>result(epley(v),"kg","Estimated squat 1RM","Use conservative loads when applying a predicted maximum.")),
  make("deadlift-1rm-calculator","Deadlift 1RM Calculator","Strength & Gym","Estimate deadlift one-repetition maximum.","Epley: 1RM = weight × (1 + reps/30)",[field("load","Deadlift weight / kg",120),field("reps","Repetitions",5)],v=>result(epley(v),"kg","Estimated deadlift 1RM","A predicted maximum is not a substitute for safe technique.")),
  make("rep-max-calculator","Rep Max Calculator","Strength & Gym","Estimate one-repetition maximum and equivalent target-rep load.","Epley 1RM = weight × (1 + reps/30)",[field("load","Weight / kg",80),field("reps","Repetitions",8),field("targetReps","Target repetitions",5)],v=>{const one=epley(v);return result(one/(1+n(v,"targetReps")/30),"kg","Estimated target-rep load","Equivalent loads are approximate." );}),
  make("training-volume-calculator","Training Volume Calculator","Strength & Gym","Calculate lifting volume as sets × repetitions × load.","Volume = sets × reps × load",[field("sets","Sets",4),field("reps","Repetitions/set",8),field("load","Load / kg",80)],v=>result(n(v,"sets")*n(v,"reps")*n(v,"load"),"kg","Training volume","Useful for comparing sessions using the same exercise and load convention.")),
  make("wilks-score-calculator","Wilks Score Calculator","Strength & Gym","Calculate a simplified Wilks-style score from body weight and total.","Score = total × coefficient ÷ body weight",[field("bodyWeight","Body weight / kg",85),field("total","Powerlifting total / kg",400)],v=>{const w=n(v,"bodyWeight"),x=w,coef=500/(47.46178854-7.209*x+0.000?1:1);return result(n(v,"total")*coef/w,"points","Wilks-style score","Simplified estimate; not for official competition scoring.");}),
  make("dots-score-calculator","DOTS Score Calculator","Strength & Gym","Calculate a simplified DOTS-style powerlifting score.","DOTS = total × coefficient(body weight)",[field("bodyWeight","Body weight / kg",85),field("total","Powerlifting total / kg",400)],v=>{const w=n(v,"bodyWeight"),a=-216.0475144,b=16.2606339,c=-0.002388645;return result(n(v,"total")*(500/(a+b*w+c*w*w)),"points","DOTS-style score","Simplified coefficient implementation; use federation rules for competition." );}),
  make("power-to-weight-ratio-calculator","Power-to-Weight Ratio Calculator","Strength & Gym","Calculate power output relative to body weight.","Power-to-weight = watts ÷ body weight",[field("power","Power / watts",300),field("bodyWeight","Body weight / kg",75)],v=>result(n(v,"power")/n(v,"bodyWeight"),"W/kg","Power-to-weight","Commonly used to compare power relative to mass.")),
  make("resting-heart-rate-calculator","Resting Heart Rate Calculator","Heart & Fitness","Calculate average resting heart rate from repeated readings.","Average RHR = sum of readings ÷ number of readings",[field("r1","Reading 1 / bpm",65),field("r2","Reading 2 / bpm",64),field("r3","Reading 3 / bpm",66)],v=>result((n(v,"r1")+n(v,"r2")+n(v,"r3"))/3,"bpm","Average resting heart rate","Measure under consistent resting conditions; interpretation needs context.")),
  make("heart-rate-recovery-calculator","Heart Rate Recovery Calculator","Heart & Fitness","Calculate the drop in heart rate after exercise.","HRR = peak exercise HR − recovery HR",[field("peak","Peak exercise HR / bpm",160),field("recovery","Recovery HR / bpm",120)],v=>result(n(v,"peak")-n(v,"recovery"),"bpm","Heart-rate recovery","Use the same recovery interval when tracking changes.")),
  make("heart-rate-reserve-calculator","Heart Rate Reserve Calculator","Heart & Fitness","Calculate heart-rate reserve from estimated maximum and resting heart rate.","HRR = estimated HRmax − resting HR",[field("age","Age / years",30),field("resting","Resting HR / bpm",60)],v=>result(220-n(v,"age")-n(v,"resting"),"bpm","Heart-rate reserve","220 − age is a population estimate and can differ from measured maximum heart rate.")),
  make("cardio-fitness-level-calculator","Cardio Fitness Level Calculator","Heart & Fitness","Classify an entered VO₂ max estimate into a broad fitness band.","Fitness band based on VO₂ max",[field("vo2","VO₂ max / mL/kg/min",40)],v=>{const x=n(v,"vo2");return result(x<30?"Low":x<40?"Fair":x<50?"Good":"Very good","","Broad cardio fitness band","Broad classification only; norms differ by age, sex and population." );}),
  make("aerobic-training-zone-calculator","Aerobic Training Zone Calculator","Heart & Fitness","Estimate an aerobic training heart-rate zone using heart-rate reserve.","Karvonen target = resting HR + intensity × HRR",[field("age","Age / years",30),field("resting","Resting HR / bpm",60),field("low","Low intensity / %",60),field("high","High intensity / %",70)],v=>{const hrr=220-n(v,"age")-n(v,"resting");return result(`${Math.round(n(v,"resting")+hrr*n(v,"low")/100)}–${Math.round(n(v,"resting")+hrr*n(v,"high")/100)}`,"bpm","Estimated aerobic zone","Heart-rate zones are estimates and can be altered by medication, fitness and measured maximum heart rate." );}),
  make("anaerobic-threshold-calculator","Anaerobic Threshold Calculator","Heart & Fitness","Estimate threshold heart rate from a sustained hard effort.","Threshold estimate = average HR during a sustained threshold effort",[field("heartRate","Average hard-effort HR / bpm",165)],v=>result(n(v,"heartRate"),"bpm","Threshold estimate","A field estimate is not the same as a laboratory lactate or ventilatory threshold test.")),
  make("pulse-pressure-calculator","Pulse Pressure Calculator","Heart & Fitness","Calculate pulse pressure from systolic and diastolic blood pressure.","Pulse pressure = systolic − diastolic",[field("systolic","Systolic / mmHg",120),field("diastolic","Diastolic / mmHg",80)],v=>result(n(v,"systolic")-n(v,"diastolic"),"mmHg","Pulse pressure","Blood-pressure interpretation should use repeated measurements and clinical context.")),
  make("mean-arterial-pressure-calculator","Mean Arterial Pressure Calculator","Heart & Fitness","Estimate mean arterial pressure from systolic and diastolic blood pressure.","MAP ≈ (SBP + 2×DBP) ÷ 3",[field("systolic","Systolic / mmHg",120),field("diastolic","Diastolic / mmHg",80)],v=>result((n(v,"systolic")+2*n(v,"diastolic"))/3,"mmHg","Estimated MAP","Approximation, not a substitute for clinical assessment.")),
  make("rate-pressure-product-calculator","Rate Pressure Product Calculator","Heart & Fitness","Calculate rate-pressure product from heart rate and systolic blood pressure.","RPP = heart rate × systolic blood pressure",[field("heartRate","Heart rate / bpm",70),field("systolic","Systolic BP / mmHg",120)],v=>result(n(v,"heartRate")*n(v,"systolic"),"bpm·mmHg","Rate-pressure product","RPP is an exercise/cardiovascular workload index, not a diagnosis.")),
  make("fitness-age-calculator","Fitness Age Calculator","Heart & Fitness","Estimate a simple fitness age from chronological age and VO₂ max.","Fitness age = age + 0.5 × (35 − VO₂max)",[field("age","Age / years",30),field("vo2","VO₂ max / mL/kg/min",40)],v=>result(Math.max(18,n(v,"age")+(35-n(v,"vo2"))*.5),"years","Estimated fitness age","Illustrative estimate only; validated equations vary by assessment method.")),
];